### ISSUE TITLE
OpenEXR saving Fix

### ISSUE THREAD

**Issue by 360highdynamicrangehdr** [ggarra13/mrv2#100]
When using **File > Save > Movie or Sequence**

When using **File > Save > Single Frame**

![Untitled 147](https://github.com/ggarra13/mrv2/assets/25839678/c267baa2-30de-4d07-bdce-7219c86f7c99)

Pixel Type Half or Float not work?

```
ERROR: [save] Cannot create color texture
```

**Comment by ggarra13** [comment]
To save on Half or Float, you need to turn on Annotations as you are problably saving a movie file that is encoded as YUV.  That will capture the screen.

**Comment by ggarra13** [comment]
I realized that saving was partially broken without Annotations, particularly on Windows.  I have updated the v0.7.5 release with new binaries.
Please download them and report back if you get errors.
