### ISSUE TITLE
Occupied resources

### ISSUE THREAD

**Issue by ags1234** [ggarra13/mrv2#101]
Downloaded file mrv2-v0.7.5-Windows-amd64.zip.
This file uncompressed is 550 MB on disk and 13.323 files.
When playing a 1 GB movie mrv2 is using 7.300 MB of RAM.

By comparison, PotPlayer is 108 MB on disk and 169 files.
When playing the same movie is using 131 MB of RAM.

At this point I cannot name another video player in the world that takes 7 GB to play a 1 GB file.

Why is mrv2 absolutely wasting user's resources?

**Comment by ggarra13** [comment]
mrv2 occupies much more on disk as it supports four additional things: Pixar's USD (Universal Scene Description) scenes, flipbook of images, Python support and Network connections.  Also, the HTML documentation for the API takes quite some disk space.

Regarding the memory usage, that is totally controllable.  The default is to try to cache half of your RAM to make scrubbing smoothly.

You can go to Panels->Settings (Default F9) and set the Cache to the value on Gigabytes.  If you want to save the most memory, you can Set the GB Cache to 0 and let the Read Ahead/Read Behind control the cache, albeit with a Cache of 0, the movie may not scrub smoothly.
