### ISSUE TITLE
"Corruption in hotkeys preferences"

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#102]
Hi there,

with the latest versions of mrv2 I'm always getting this error message on startup:

`ERROR: [keys] Corruption in hotkeys preferences. Hotkey Ctrl+s for Save Session will not be available.  Already used in Save Image`

I already deleted the prefs in ~/.filmaura but to no avail.

**Comment by ggarra13** [comment]
Thanks for reporting that.  You need to delete the ~/.filmaura/mrv2.keys.prefs and that should fix it.  If it doens't let me know, and I'll look into it further.

**Comment by ggarra13** [comment]
Alternatively, if you have already set your own hotkeys and don't want to lose them, you can go into Windows->Hotkeys and look for Ctrl+s in Save Image and Save Session.

**Comment by ggarra13** [comment]
I can verify that going to Windows->Hotkeys and hitting Save and overwriting the the default mrv2.keys.prefs fixes the issue.

**Comment by SteffenDuenner** [comment]
Thanks for your quick reply.
Just hitting Save didn't help in my case, but deleting the ~/.filmaura/mrv2.keys.prefs file did.
Strange thing is that yesterday I deleted the contents of the whole ~/.filmaura/ folder but that didn't work.

**Comment by ggarra13** [comment]
That's weird.  I am trying to figure out how the hotkey corruption happened, as I could not reproduce it by installing older released versions of mrv2.  Did you compile from source by any chance (I might have mistakenly introduced the issue on some commit)?
Also, you did not happen to keep the old mrv2.keys.prefs by any chance so I can take a look?

**Comment by SteffenDuenner** [comment]
Yes, I compile mrv2 myself so that might be the cause.
I still have the mrv2.keys.prefs file that got created after I deleted the "original" one that showed this error message for the first time.
IIRC this one also threw an error but I might be wrong. I attached it nonetheless.

[mrv2.keys.prefs.zip](https://github.com/ggarra13/mrv2/files/12582929/mrv2.keys.prefs.zip)

**Comment by ggarra13** [comment]
Thanks for the hotkeys file.  I was able to reproduce the issue, and I have made the hotkey message not appear when the reason is a new hotkey is added and you have already set hotkeys to the same hotkey.
