### ISSUE TITLE
Unable to play .mkv files

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#103]
mrv2 version 0.7.5 on windows is unable to play my .mkv files. When i open one, mr viewer shows the log window with this error message at the bottom:

> ERROR: [] 0.599708 mrv2: C:\Users\username\Videos\testvideo.mkv: Cannot read timeline

Interestingly, there is an easy fix: change the file's ending to .mp4, then it plays the file as expected. 

The mkv files i tested are from a screenrecording made with OBS. Here is one of them for reference: https://mega.nz/file/V3QiiDyL#iHl-FaxzgLZZLkBtkBBtqSdm02HqujVrseJvH3EHpzs

**Comment by ggarra13** [comment]
Thanks for reporting this.  Here's a beta of v0.7.6 for Windows that fixes it:

.exe installer:
https://mega.nz/file/ua51FKwL#g4tssAkXHvR6hmi-pAUFc_jblS1wr63_hy6pP4iwXeI

.zip archive:
https://mega.nz/file/uWwVmSQZ#UMyzNG2Hx3vHOgrLn8OMW6jf8rrPY75jNQlitMVLb6o
