### ISSUE TITLE
mrv2 has no icon in the "installed programs" list of Windows

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#104]
mrv2 has no icon in the list of installed programs in windows, which makes it harder to find. 

Right now it looks like this in the Windows 11 settings app:
![Screenshot 2023-09-13 094136](https://github.com/ggarra13/mrv2/assets/13683581/2d5a9db2-5066-4b3b-b706-09074530af33)

And in the classic control panel:
![Screenshot 2023-09-13 094147](https://github.com/ggarra13/mrv2/assets/13683581/c85c2e1a-379e-48d3-965a-c03ad61641a0)

**Comment by ggarra13** [comment]
Thanks for reporting it.  I have now fixed the Windows installer to install the icon also on Windows 11's Settings->App->Installed apps.  It should show everywhere from the next version on.

Also, I improved the quality of the icon too.
