### ISSUE TITLE
Video Drag & Drop doesn´t work at sometime anymore.  

### ISSUE THREAD

**Issue by arfx** [ggarra13/mrv2#108]
Hey, 
first of I really love your tool, it´s awesome. I used the last years Keyframe but yours is even more packed with awesome features. 

**But now to my Issue/Bug.**
I noticed after a while of using mrv2 that I can´t drag and drop some video files in the tool. 

I haven´t found yet the breaking point, but for reproduce, a short summary where I get it breaking at some point.

Open mrv2 and have a explorer with multiple videos next to it open. 
- Drop a file in mrv2 scrub a bit around
- made some small annotations
- maybe even copy a frame or similar edit
- repeat this multiple time. 

At some point I can´t drag and drop some file into mrv2.

**Comment by ggarra13** [comment]
1)  Are you using mrv2 v0.7.6 by any chance?  v0.7.5 had a serious memory bug that could cause all sort of issues when pasting frames.
2) Do you think you could do a video capture of what you are doing to break it?

**Comment by arfx** [comment]
Yes, I get it in both versions. 
Also, it does not directly have something to do with copy/paste frames. 
I get it also sometimes if I open only the files panel. 

For example, look at the video https://github.com/ggarra13/mrv2/assets/8065400/c6968501-50e1-472e-ae24-532af2764b29

**Comment by ggarra13** [comment]
I was able to reproduce it.  I will investigate.

**Comment by ggarra13** [comment]
Here's a beta version of v0.7.7 that should fix the drag and drop issue.  Please report back if it fixes things on your end and if you find any other bugs.

Windows .exe installer:
https://mega.nz/file/PPAFwLCL#BWaz7jYhiL4715uyz0RND-Hi5QWOKwnN_eSAFiXFYrQ

**Comment by arfx** [comment]
The new version fixed that Issue. 🙏
