### ISSUE TITLE
PDF Export doesn´t have (frame - timecode - secs) codes and isn´t chronology sorted 

### ISSUE THREAD

**Issue by arfx** [ggarra13/mrv2#110]
The Save > PDF Document (Annotation/Notes Export) is really cool Feature and works really well. 
The only what I noticed which is probably a BUG that the "frame - timecode - secs" are not correctly displayed.
Also don´t know what is currently the sort of that but it seems, from the creation of the annotation, could this be a **setting** or changed to the timecode.

![image](https://github.com/ggarra13/mrv2/assets/8065400/c68d2e3c-d2da-4e05-8f3b-b24a4eaaee8f)

**Comment by ggarra13** [comment]
Try this new beta of v0.7.7 that should address both issues (bugs).  Keep the bugs coming!

.exe installer:
https://mega.nz/file/PWYEkAyJ#uJye0-fod0XQFbfjAWbSsUkJoKrGI7RmXEoNAOFC1AQ

**Comment by ggarra13** [comment]
I had to take out the previous .exe as it was showing things still in development.   You should find this next beta fixes both bugs you reported (frame/timecode/secs missing and order of annotations).

.exe installer:

https://mega.nz/file/GHhlzLZA#nmz-JBeabYfqtorz3slKqiO9UIbNcbVRXsXqWSo5SCU

**Comment by arfx** [comment]
Works in that version 👍
