### ISSUE TITLE
Compare via Wipe doesn´t work

### ISSUE THREAD

**Issue by arfx** [ggarra13/mrv2#111]
I tried the compare feature and all modes are working fine, only the Wipe between picture A  & B doesn´t work.
If I use ALT key and Left Mouse Button Hold, I see the slider Values moving but nothing from the second picture. 

I even check your https://youtu.be/roD4WexsLZs Video Tutorial for that and it seems quite useful.

![mrv2_2023-09-19_08-04-27](https://github.com/ggarra13/mrv2/assets/8065400/d72052b6-7577-476d-9dca-3ff8cc527435)

**Comment by ggarra13** [comment]
I can confirm the feature is broken.  Currently selecting the Wipe mode concatenates the two movie files instead of playing them together.
This is an issue for Darby Johnston, as it is probably something that got broken in tlRender.  It may take some time to fix.  I apologize for that.

**Comment by ggarra13** [comment]
Here's a new version of mrv2 v0.7.7 beta that fixes the Comparison Wipe.   It also adds an addition to the color picker of seven saved colors.  I plan to make it better and more interactive like Krita, but it will do for now:

https://mega.nz/file/bXwXRLrZ#OFZeg46S0j8aENGuT5oJekmTnNELtlFtdFJxo_7cOXc

**Comment by ggarra13** [comment]
Please download v0.7.7 instead as it was just released.

**Comment by arfx** [comment]
works again , great 👍
