### ISSUE TITLE
Color Palette or previous Color for Annotation - idea

### ISSUE THREAD

**Issue by arfx** [ggarra13/mrv2#112]
This is only an Enhancement idea for Color of the Annotations.

It would be useful if you have a smaller (or not scaling) Color Selection Area. And next to it´s a Color Palette (4-5) or only the latest Color. That you can switch between Colors faster and don´t need to pick manual the color again. 

Similar to like Photoshop or Krita like a switch function next to the main Color. Or even better a dynamic Color Palette, which creates a List of the latest picked Colors.

![krita_2023-09-19_08-14-56](https://github.com/ggarra13/mrv2/assets/8065400/d8dfc785-65bb-4d1a-ba18-581b834f615c)

**Comment by ggarra13** [comment]
Please update to v0.7.7 that was just released that fixes some bugs and adds the Krita functionality you described.

**Comment by arfx** [comment]
This was very fast implemented 🙏 and works as it should. 
Only improvements I could see are:  
- in the color selection the latest color should always be on the top right and the before should go down in the list
 (and not going the list from top to bottom again, like currently)
![explorer_2023-09-20_08-09-32](https://github.com/ggarra13/mrv2/assets/8065400/8b439079-ecc4-4f48-a534-9d9bf2d033ed) 


- the switch button should also be in the hotkeys selection present

**Comment by ggarra13** [comment]
Both things have been added to main HEAD and should be in the next version.
