### ISSUE TITLE
Text Annotations - should also be eraseable when Baked into the frame - idea

### ISSUE THREAD

**Issue by arfx** [ggarra13/mrv2#113]
I don´t think this is a Bug, it's probably more of an enhancement.

If the Text is Bake into the Frame by pressing the x on the Text Annotation. It would be useful if you could also erase that.
 
Sure you can always undo the last steps from the annotation but only the last. If you have done after the text something else you need to undo this first before and then can only undo the Text Annotation.

**Comment by ggarra13** [comment]
Would a Clear Text Annotations to the Annotation Panel fix this?  Currently, the Eraser tool does not work with Text annotations unfortunately, as they are always drawn last.

**Comment by arfx** [comment]
Ah, I don´t know. 
Sure that would solve that issue, but this would add another button somewhere. 
Plus I assume it would then also delete all Text Annotations again. Which is also not the best. 

An example 
I can remember where Feedback was written in multiple longer Text & Drawing Annotations, on single Frames which would need redone then completely if you make a delete Text Annotations option.

**Comment by ggarra13** [comment]
I have come up with a solution to allow you to edit the baked text annotations.  Add some Text annotations with the text tool.  Then, with the right mouse button on the Text Tool a new window will appear.  From it, select the annotation you want to edit.  Click on Edit Text and you will be back in Text Editing mode.

Windows .exe installer:
https://mega.nz/file/KCIGXQRR#RXCjNkotsDblImEPzR_JdymLkR2YA-UB0qtjPT7BVRo
