### ISSUE TITLE
add LibRaw 0.21 support

### ISSUE THREAD

**Issue by 360highdynamicrangehdr** [ggarra13/mrv2#115]
RAW digital camera files [here](https://www.libraw.org/).
A variety of digital camera “raw” formats

**Comment by ggarra13** [comment]
I have added RAW support in main HEAD and it should be in the next release.  I think you compile from source, so you can already test it.

**Comment by ggarra13** [comment]
Here's a beta of v0.7.8 for you to try:

Windows .exe installer:
https://mega.nz/file/KCIGXQRR#RXCjNkotsDblImEPzR_JdymLkR2YA-UB0qtjPT7BVRo

**Comment by ggarra13** [comment]
Added in released v0.7.8.  Closing the issue now.
