### ISSUE TITLE
Windows installer minor bug: unticking "File associations" checkbox still prompts for them

### ISSUE THREAD

**Issue by darkvertex** [ggarra13/mrv2#12]
So just a little detail I noticed: If I untick "_File associations_" in the installer components when running the Windows installer, it still prompts afterwards for them, and they're all ticked by default, completely ignoring my checkbox decision.

It's easy enough to hit "Uncheck all" and move on, but thought I'd report it.

**Comment by ggarra13** [comment]
This is fixed in current HEAD (will be in next version).  I removed the option as the things to install and instead after the install you will get a requester asking if you want to install shortcuts.  This is better as it allows me to translate the requester to other natual languages.
