### ISSUE TITLE
Export an .otio timeline from MRV2

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#121]
With the introduced timeline editing tools writing changes into an `.otio` file might make sense. 
However, I'm unable in the UI to find how to save out an OTIO file of the current timeline?

I would have expected File > Save to have a menu entry for "otio" or "timeline" or alike.

**Comment by ggarra13** [comment]
It is in the Playlist Panel, with an icon that looks like a disk.  I'll see to add it to the File menu too.

**Comment by ggarra13** [comment]
It has been added to the File->Save->OTIO EDL Timeline menu entry in v0.7.9.

**Comment by BigRoy** [comment]
Can confirm this works. Thanks!
