### ISSUE TITLE
Python cmd module exposes command oepnSession, typo?

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#123]
It seems the python facing command for 'openSession' has a typo in the codebase.

See the [search](https://github.com/search?q=repo%3Aggarra13%2Fmrv2%20oepnSession&type=code) on `oepnSession` with the source of the typo originating [here](https://github.com/ggarra13/mrv2/blob/6466b1474325b99d2ce4f6ce81e91fc7aa3c5bab/mrv2/lib/mrvPy/Cmds.cpp#L512)

`oepnSession` should be refactored `openSession`

**Comment by ggarra13** [comment]
Yes.  It is a typo.  Fixed in HEAD and beta branch
