### ISSUE TITLE
Allow plugin menu to add a separator/divider

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#126]
### Issue

I'd like a `mrv2.plugin.Plugin` to be able to define separators in the return value for `menus` to be able to add the grey dividers like in this menu:

![image](https://github.com/ggarra13/mrv2/assets/2439881/8a60048d-89d9-45be-87cc-cd1a27ae6b71)

### Idea

I was thinking something along the lines of a special value (since the it's a `dict` we can't repeat the same separator key)

```python
from mrv2 import plugin

# Assume this is defined in the plugin module
plugin.MENU_SEPARATOR = "<SEPARATOR>" # or whatever you want as identifier


def stub():
    """Do nothing function just for sake of the example."""
    pass


class MyPlugin(plugin.Plugin):
    def menus(self):
        top = "MyMenu"
        return {
            f"{top}/Alpha Channel": stub,
            f"{top}/-separate-1": plugin.MENU_SEPARATOR,
            f"{top}/Mirror X": stub,
            f"{top}/Mirror Y": stub,
            f"{top}/-separate-2": plugin.MENU_SEPARATOR,
            f"{top}/Black Background": self.on_manage
        }

```

That's a quick pseudocode example. It is up to the user to still ensure unique keys for the dict however.

Looking at the code above we might also want to reconsider supporting another return type instead of a `dict` just so technically we don't require keys to be unique or at least allow. But that could be a topic for another issue down the line since the implementation would likely be more involved. By expanding the API for that it might also allow e.g. setting shortcuts for the menu entries, etc?

**Comment by ggarra13** [comment]
Here's the API I implemented:

```
    """
    Return the menus to add to mrv2's main toolbar.
    You can add your commands to mrv2 menus or create a new
    menu entry. Each Submenu is separated by '/'.
    Currently, you cannot remove a menu entry.

    Returns:
    dict: a dictionary of key for menu entries and values as methods.
          The value can be a tuple to add options like a divider for a menu
          entry.
    """
    def menus(self):
        menus = {
            # Call a method and place a divider line after the menu
            "Python/Play/Forwards" : (self.play, '__divider__'), 
            "Python/Play/Backwards" : timeline.playBackwards # call a function
        }
        return menus
```

**Comment by BigRoy** [comment]
Thanks - looks fine with me - so is this [particular commit example wrong](https://github.com/ggarra13/mrv2/commit/bb938871fe5fcc9548a6f8539a4448af8d8640e5#diff-88f53a47649158ee32a2ebb8dc638049b502b2a9f122aa3d98446fa0665233b6R90)?
