### ISSUE TITLE
Run Python module scripts like pip install against mrv2's python executable

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#127]
### Issue

I wonder whether it'd be possible to somehow run e.g. `mrv2 -m pip install PySide2` using the executable of MRV2 itself with its Python interpreter.

Without that I'd need to create a matching Python version environment on my machine, and then `pip install PySide2 --target /my/libs` and launch `mrv2` with those libs on `PYTHONPATH` to have them available.

Note: `PySide2` is just an example here.

### Just to showcase the `-ps` flag doesn't allow it (logically)

```bat
>mrv2 -ps -m pip install PySide2
>Could not read python script '-m'
>mrv2 -ps pip install PySide2
>Could not read python script 'pip'
```

---

### Workaround

Another approach could be to run it within MRV2 itself using the PIP package, but it is _not_ recommended to do so.

```python
import pip

# Recent versions of PIP have `main` moved to internals to be clear about
# the fact that is not the recommended way to access it. This could be the
# case whenever user might have upgraded MRV2's pip package
if hasattr(pip, "_internal"):
    main = pip._internal.main
else:
    main = pip.main

main(["install", "PySide2"])
```

**Comment by ggarra13** [comment]
Can't you run the command with Python's subprocess module?

**Comment by BigRoy** [comment]
> Can't you run the command with Python's subprocess module?

No, because as far as I know there's no way to call `pip` itself against the `MRV2` python interpreter since it's embedded within MRV2 itself. Right? As such you can't trigger `__main__` from `pip` package as a module as would usually be the case with:

```
python -m pip install PySide2
```

In some pip installs a `pip.exe` also gets generated, so that one could do:
```
pip install Pyside2
```
_But that might still need to have `python` be available on path as executable unless the executable manages to get by with just the `python3.dll` that is in `mrv/bin`.

**Comment by ggarra13** [comment]
No.  The issue is that I forgot to include the python.exe (Windows) and python3.10 (macOS and Linux) inside the bin/ directory of mrv2.  They are less than 1MB to bundle them.  You would then be able to run them manually with:
```
mrv2_dir/bin/python.exe -m pip install <whatever>
```

or from a script with the subprocess module.

Anyway, check for the v0.8.0 beta build on sourceforge in a couple of hours.
