### ISSUE TITLE
Store custom metadata in the current session

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#128]
### Issue

I'd like to be able to manage custom metadata, e.g. json data or a `dict` of data into the current session, preferably on:

1. Session-level, not related to any file in the playlist, but globally for the session file.
2. File-level, per playlist entry metadata,
3. Per clip level in an edit, this is likely metadata at the `otio` item level and likely just needs to be done through the `opentimelineio` api, yes?

The idea is that each of the metadata to be assigned would save along (serialize) with a MRV2 session save and get restored on opening the MRV2 session.

**Comment by ggarra13** [comment]
Added setSessionMetadata() and sessionMetadata() functions in HEAD.

The other ones might require more work.

**Comment by BigRoy** [comment]
This does work - but I wonder whether the design is as we want it. It seems that `setSessionMetadata` is capable of setting a single string, e.g.:

```python
from mrv2 import cmd
cmd.setSessionMetadata("TEST")
print(cmd.sessionMetadata())
# TEST
```

Which would allow me to essentially store any metadata as e.g. a JSON serialized string in there. However, if multiple plugins for MRV2 would like to store their own session metadata quickly the issue would arise that the metadata would conflict and they would either ALL need to enforce using json serialized string at the top level or basically override each other's values, etc.

By design I think it might be better to be able to either store a `dict` of data, so that e.g. a plugin could only update a certain key:

```

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

# Override all data
data = {
    "plugin1.setting_x": "hello_world",
    "plugin1.setting_y": 1,
    "plugin2.setting_x": "foobar"
}
cmd.setSessionMetadata(data)

# Add only your own data
data = cmds.sessionMetadata()
data["plugin1.setting_x"] = "hello_world"
cmds.setSessionMetadata(data)
```

Or, that instead you be setting metadata into a pre-specified key, e.g. 

```
cmds.setSessionMetadata("key1", "value1")
```

So that plugin X could do:
```python
cmds.setSessionMetadata("pluginx_data", "serialized_json_data_for_plugin_x")
```

Getting the data would then either:
```python
data = cmds.getSessionMetadata()
# {
#  "pluginx_data": "value_x"
#  "pluginy_data": "value_y"
# }
```
Or:
```
data = cmds.getSessionMetadata("pluginx_data")
# "value_x"
```

If the data would be stored per key then likely it might also need a `cmds.listSessionMetadataKeys()` or whatever method.
What do you think would be the best approach?

Storing per key would at least ensure you wouldn't need the full dict from session metadata to 'append' your data into it.

**Comment by ggarra13** [comment]
I need to think about it and play with the code a little to see what's best.

**Comment by ggarra13** [comment]
I created a new submodule called session (ie. mrv2.session).  It contains all the loading/saving functionality and the metadata now kepts in a dict.  It is also documented.

**Comment by BigRoy** [comment]
Love it - this works flawlessly. 

Will need to move some things around since the other session methods for save/load also moved there but that's fine in the 0.x release cycle I suppose.
