### ISSUE TITLE
Some crashes on Linux

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#13]
Hi there, great to see mrViewer get a well deserved upgrade :)

I know mrv2 is still in it's infancy, but I noticed some crashes during my first tests:

- If I open Preferences, go to Playback and then click on the "FPS" menu / switch, mrv2 instantly crashes.
- If I go to the OCIO tab in the Preferences and change the OCIO config to something other than the nuke-default coming with mrv2, it works. If I now click the option to "Save OCIO Config File in Preferences", hit OK and re-open the Preferences (or mrv2) the OCIO config is back to nuke-default.
- There were several crashes during changing and trying to save some Preference values.
- I could not set or assign the Input Color Spaces in the prefs. If I click on "Pick", mrv2 closes.

I noticed that in the hidden ./filmaura folder there are several prefs, some still named "mrViewer" which I thought were remnants of the old mrViewer installation. So I deleted the whole folder to have a fresh start, but mrv2 created the pref-files again:
![image](https://user-images.githubusercontent.com/33224667/219331500-0d1b067e-7895-4bc7-9b5b-0c3453bbb3f2.png)

I don't know it this is part of the problem?

**Comment by ggarra13** [comment]
@SteffenDuenner Hi.  Thanks for reporting those bugs.  I have a prerelease of v0.3.3 that you can try and see if it fixes your bugs:

tar.gz
https://mega.nz/file/mG5jVIAD#_TMrUBehpUdqs2BTysq6moPWEb5AiS-m3TIBCRsFEXM

.rpm
https://mega.nz/file/HaYzzTKR#7MOiLthuPSGuLLG77epr1abKiYMH9KMsNkaoMAy2zS8

.deb
https://mega.nz/file/GL51RTAJ#Mxb5KQpnz4V_r4ov0uQdIgRjkr2iZCnHm-dOyEyw_to

Let me know if you find mre bugs.  The .filmaura preferences are fine.  mrViewer.prefs and mrViewer.keys.prefs correspond to the original mrViewer.  mrv2*.prefs corresponds to the new mrv2 program.  The mrViewer2.prefs file is outdated (used in v0.3.1 I think by mistake).  You can deletet it.
