### ISSUE TITLE
Set FPS and OCIO Color space via Python API

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#133]
### Issue

I seem to be unable to find how to **set the FPS** (Speed) and the **OCIO Input Color Space** and **OCIO Output Color Space** for a loaded clip via Python API.

These are exposed for the `mrv2` command line interface - but I can't find how to set them via Python during the MRV2 session.

I must be blind - or these are not exposed yet. 🤓 

---

Side question: For an EDL (otio timeline) - are the OCIO colorspaces per clip, or is the Color Space a global viewer colorspace. I can imagine we might need to have an OCIO / LUT, etc. to be set per item in the timeline.

**Comment by ggarra13** [comment]
The OCIO color spaces are currently global.  There's currently no way to embed the metadata on the OTIO .otio file, unless we rely on some (custom) metadata.

**Comment by ggarra13** [comment]
I added the commands image.setOcioIcs(), image.setOcioView() to set the values and without the set to retrieve them.  Also added the list of Ics with ocioIcsList() and ocioViewList().

**Comment by ggarra13** [comment]
timeline.setSpeed(), timeline.speed() and timeline.defaultSpeed().

**Comment by BigRoy** [comment]
Just wanted to say - you're on fire 🔥 
Nice work. Looking forward to the next compiled release.
