### ISSUE TITLE
FPS field left click drag forces value between 0.0-1.0

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#134]
### Issue

The FPS field at the bottom of the timeline allows you to left click drag to tweak the FPS value - which is nice! Unfortunately when click+dragging it forces the value between 0.0 and 1.0.

I'm referring to this field:

![image](https://github.com/ggarra13/mrv2/assets/2439881/0f88d83b-8bda-4476-8350-9d33cc5e6ae2)

It would be nice if at the very least it defaults to a 0.0-60.0 range or alike.

Having this draggable for your FPS can help an animator easily spot whether maybe there animation is just a tad to fast or slow.
It sometimes also helps to just slow down the playback (even if to a non-exact frame range) just to check frame-by-frame some parts of your animation.

**Comment by ggarra13** [comment]
Fixed in HEAD.
