### ISSUE TITLE
Unable to access image.AlphaBlend.None in Python

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#140]
### Issue

In Python it's not allowed to access an attribute named `None` it seems.

As such:
```python
from mrv2 import image

mode = image.AlphaBlend.None
```

Results in a SyntaxError even though it does have the property:
```python
print(dir(image.AlphaBlend))
# ['None', 'Premultiplied', 'Straight', '__class__', '__delattr__', '__dir__', '__doc__', '__entries', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__le__', '__lt__', '__members__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', 'name', 'value']
```

### Workaround

A workaround is to access it using `getattr`:

```python
blend = getattr(image.AlphaBlend, "None")
```

But it feels weird. 

### Proposal

It might be better to make the alues accessible via e.g. `image.AlphaBlendNone`?
By prefixing them it might also avoid some of the clutter in the `image` module:

```python
print(dir(image))
# ['AlphaBlend', 'Anaglyph', 'BT2020', 'Channels', 'Checkerboard', 'Color', 'Columns', 'DisplayOptions', 'EnvironmentMapOptions', 'EnvironmentMapType', 'FromFile', 'FullRange', 'Image', 'ImageFilter', 'ImageFilters', 'ImageOptions', 'InputVideoLevels', 'LUTOptions', 'LUTOrder', 'LegalRange', 'Levels', 'Linear', 'Mirror', 'Nearest', 'None', 'OpenGL', 'PostColorConfig', 'PreColorConfig', 'Premultiplied', 'REC709', 'Scanlines', 'SoftClip', 'Stereo3DInput', 'Stereo3DOptions', 'Stereo3DOutput', 'Straight', 'VideoLevels', 'YUVCoefficients', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'ocioConfig', 'ocioIcs', 'ocioIcsList', 'ocioView', 'setOcioConfig', 'setOcioIcs', 'setOcioView']
```
It's a bit unclear there that `None` is part of the `image.AlphaBlend` settings, etc.

**Comment by BigRoy** [comment]
If I work around setting the image filters and do e.g. this:
```python

import mrv2
from mrv2 import annotations, cmd, math, image, io, media
from mrv2 import playlist, timeline, usd, settings

options = cmd.imageOptions()
options.alphaBlend = getattr(image.AlphaBlend, "None")
cmd.setImageOptions(options)
```
Then I do not see the Render menu entry update accordingly:

![image](https://github.com/ggarra13/mrv2/assets/2439881/80825ce9-b707-4311-9205-2f6bc7b9ca69)

Even though requerying through Python does show it was updated:
```python
print(cmd.imageOptions())
<mrv2.image.inageOptions videoLevels=FromFile alphaBlend=Straight imageFilters=<mrv2.image.ImageFilters minify=Linear magnify=Linear>>
```

As such it seems the menu entries do not stay in sync when updating the image options through the Python API.

**Comment by ggarra13** [comment]
Ok. A lot to comment.  New beta on sourceforge on the beta dir.

1) I've renamed all enum entries that were None as kNone, to make it simpler.  
2) The enum classes don't have constructors that allow multiple arguments.  You need to instantiate the class (or retrieve it from cmd.imageOptions()  for example) and then change the values of its members.  Then you set the new values with cmd.setImageOptions(opt) and the like. 
3) You were indeed correct that the values were not being updated in the menus.  That is now fixed.

**Comment by BigRoy** [comment]
1. Latest beta indeed exposes `kNone`
2. Not sure how that works - can't get it to work in latest beta.
3. Menus indeed update - e.g. following now works fine:

```python
options = cmd.imageOptions()
options.alphaBlend = image.AlphaBlend.kNone
cmd.setImageOptions(options)
```

**Comment by ggarra13** [comment]
I fixed that in the latest beta on sourceforge.

**Comment by ggarra13** [comment]
Can I close this issue?
