### ISSUE TITLE
add theme for mrv2 like zynaddsubfx

### ISSUE THREAD

**Issue by theavege** [ggarra13/mrv2#142]
Hello.

Please add a theme for mrv2 like [zynaddsubfx](https://zynaddsubfx.sourceforge.io).

Sincerely,
Artem

**Comment by ggarra13** [comment]
What exactly do you like about that look?  The interface of a synthesizer is very different from that of a video player.  You can probably create a new color scheme if you modify mrv2's Black color theme to add one (in the colors/ directory of mrv2) with a bright cyan color.

**Comment by theavege** [comment]
Hello @ggarra13 

Thank you for your reply.
I like the main theme of mrv2, but I think
the color scheme of a synthesizer will be more expressive
and text color does not blend with background color.
I will create a new color scheme based on your advice.

Sincerely,
Artem
