### ISSUE TITLE
Prores4444 does not read alpha

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#143]
### Issue

Not entirely sure why but comparing to `djv` then `mrv2` doesn't seem to correctly load alpha for Prores4444 files.

![prores_4444_no_alpha](https://github.com/ggarra13/mrv2/assets/2439881/e85a94ba-a516-4b19-b5ee-083c8263849b)

Is this just an issue with the automated builds due to licensing? or an actual bug?

**Comment by ggarra13** [comment]
Not sure.  Prores is the property of Apple so there *may* be licensing issues.

Can you share the movie file publicly?  If not, you can send a link to my email at ggarra13@gmail.com?

**Comment by BigRoy** [comment]
I shared the file by e-mail.

**Comment by ggarra13** [comment]
Fortunately it is not a limitation of Apple.  It was a missing feature in tlRender.

I uploaded a new beta to the sourceforge site (beta folder):

https://sourceforge.net/projects/mrv2/files/beta/

It has:

1) Proper handling of alpha channels on video codecs that FFmpeg support.
2) Python Editor fixes (hopefully, there are no more errors, but let me know if there are still things broken).
3) Python Classes now have keyword constructors besides the default one.

I will see if in the next release I get: scrubbing without having to press play, default preferences for Image and Display Options, a new API for session metadata.

**Comment by BigRoy** [comment]
> Proper handling of alpha channels on video codecs that FFmpeg support.

The prores file loads alpha correctly in latest beta indeed. ✅ 

---

> Python Editor fixes (hopefully, there are no more errors, but let me know if there are still things broken).

Doesn't work for me yet. Commented [here](https://github.com/ggarra13/mrv2/issues/138#issuecomment-1771755306).

---

> Python Classes now have keyword constructors besides the default one.

Not sure how these should work, but these all do not work for me:
```python
image.ImageFilters()
image.ImageFilters(minify=image.Nearest, magnify=image.Nearest)
image.ImageFilters(minify=image.ImageFilter.Nearest, magnify=image.ImageFilter.Nearest)
image.ImageFilters(image.Nearest, image.Nearest)
image.ImageFilters(image.ImageFilter.Nearest, image.ImageFilter.Nearest)
```

Getting errors like:
```
TypeError: __repr__(): incompatible function arguments. The following argument types are supported:
    1. (self: mrv2.image.Levels) -> str

Invoked with: <repr raised Error>

At:
  <string>(9): <module>
```

Best to continue that issue [here](https://github.com/ggarra13/mrv2/issues/140)
