### ISSUE TITLE
Settings: Change alpha checkerboard colors + size

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#144]
For me the transparency checkerboard pattern is quite large and has extreme contrast (pure black and white?) but I'd prefer the checkerboard smaller and having less contrast.

Would it be possible to expose settings for those colors and sizes?

E.g. here are some settings from Photoshop and a preview of what I believe is Photoshop's default checkboard pattern size + colors which I prefer much more than the pure black white.
![photoshop_transparency_grid_settings](https://github.com/ggarra13/mrv2/assets/2439881/39f96f9e-591d-4f95-bef0-cc3731d57489)

**Comment by ggarra13** [comment]
Check out v0.8.2 that adds a Background Panel.  Let me know what you think.
