### ISSUE TITLE
Incorrect display of Mrv2 is observed

### ISSUE THREAD

**Issue by theavege** [ggarra13/mrv2#148]
Hello.

Debian Stable, XFCE. Incorrect display of Mrv2 is observed
 
https://github.com/ggarra13/mrv2/assets/15143134/e8d63f66-c16c-4921-8d8d-04b4f546c351

Sincerely,
Artem

**Comment by ggarra13** [comment]
Try downloading v0.8.4 beta from:

https://sourceforge.net/projects/mrv2/files/beta/

and see if it fixes your problems.  If it does not, then I need some more info:

1) XFCE version
2) Are you running it under XWayland or X11/X.org?

**Comment by ggarra13** [comment]
I tried it both v0.8.3 and v0.8.4 beta under Ubuntu 22.04.3, and XFCE 4.16:

$ apt list xfce4-panel
xfce4-panel/jammy,now 4.16.3-1 amd64

and I could not reproduce your behavior.

**Comment by theavege** [comment]
![image](https://github.com/ggarra13/mrv2/assets/15143134/8b5a002c-f403-4dce-8f60-89b5498f0abf)

**Comment by theavege** [comment]
![image](https://github.com/ggarra13/mrv2/assets/15143134/fc6eb1a4-7250-4af5-84ec-e94b7c86d109)

![image](https://github.com/ggarra13/mrv2/assets/15143134/50e7219a-c2ca-40e9-9346-e3eab90f8df3)

**Comment by ggarra13** [comment]
What is your graphics card (model, version, drivers, etc)?

**Comment by theavege** [comment]
![image](https://github.com/ggarra13/mrv2/assets/15143134/0dad8b8d-cbe9-40cf-876a-3392258db321)

**Comment by ggarra13** [comment]
To rule out graphic cards issues (or to confirm them), did you try running mrv2 under a different Window manager like GNOME?

**Comment by ggarra13** [comment]
If you confirm it is a graphics card/driver issue, you could try switching from "modesetting" to the "intel" driver.

You can do this by creating a configuration file in the /etc/X11/xorg.conf.d/ directory. For example:

`
sudo nano /etc/X11/xorg.conf.d/20-intel.conf`

Add the following content:

```
Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
EndSection
```

Save the file and restart the X server:

`sudo service lightdm restart`

**Comment by theavege** [comment]
![image](https://github.com/ggarra13/mrv2/assets/15143134/0ba6d243-f900-48df-815c-4f512a8c84b8)

https://github.com/ggarra13/mrv2/assets/15143134/3928d1b6-0b32-40a7-943d-5aef816490a7

**Comment by ggarra13** [comment]
What am I looking at? Is any of those movies running under GNOME?  I checked with another user that also has an Intel card and he reports no errors, so I don't think it is a card or driver issue.  I believe this is a Window manager issue.

**Comment by theavege** [comment]
> What am I looking at?

I'm trying to show an incorrect display

> Is any of those movies running under GNOME?

I don't use GNOME. I'm using XFCE.

>I checked with another user that also has an Intel card and he reports no errors, so I don't think it is a card or driver issue.

Clear

>I believe this is a Window manager issue.

Thanks.

**Comment by ggarra13** [comment]
> > Is any of those movies running under GNOME?
> 
> I don't use GNOME. I'm using XFCE.

I understand you may not want to switch from XFCE, but I suggested you try it to see it if actually works.  In any case, I've run out of ideas for you to try, so you might want to check with the XFCE forums / developers.

**Comment by theavege** [comment]
Thank you. I understood you. I'll take your advice.
