### ISSUE TITLE
QoL enhancement suggestions

### ISSUE THREAD

**Issue by Tomycj** [ggarra13/mrv2#152]
Hi, I found this viewer when looking for lightweight and quick to open exr viewers. As a Blender user, it's much needed, especially since other alternatives don't support OCIO2 configs (forcing us to use configs from older versions), and AgX is now included in Blender 4.0.

These are some QoL suggestions:

1. Remember the selected OCIO Display/View after closing and reopening. This way the user doesn't have to re-select it each time the viewer is opened.

2. Remember the selected options from the menu bar. Particularly magnify and minify filters (in Render), Playback, and Timeline settings.

3. Image panning controls: maybe Ctrl+Click to pan the image.

4. Customizable mouse buttons. I didn't find a way to un-bind the play/pause with left mouse.

With a few more little improvements like these, I think this could become a very useful tool for Blender users. Thanks a lot!

**Comment by ggarra13** [comment]
> These are some QoL suggestions:
> 
> 1. Remember the selected OCIO Display/View after closing and reopening. This way the user doesn't have to re-select it each time the viewer is opened.

I have added a Preference Setting in Window->Preferences->OCIO Defaults->Display/View.

> 2. Remember the selected options from the menu bar. Particularly magnify and minify filters (in Render), Playback, and Timeline settings.

The magnify and minify settings can now be set in Preferences->User Interface->Render->Minify/magnify Filter.  Playback can be set to auto playback already in Preferences->Auto Playback.   Timeline controls can be set already in Preferences->Timeline.

> 3. Image panning controls: maybe Ctrl+Click to pan the image.

I have added Ctrl + Left Mouse Button drag to pan the image and the timeline viewport.

> 4. Customizable mouse buttons. I didn't find a way to un-bind the play/pause with left mouse.

This one will probably not be added, as there too many variables to check.

---------------------------------------------------------------------------------------------

You can check the changes in the new v0.9.1 beta (once it compiles overnight) at:

https://sourceforge.net/projects/mrv2/files/beta/

**Comment by Tomycj** [comment]
I already updated it and everything seems to be working fine. As a final suggestion, consider taking a look at the "branding": a fancy name, a fancy logo, file type icons, etc.

Thanks a lot!
