### ISSUE TITLE
[Bug] None English file path issue

### ISSUE THREAD

**Issue by xiaopeng12138** [ggarra13/mrv2#153]
When the file path contains Chinese character, mrv2 cant open the file via file association. See screenshot.
Drag and drop and open via File menu works.
![image](https://github.com/ggarra13/mrv2/assets/46627911/f14876fd-f867-497b-bfe1-802a2958565b)

**Comment by ggarra13** [comment]
Can you please upload a file with Chinese characters that does not work to some online service like mega.nz?  I don't know how to create one myself.

**Comment by xiaopeng12138** [comment]
[TestFolder.zip](https://github.com/ggarra13/mrv2/files/13401070/TestFolder.zip)

**Comment by ggarra13** [comment]
Try this version of v0.9.1 beta that works for me.  Make sure you check the file association points to this v0.9.1  (Check Help->About).

.exe:
https://mega.nz/file/DWgGFCLR#61uS3jnkFSYGBj4NLIc3XEDYvsEOvySdHyzDSMA7tc8

.zip:
https://mega.nz/file/ODZHQIrJ#OD7_N02detzkH089L36MmWXQbnh1WdocXablmPZKfi4

**Comment by xiaopeng12138** [comment]
> Try this version of v0.9.1 beta that works for me. Make sure you check the file association points to this v0.9.1 (Check Help->About).
> 
> .exe: https://mega.nz/file/DWgGFCLR#61uS3jnkFSYGBj4NLIc3XEDYvsEOvySdHyzDSMA7tc8
> 
> .zip: https://mega.nz/file/ODZHQIrJ#OD7_N02detzkH089L36MmWXQbnh1WdocXablmPZKfi4

It works now. Thank you!
