### ISSUE TITLE
FR: Save images to predefined folder

### ISSUE THREAD

**Issue by gerroon** [ggarra13/mrv2#167]
Hi

it would be great if one could just capture individual frames to a predefined folder like that can be done with VLC. It isa bit tedious to constantly enter individual file names for saving single frame.

**Comment by ggarra13** [comment]
I've added File->Save->Frames to Folder to v0.9.4 beta currently on sourceforge.net (https://sourceforge.net/projects/mrv2/files/beta/).  

The first time you call the function, it will ask you the parameters and the directory and name to save the file as usual.  However, the next times you invoke it, it will automatically save the image without popping any options or file name.

To change the file name or options that it is saving under, you should go to File->Save->Single Frame as usual and then go on to keep using File->Save->Frames to Folder.

**Comment by gerroon** [comment]
Thanks, it crashed when I did not provide a filename.

How do I set the frame number?

**Comment by gerroon** [comment]
I tdoes not work on Windows 11, as far as I can tell.  

Exr trows error

`ERROR: [save] D:/.TMP/test.0001.exr: Unsupported video`

**Comment by ggarra13** [comment]
> It does not work on Windows 11, as far as I can tell.
> 
> Exr trows error
> 
> `ERROR: [save] D:/.TMP/test.0001.exr: Unsupported video`

This is the error you get when you don't have Annotations on.  Movie files are encoded in YUV which EXRs do not support.  Turning off Annotations on makes the frame be captured in RGBA_F32 which is compatible with EXRs.

**Comment by ggarra13** [comment]
> Thanks, it crashed when I did not provide a file extension.

Thanks, I'll check that, as it is likely a bug.

**Comment by ggarra13** [comment]
> > Thanks, it crashed when I did not provide a file extension.
> 
> Thanks, I'll check that, as it is likely a bug.

I checked both File->Save->Single Frame and File->Save->Frames to Folder.  With either one when I save with no extension, I get the following error:

`ERROR: [cback] File extension cannot be empty.`

You will need to give me step by step instructions to reproduce it.

**Comment by ggarra13** [comment]
> Also it keeps opening the folder browser, then I am manually saving every time I pres "alt-s" which I set to be save single frame. I do not see it saving in hte background like VLC does.

You should not set the shortcut to "Save Single Frame" (which does exactly what it says it does), but to "Save Frames to Folder".

**Comment by gerroon** [comment]
> > Also it keeps opening the folder browser, then I am manually saving every time I pres "alt-s" which I set to be save single frame. I do not see it saving in hte background like VLC does.
> 
> You should not set the shortcut to "Save Single Frame" (which does exactly what it says it does), but to "Save Frames to Folder".

Thanks for the addition, that was it.
