### ISSUE TITLE
Missing dependency for building on Ubuntu

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#17]
I just built mrv2 myself (which is quite amazing considering I know nothing about coding ;) ).
I'm on Linux Mint 21.1 (i.e. basically a Ubuntu 22.04 under the hood) and after failing during the "./runme.sh" several times with all kinds of errors, I found out that all that was missing were the ALSA libraries.
Under RedHat they're installed under the name of "alsa-lib-devel", but under Ubuntu / Linux Mint they're missing.

`apt install libalsa-ocaml-dev`

helped me and the compile went smoothly. So maybe you should add this package to the dependencies.

Apart from that I'm kind of proud to be able to build Blender and mrv2 all by myself from now on. ✌🏻

**Comment by ggarra13** [comment]
Thank you for reporting that.  The actual libraries missing in the docs for Ubuntu are:

libasound2-dev
libpulse-dev
