### ISSUE TITLE
Jumping Versions with regex

### ISSUE THREAD

**Issue by jrsndl** [ggarra13/mrv2#170]
Can you please point me to documentation on ow to write regex for detecting versions?
It is great feature, but I can't make it to for for typical folder structrures like:

foo/shot_v001/shot_v001.1001.exr
foo/shot_v002/shot_v002.1001.exr
or 
bar/shot/v001/shot_v001.1001.exr
bar/shot/v002/shot_v002.1001.exr

Thank you

**Comment by ggarra13** [comment]
In principle, the default of _v should have worked for your first example (and I just checked it works me):

```
foo/shot_v001/shot_v001.1001.exr
foo/shot_v002/shot_v002.1001.exr
```

The actual regex that is created when you have "_v" is the following:
`
([\w:/]*?[/\._]_v)(\d+)([%\w\d\./]*)`

You need to make the regex match three groups: a prefix ([\w:/]*?[/\._]_v), the actual version (\d+) and the suffix ([%\w\d\./]*).

I think for your second example, the regex you may need might be:
 
`([\w:/]*?[/\._]v)(\d+)([%\w\d\./]*)`

**Comment by jrsndl** [comment]
> In principle, the default of _v should have worked for your first example (and I just checked it works me):

it doesn't work for me (Windows 10, UNC path)

> following: ([\w:/]*?[/\._]_v)(\d+)([%\w\d\./]*)
Not sure what regex flavor is used, but it looks like some slashes need to be escaped? When I use this regex, or _v, mrv2 doesn't even show top menu Image item.

When I add ```(.*_v)(\d+)([%\w\d\.\/]*)``` instead, I see this in the log:
![image](https://github.com/ggarra13/mrv2/assets/45896205/b20db62e-d95a-4032-afce-686fdfa5d896)

When I try simple ```(.*_v)(\d+)(.*)``` that should match the first occurence of the _v in the path foo/shot_v**001**/shot_v001.1001.exr, the log is the same.

Maybe the regex is not counting with backslashes on Windows?

**Comment by ggarra13** [comment]
Ah!  UNC paths... I hadn't considered that.  Can you post the full path as it is in Windows, then I'll build a regex for both "_v" and for other structures?
