### ISSUE TITLE
Maya USD plugin conflict

### ISSUE THREAD

**Issue by JordanV4** [ggarra13/mrv2#173]
I had the problem that the USD plugin was no longer loaded in Maya.

With the Autodesk support I found out that it seems to be due to the ENV variable PATH: C:\Program Files\mrv2 0.9.4\bin.
If the entry is deleted, the USD plugin can be loaded again.

Systhem Windows 11

**Comment by ggarra13** [comment]
Thanks for reporting that.  It is likely that Autodesk and mrv2 have conflicting versions of the same library, depending on what version of mrv2 and the maya plug-in you are using.  I am afraid I don't have an easy solution for that, as it is a limitation of how Windows works with PATHs, unlike Linux or macOS.  
The best way to work around it, if you are on Windows, is to NOT install mrv2 with setting the PATH variable and use Powershell, MSys64 or a .bat file to control the PATH variable instead depending on what application you are working with.  
On Msys64 you can create two bash scripts (one for maya and one for mrv2) and, if you prefer Powershell, use two .ps1 files.  .bat files are an inferior approach as they, AFAIK, always leave a console open.  I would suggest you check with ChatGPT to see what it suggests for you.
