### ISSUE TITLE
Does mrv2 support windows 7 ?

### ISSUE THREAD

**Issue by MMmaomao** [ggarra13/mrv2#174]
Hi, I tried mrv2 on windows 10 works well, but on another windows 7 machine is not work.
It pop up a window shows
![image](https://github.com/ggarra13/mrv2/assets/4596276/db22e244-1705-4a55-b8b5-9b5236c2bf92)

I tried this solution. copy `api-ms-win-core-path-l1-1-0.dll` and install the `VC_redist.x64.exe` but still not work. 
https://www.youtube.com/watch?v=TQ2XAmGDLmU&ab_channel=STSTutorial

**Comment by ggarra13** [comment]
mrv2 works only in Windows 8.1 or higher.  If you need a viewer that works on Windows 7, I believe both mrViewer, djv_view and DJV2 should work.

**Comment by MMmaomao** [comment]
I see, thanks
