### ISSUE TITLE
Unable to play av01 codec video

### ISSUE THREAD

**Issue by MMmaomao** [ggarra13/mrv2#175]
Hi, I play this video using potplayer works well, but using mrv2 would stop responding. 
https://github.com/ggarra13/mrv2/assets/4596276/cef06c18-767f-483c-ad28-e346fc459980

**Comment by ggarra13** [comment]
Thanks for providing a copyright free clip for testing.  The video you provided uses the libdav1d codec which currently mrv2 does not support.  The license is compatible with mrv2, but we would need to test and debug that it works fine on each platform which takes some time.
Currently, you can convert the clip into a format that mrv2 will read with the ffmpeg utilities, which run command-line (I think there are freely avaiable GUIs two for those that don't like typing).
The simplest way command-line to convert it is:
    ffmpeg -i youcat.mp4 mrv2_cats.mp4

**Comment by MMmaomao** [comment]
Thanks.

**Comment by ggarra13** [comment]
The latest beta at sourceforge:

https://sourceforge.net/projects/mrv2/files/beta/

supports the AV1 codec for both decoding and encoding.
It also adds encoding of VP9 videos.

**Comment by ggarra13** [comment]
Now supported in v1.0.4
