### ISSUE TITLE
"Save Movie Error - Invalid Argument" (+Compiling MRV2 in Windows)

### ISSUE THREAD

**Issue by Olympusmonsgames** [ggarra13/mrv2#183]
Here's what I get in the output log when attempting to save a movie of a 16-bit EXR image sequence (Windows 10 | mrv2 v1.0.5 pre-compiled installer):
```
[save] Image info: 2048x858 RGBA_F16
[save] Output info: 2048x858 RGB_U8
ERROR: [save] E:/MyVideoFile.mp4: avcodec_open2 - Invalid argument
```
Am I just missing something here? Saving/Exporting movies isn't covered anywhere in the documentation. I have FFMPEG (full) installed at `C:\FFMPEG\`, but mrv2 seems to be using it's own ffmpeg libraries as updating FFMPEG today didn't make any difference here.

The ProRes profiles seem to work fine, as does choosing `None` for profile, but `None` gives me an **H.263** video, which isn't supported as embeddable on most comms platforms (Slack, Discord etc). As ProRes *also* isn't an embeddable codec on these platforms, I currently have no way to use mrv2 to process render dailies (which I would **love** to be able to do instead of using Adobe Media Encoder.

Side Note: Where are the FFMPEG profiles saved? Can I edit/add to that list myself using the pre-compiled install of mrv2 or do I need to build from src?

**Comment by ggarra13** [comment]
> Am I just missing something here? Saving/Exporting movies isn't covered anywhere in the documentation.

Sadly, you are not missing anything.  I'll make sure to add a section to the documentation.

> The ProRes profiles seem to work fine, as does choosing `None` for profile

The H264 codec is, unfortunately, only supported if you build mrv2 as GPL, as, otherwise, it requires a license from VideoLan.  mrv2 is, by default, a BSD application, not a GPL one.  If you want to build your own version of mrv2 as GPL, look for how to do it in the main page of https://github.com/ggarra13/mrv2.

> Side Note: Where are the FFMPEG profiles saved? Can I edit/add to that list myself using the pre-compiled install of mrv2 or do I need to build from src?

They are stored in the mrv2 and tlRender source code.  You cannot edit them easily.

**Comment by Olympusmonsgames** [comment]
It's a bit unclear to me how to compile mrv2 on Windows. I've modified the `vcvars_win64.bat` file calls with my VS Community (2022) and msys2 dirs. I don't need to set an explicit Win SDK version, I already have a few SDK versions installed as VS components.

Do I run the bat file? Or the runme.sh file (if so, do I run that in msys2)?
I like the idea of compiling the NSIS installer, as I'd like to distribute the build to multiple of my machines.

Sorry if these are newbie questions, I have experience compiling C++ & Python, but no experience packaging windows applications.

Thanks!

**Comment by ggarra13** [comment]
> It's a bit unclear to me how to compile mrv2 on Windows.

I'll try to make the instructions clearer.

> 
> Do I run the bat file? Or the runme.sh file (if so, do I run that in msys2)? I like the idea of compiling the NSIS installer, as I'd like to distribute the build to multiple of my machines. How do I incorporate that into the build? I've already downloaded fresh copies of msys2, NSIS, and CMake

First, you need to run the .bat file from its installed location (or make it as I do a shortcut in the Desktop).  The .bat file should open a new MSYS2 terminal after saying a quick welcome message from the MSVC compiler.
From the MSYS2 terminal it opens, you can verify that you can see the MSVC compiler if you do:

msys2$ which cl.exe
/C/Program Files/MSVC2019/etc.../bin/cl.exe

If you cannot see the compiler, you modified the .bat file incorrectly (check the paths to it).

If you can see it, then you can proceed to:

$ cd /root/dir/of/mrv2
$ ./runme.sh -gpl   # -gpl to have it compile with H264 of FFmpeg.

That should compile mrv2 with its default settings (it will print out the number of CPUs 
 and the CMake version).  If you have a modern machine with 16 cores, it should take about 30 mins for the compilation to finish.

Assuming the compilation works, it will place the mrv2.exe in:

/root/dir/of/mrv2/BUILD-Msys-amd64/Release/install/bin/mrv2.exe

If the compilation fails, you can always check the log to see what went wrong at:

/root/dir/of/mrv2/BUILD-Msys-amd64/Release/compile.log

Look for "FAILED:", "Error:", "CMake Error", etc.

If something went wrong, you can try compiling with one CPU core to make the compiled messages clearer like:

./runme.sh -j 1

Anyway, that should get you started.  If you run into issues, feel free to ask again here.

> 
> Sorry if these are newbie questions, I have experience compiling/debugging C++ & Python scripts, but no experience packaging windows applications/installers.

Never mind the newbie questions.  We've all had them.

**Comment by slavkosky** [comment]
Great, much appreciated! I stopped using VS2019 last year, so I had to modify my 2022 install by adding the `MVSC v142 Build Tools x86/64` components. That didn't work, I got a few unresolved external symbol errors when building `liblcms2.lib` and `raw.dll`. 

So next I tried this:
- Reinstalled VS Community 2019 (with MSVC and v142 build tools components)
- Set the `vcvarsall.bat` path to the newly-installed VS 2019 `vcvarsall.bat` path
- Deleted the entire `BUILD-Msys-amd64` folder
- Re-ran the `.bat` file in `Windows` folder

I still got unresolved symbols errors in the same stage of the compile (attached my latest `compile.log`) the errors start on **Line 14128**

**Comment by ggarra13** [comment]
Ok.  Your problem is that you have gcc installed in your path, which you should not install as liblcms2 needs to be compiled with cl.exe, not gcc.  Let me know if this was installed by default so I add that to the instructions or scrtips.

Try:

$ pacman -R gcc
$ cd /root/dir/of/mrv2
$ ./runme.sh

**Comment by ggarra13** [comment]
Regarding ninja reporting no errors, that's because ninja runs multiple threads so some threads may exit with no errors but if at least one exits with errors the whole compilation stops.  Sadly the messages get buried in the log.

**Comment by slavkosky** [comment]
Gotcha, no worries on that. And thanks for the insight, ill remove gcc and try again. I cant remember if i installed it at some point, I've been using the same OS install for years so its entirely possible. 

Maybe just add a line in your instructions to make people aware that gcc is the culprit if they get that error in the future. Ill let you know how the compile goes!

**Comment by ggarra13** [comment]
> Gotcha, no worries on that. And thanks for the insight, ill remove gcc and try again. I cant remember if i installed it at some point, I've been using the same OS install for years so its entirely possible.

You can also modify the compile_liblcms2_windows.sh script to:

```
export CC=cl.exe  # Added
./configure --enable-shared --disable-static ....etc....
```

**Comment by slavkosky** [comment]
Running `pacman -R gcc` in MSYS2 = `error: target not found: gcc` I'm checking my VS install to see if it crept into one of my component bundles I selected when installing

**Comment by ggarra13** [comment]
Try:

`which gcc`

to see if it is installed indeed.

Anyway, I recommend you use the export CC=cl.exe change in compile_liblcms2_windows.sh as it is more solid.

**Comment by slavkosky** [comment]
Ah, found it. I had installed Strawberry Perl env last year, it added gcc.exe to my path. I'll try again with this change, but could you elaborate on the mod to `compile_liblcms2_windows.sh`? I looked at it 
```sh
#!/usr/bin/env bash
# SPDX-License-Identifier: BSD-3-Clause
# mrv2
# Copyright Contributors to the mrv2 Project. All rights reserved.

#
# This script compiles a LCMS2 as a shared library (DLL).
#
if [[ ! -e etc/build_dir.sh ]]; then
    echo "You must run this script from the root of mrv2 directory like:"
    echo
    script=`basename $0`
    echo "> bin/$script"
    exit 1
fi

if [[ ! $RUNME ]]; then
    . etc/build_dir.sh
else
    . etc/functions.sh
fi

#
# Set the main tag to compile
#
LCMS_BRANCH=lcms2.15

if [[ $KERNEL != *Msys* ]]; then
    echo
    echo "This script is for Windows MSys2-64 only."
    echo
    exit 1
fi

MRV2_ROOT=$PWD
SUPERBUILD=$PWD/$BUILD_DIR/tlRender/etc/SuperBuild
INSTALLDIR=$PWD/$BUILD_DIR/install

if [[ ! -e $INSTALLDIR/lib/liblcms2.lib ]]; then

    #
    # Install development tools
    #
    pacman -Sy --noconfirm
    # pacman -Sy mingw-w64-x86_64-toolchain --noconfirm
    
    #
    # Clone the repository
    #
    mkdir -p $SUPERBUILD
    cd $SUPERBUILD
    if [[ ! -d LCMS2 ]]; then
	run_cmd git clone --depth 1 --branch $LCMS_BRANCH https://github.com/mm2/Little-CMS.git LCMS2 2> /dev/null
    fi
    
    #
    # Run configure
    #
    cd LCMS2
    run_cmd ./configure --enable-shared --disable-static --prefix=$INSTALLDIR
    
    #
    # Compile and install the library
    #
    make -j ${CPU_CORES} install

    run_cmd mv $INSTALLDIR/lib/liblcms2.a $INSTALLDIR/lib/liblcms2.lib
    
    cd $MRV2_ROOT
else
    echo "liblcms2 already installed."
fi
```
Where do I put those two lines you mentioned?

**Comment by ggarra13** [comment]
```shell
 
     #
     # Run configure
     #
     export CC=cl.exe   # Add this.  It will still choke if you have gcc or g++ on your path thou.
     cd LCMS2
     run_cmd ./configure --enable-shared --disable-static --prefix=$INSTALLDIR
 ```

**Comment by slavkosky** [comment]
Thanks. After Strawberry Perl uninstall and removing path entries `which gcc` now spits out `no gcc in (<a bunch of compiler dirs>)`. I've also added `export CC=cl.exe` at line 59. Time for another go :)

**Comment by slavkosky** [comment]
Ran it again, and the output when building `lcms2` is stating:
```console
> git clone --depth 1 --branch lcms2.15 https://github.com/mm2/Little-CMS.git LCMS2

> ./configure --enable-shared --disable-static --prefix=/C/mrv2/BUILD-Msys-amd64/Release/install
configure: loading site script /etc/config.site
checking build system type... x86_64-pc-msys
checking host system type... x86_64-pc-msys
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '197609' is supported by ustar format... yes
checking whether GID '197121' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports the include directive... yes (GNU style)
checking for gcc... cl.exe
checking whether the C compiler works... yes
checking for C compiler default output file name... conftest.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... obj
checking whether we are using the GNU C compiler... no
checking whether cl.exe accepts -g... yes
checking for cl.exe option to accept ISO C89... none needed
checking whether cl.exe understands -c and -o together... no
checking dependency style of /C/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/LCMS2/compile cl.exe... msvc7
checking for /C/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/LCMS2/compile cl.exe option to accept ISO C99... unsupported
checking for /C/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/LCMS2/compile cl.exe option to accept ISO C89... (cached) none needed
checking for /C/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/LCMS2/compile cl.exe option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... /C/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/LCMS2/compile cl.exe -E
checking for g++... no
checking for c++... no
checking for gpp... no
checking for aCC... no
checking for CC... no
checking for cxx... no
checking for cc++... no
checking for cl.exe... cl.exe
checking whether we are using the GNU C++ compiler... no
checking whether cl.exe accepts -g... yes
checking dependency style of cl.exe... msvc7
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for non-GNU ld... no
configure: error: no acceptable ld found in $PATH

real	0m12.370s
user	0m0.075s
sys	0m0.212s

make: Nothing to be done for 'install'.
> mv /C/mrv2/BUILD-Msys-amd64/Release/install/lib/liblcms2.a /C/mrv2/BUILD-Msys-amd64/Release/install/lib/liblcms2.lib
mv: cannot stat '/C/mrv2/BUILD-Msys-amd64/Release/install/lib/liblcms2.a': No such file or directory
:: Synchronizing package databases...
``` 

Here's the entire log:
**[compile.log](https://github.com/ggarra13/mrv2/files/14216878/compile.log)**

**Comment by ggarra13** [comment]
Okay.  Now you are missing /usr/bin/ld which comes from:
`
pacman -Sy binutils --noconfim`

It was missing in the script.  Good catch!

**Comment by ggarra13** [comment]
I have re-worked the ffmpeg and lcms2 compile scripts in the repository and I also added support for VP9 encoding and AV1 decoding and encoding, which are supported by Discord and are free of patents and license issues (and offer better quality than H264 on top).

```
cd /dir/of/mrv2/
git switch main
git pull
./runme.sh -gpl
```

**Comment by slavkosky** [comment]
I have an RTX 4090 with AV1 encoder, so that's great news! I'll pull those changes now and attempt again. Thanks for you're amazing work!

**Comment by ggarra13** [comment]
Make sure to check the new build requirements, as you now need to install "meson" too on Windows (ie. the meson .msi installer) for the dav1d (AV1 decoder).
Also, the AV1 encoder currently works in software only, so it is still somewhat slower than H264.
I *will* be adding hardware encoding at some point, but the build scripts are hard to deal with as you need CUDA installled, which cannot be automated as you need to sign the NVidia EULA.

**Comment by slavkosky** [comment]
Software encoding will be fine. AV1 is so much better than h264 so it's worth the extra bit of encode time regardless

**Comment by Olympusmonsgames** [comment]
Hey, just wanted to follow up:

- **I was able to package an installer using NSIS on the first try.** Great!
- Now installed, I'm getting some strange python-related errors in the log **immediately upon opening mrv2**
  - This error occurs both when opening mrv2 directly and when opening an image sequence
```
ERROR: [python] AssertionError: SRE module mismatch At:
  C:\Program Files\mrv2\bin\lib\re\_compiler.py(18): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap>(1079): _handle_fromlist
  C:\Program Files\mrv2\bin\lib\re\__init__.py(125): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  C:\Program Files\mrv2\bin\lib\platform.py(117): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  C:\Program Files/mrv2/python/plug-ins\update-mrv2.py(11): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
```


Also I noticed an issue with video export:
- While I am able to export with the GPL profiles, I've noticed that the frame rate of the exported video isn't being set correctly sometimes.
  - FFMPEG seems to be getting the fps from the session default frame rate (in preferences) instead of the timeline frame rate override in the bottom toolbar in the viewer.
  - Once you change the default fps in settings, and export again, fps will still be the value before the setting change
  - However restarting mrv2 after changing default fps will give you the right fps on export.

Are you setting the ffmpeg command args using the profile configs? If so, where do those live? Just curious if I can make my own export profiles for mrv. I do a lot of voxel-based fluid sims at uncommon timesteps. I export frame sequences frequently (~dozen times per day or so) and play around with playback fps to see what speed looks best, compare my results to reference video, etc. I've been trying to cut Adobe Media Encoder out of my workflow because I already use mrv2 for previewing sequences and the extra time adds up.

**Comment by ggarra13** [comment]
> * **I was able to package an installer using NSIS on the first try.** Great!

Most excellent!!! 👍 

> * Now installed, I'm getting some strange python-related errors in the log **immediately upon opening mrv2**
>   

These type of errors usually means that when compiling (or installing) python there was a mismatch between the libraries and the main python executable versions (the embedded mrv2.exe in our case).  Usually, the culprit is PYTHONPATH at either compile or run time.  I am now recompiling all of mrv2 and installing it myself to see if I also get the errorrs.

You might want to check the compile.log to see when Python gets compiled to see if there are any errors then too.

> Also I noticed an issue with video export:
> 
> * While I am able to export with the GPL profiles, I've noticed that the frame rate of the exported video isn't being set correctly sometimes.
>   
>   * FFMPEG seems to be getting the fps from the session default frame rate (in preferences) instead of the timeline frame rate override in the bottom toolbar in the viewer.
>   * Once you change the default fps in settings, and export again, fps will still be the value before the setting change
>   * However restarting mrv2 after changing default fps will give you the right fps on export.

Ok.  You almost got it right.  

The FPS is stored with the clip once loaded.  

If loading a movie, the FPS is taken from the movie file.  If loading a sequence the FPS is taken from the Preferences upon load time and stored with it.  

When you go to save the clip, the FPS is taken from the stored location with the clip.

You should be able to avoid having to restart mrv2 if you go to Preferences, change the Sequence FPS there, and then reload the sequence (or RMB->File->Clone in the Files Panel).

**Comment by ggarra13** [comment]
> Are you setting the ffmpeg command args using the profile configs? If so, where do those live?

No.  The ffmpeg executable is not bundled with mrv2.  The profile settings for exporting (ie. bitrate, etc) are in C++ code in my own version of the tlRender gitmodule (ie. github.com:ggarra13/tlRender)

**Comment by ggarra13** [comment]
> You might want to check the compile.log to see when Python gets compiled to see if there are any errors then too.

I removed some errors (warnings really) from the Windows compilation of Python.  I don't think that was what caused your build to fail with Python errors, but just in case do:

```
git pull
runme.sh
```

In any case, do you have another Python version installed on your machine that may be conflicting with version 3.10 that mrv2 compiles?  I may want to mimic your setup and see if I can get my build to fail too.

**Comment by Olympusmonsgames** [comment]
>  Usually, the culprit is PYTHONPATH or PATH at either compile or run time. I am now recompiling all of mrv2 and installing it myself to see if I also get the errors.
>
>You might want to check the compile.log to see when Python gets compiled to see if there are any errors then too.

I checked `compile.log` and didn't find any errors except the `Python Logging "Module Detached"` errors I'd been seeing before, as well as a warning about pip needing an update for 3.10.  However your bit about PATH conflicts tipped me off. I had other installs of Python (both `3.12` and `3.10`) installed on my system (and both were added to my system PATH. I removed `3.12` completely from the system, and manually upgraded `pip` in my 3.10 install. I'll try and compile again with your latest git commits and report back 👍

**Comment by Olympusmonsgames** [comment]
> The FPS is stored with the clip once loaded.
>
> If loading a movie, the FPS is taken from the movie file. If loading a sequence the FPS is taken from the Preferences upon load time and stored with it.
>
> When you go to save the clip, the FPS is taken from the stored location with the clip.
>
> You should be able to avoid having to restart mrv2 if you go to Preferences, change the Sequence FPS there, and then reload the sequence (or RMB->File->Clone in the Files Panel).

I see, yeah I'd deduced that from trial and error (and by experimenting editing a session file I'd saved). This workflow will be fine now that I have confirmation of how to change export fps properly, _but_ I also can't help but wish there were a way to override FPS (and some other FFMPEG params like bitrate target, resolution, etc.) _right in the export dialog_. Either way, I'm just glad I can use mrv2 for exporting video now!

**Comment by Olympusmonsgames** [comment]
Ok, got a new set of errors I haven't seen before (starting ~Line 94 of `compile.log`:
```console
:: Synchronizing package databases...
 clangarm64 downloading...
 mingw32 downloading...
 mingw64 downloading...
 ucrt64 downloading...
 clang32 downloading...
 clang64 downloading...
 msys downloading...
error: failed retrieving file 'ucrt64.db' from mirror.msys2.org : SSL connection timeout
error: failed retrieving file 'clang32.db' from mirror.msys2.org : SSL connection timeout
error: failed retrieving file 'clang64.db' from mirror.msys2.org : SSL connection timeout
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'msys.db' from mirror.msys2.org : SSL connection timeout
resolving dependencies...
looking for conflicting packages...
```
Also got two errors late in the build (~Lines 17702 and 17777 respectively)having to do with `exceptions.py`:
```console
byte-compiling build\bdist.win-amd64\egg\fltk14\test\exceptions.py to exceptions.cpython-310.pyc
Sorry: IndentationError: unexpected indent (exceptions.py, line 47)
...
Extracting pyFltk1.4-1.4.0rc1-py3.10-win-amd64.egg to c:\mrv2\build-msys-amd64\release\install\bin\lib\site-packages
Sorry: IndentationError: unexpected indent (exceptions.py, line 47)
Adding pyFltk1.4 1.4.0rc1 to easy-install.pth file
```

**Comment by ggarra13** [comment]
The msys2 errores are network errors.  You might need to start the build
with runme.sh again if you get them if some Msys package does not sync.

The byte compiling error is a typo the pyFLTK guys missed.  You can ignore
it.

**Comment by ggarra13** [comment]
> **EDIT:** I checked `BUILD-Msys-amd64\Release\install\bin` and it did seem to build `mrv2.exe` properly. I opened it, and there aren't any python errors in the console on startup anymore. Lower-left corner of mrv2 window states `Everything OK.` For now, I'm going to package this up.

Yes, the warnings you are getting are normal.  Most libraries used in ffmpeg are unix libraries and when built with the MSVC compiler they throw fits.

**Comment by ggarra13** [comment]
I am now trying to modify the build so that if you have other instances of Python installed they don't conflict.  I found out the environment variables set in System->Environment Variables were getting used (like python.exe), instead of the files in BUILD-MSys-amd64/Release/install/bin.

**Comment by ggarra13** [comment]
You should now be able to install any python version and it should not interfere with the build process.  If you can do a test with another python version, I'd be much obliged.  Do:

<install python3.11 for example>

```
cd mrv2
git switch main
git pull
./runme.sh

```

**Comment by ggarra13** [comment]
I have added the option to save movie files with the speed set in the playback toolbar.   You can save movie files from sequences or without sound at a different rate.  If you try to save a movie file with sound, the speed in the toolbar is disregarded (we cannot do resampling while saving the movie file).

```
cd /dir/of/mrv2/
git switch main
git pull
./runme.sh -gpl
```

If you kept the directory of your latest compile, you can do to compile quicky:

```
cd /dir/of/mrv2/
git switch main
git pull
./runmet.sh
```

**Comment by ggarra13** [comment]
> Side Note: Where are the FFMPEG profiles saved? Can I edit/add to that list myself using the pre-compiled install of mrv2 or do I need to build from src?

I have added FFmpeg presets to mrv2 v1.0.5 (currently in beta).  The current beta lives in [www.sourceforge.net/projecs/mrv2/files/beta.](https://sourceforge.net/projects/mrv2/files/beta/)

You can either donwload it to try it, or compile it again yourself with:

```
cd mrv2_dir
git switch main
git pull
./runme.sh
```

I also improved the performance of compiling and removed the potential for network errors when updating Msys64 (it is now updated only once).

**Comment by Olympusmonsgames** [comment]
Hey! I just pulled from git and tried a compile again, got this error when FFMPEG compilation started:
```console
Compiling FFmpeg as GPL......

> rm -rf /c/mrv2/BUILD-Msys-amd64/Release/tlRender/etc/SuperBuild/FFmpeg/build/ffmpeg
ERROR: OpenSSL >=3.0.0 requires --enable-version3
```
[compile.log](https://github.com/ggarra13/mrv2/files/14321214/compile.log)

**Comment by ggarra13** [comment]
Oh.  Msys64 updated its openssl library.  Try:

```
cd mrv2_dir
git switch main
git pull
./runme.sh -gpl
```
