### ISSUE TITLE
Save 'Single Frame' dialog - `OpenEXR` support

### ISSUE THREAD

**Issue by p2or** [ggarra13/mrv2#185]
Hi @ggarra13,

nothing urgent, but I thought it's worth a report: When I try to save the current frame using the 'Single Frame' option, I always get the `OpenEXR` dialog afterwards, _regardless of the file format_ I typed before. And more importantly, I get the following error message when saving the frame as `OpenEXR`: `ERROR: [save] /Users/p2or/Desktop/test.exr: Unsupported video` - Is this a bug or is it simply not supported?

<img width="530" alt="Screenshot 2024-01-31 at 20 14 58" src="https://github.com/ggarra13/mrv2/assets/512368/9e0060d8-9e5b-41ee-9853-0de105bee2f5">

----

MacOS 14.3, mrv2 64 bits - v1.0.2 - Built Jan 23 2024 03:36:21

Cheers,
Christian

**Comment by ggarra13** [comment]
The dialog is normal.  It appears for any format, but it should remain ghosted for any format that is not .exr.

The "unsupported video" is likely you trying to save a movie file as an EXR or some other RGB/A format.  The movies are in YUV space that's why it reports unsupported video format.  You can work around it if you select Show Annotations which will, besides saving annotations, capture each frame as RGBA and save it as such.

If that does not solve your issues, let me know.

**Comment by p2or** [comment]
Hi @ggarra13,

thanks for your feedback.

> The dialog is normal. It appears for any format, but it should remain ghosted for any format that is not .exr.

Yep, the OpenEXR options are greyed-out for all formats I tested. I'd expect some format related settings like in version 1 though - feel free to ignore.

> The "unsupported video" is likely you trying to save a movie file as an EXR or some other RGB/A format.

Unfortunately, I get this error message when I try to save a single frame to EXR, although all other formats seem to work.

Cheers,
Christian

**Comment by ggarra13** [comment]
Find a fix in the beta directory of sourceforge at (without NDI or pyFLTK support):

https://sourceforge.net/projects/mrv2/files/beta/

There's also a beta for M1 machines (Darwin-arm64) which I would like you to test if you can and report if it is faster than the Intel version (Darwin-amd64).

**Comment by p2or** [comment]
Hi @ggarra13,

thanks. I've just installed `mrv2-beta-Darwin-amd64.dmg`. When I try to save a single image as EXR, mrv2 unfortunately crashes immediately.

> There's also a beta for M1 machines (Darwin-arm64) which I would like you to test if you can and report if it is faster than the Intel version (Darwin-amd64).

I am happy to help. Is there anything I should look out for? In general, it feels a little faster. I've also tried to save a single frame to EXR:

![test-darwinArm](https://github.com/ggarra13/mrv2/assets/512368/e6c9d311-76a1-478e-97a0-1eb8322fb5e2)

Does this help?

Cheers,
Christian

**Comment by ggarra13** [comment]
Find a new version of beta v1.0.3 (amd64 - NOT M1) that seems to work for me at:

 https://mega.nz/file/fb4wCA5K#axgZ7BhrqK691aSMnL9wE5sggc9Iy2GP418oK08JVW4

I'll have a new ARM64 (ie M1) version compiled tomorrow (or sooner) if all goes well.  For the M1 version, I am curious to see if the speed improvement is worth it.  I would heavy test it with 4K images and movies and with 8K ones if you have them.  I don't have an M1 machine myself to put it through its paces.

**Comment by ggarra13** [comment]
Find the M1 (arm64) version without NDI support at:

https://sourceforge.net/projects/mrv2/files/beta/

It should also fix the EXR saving.

**Comment by ggarra13** [comment]
v1.0.3 has been released with the fixes on both AMD64 and ARM64.

**Comment by p2or** [comment]
Hi @ggarra13,

as of version `1.0.3`, saving the frame in `OpenEXR` works as expected. Great, many thanks for your quick fix.

Re ARM performance: I have tested a 4k image sequence (`OpenEXR`) as well as regular 4k-Clips (`.mp4`) and there is no noticeable difference between the Arm64 and Amd64 version - both are a little jerky.

Does this help?

Cheers,
Christian

**Comment by ggarra13** [comment]
> 
> Re ARM performance: I have tested a 4k image sequence (`OpenEXR`) as well as regular 4k-Clips (`.mp4`) and there is no noticeable difference between the Arm64 and Amd64 version - both are a little jerky.
> 
> Does this help?

Yes, that helps.
