### ISSUE TITLE
Loading sequence from 900 beyond 1000 frames issue

### ISSUE THREAD

**Issue by mzigaib** [ggarra13/mrv2#191]
Any image sequence that I try to load that starts before 1000 and goes beyond never loads the entire sequence it just stops on 999.

I am using Fedora 39 and MRV2 1.0.5

**Comment by ggarra13** [comment]
I cannot reproduce it.  How are the frames named? Padding? No padding?

I tried:

nopad.1000.exr	nopad.999.exr  pad.0999.exr
nopad.1.exr	pad.0001.exr   pad.1000.exr

mrv2 nopad.1.exr
mrv2 pad.0001.exr

Both loaded fine in mrv2-v1.0.5 release Linux.

**Comment by mzigaib** [comment]
Hi thanks for the feedback!
I can show you the entire paths for the ones that I tried

/media/roofstudio/projects/macallan/users/Michel/Studies/Houdini/flipbook/RND_paper_growth_ripples_no_noise_RND_paper_growth_v09_v09/RND_paper_growth_ripples_no_noise_RND_paper_growth_v09_v09.0980.jpg (980-1100)

/media/roofstudio/projects/macallan/users/Michel/Studies/Houdini/flipbook/RND_paper_growth_RND_paper_growth_v07_wave_effect_01_v07/RND_paper_growth_RND_paper_growth_v07_wave_effect_01_v07.0980.jpg (980-1100)

And so on, any that I tried to load got stuck on 0999 and does not load further.

**Comment by mzigaib** [comment]
Wait I will get back to you

**Comment by mzigaib** [comment]
Here is one that in Houdini mplayer it loads normally were in MRV2 I am having the issue.
The complete path:
/media/roofstudio/projects/macallan/users/Michel/Studies/Houdini/flipbook/RND_paper_growth_RND_paper_growth_v07_1_wave/RND_paper_growth_RND_paper_growth_v07_wave_effect.0980.jpg

Which I renamed.

And the screenshots shows what happens

![Screenshot from 2024-02-23 11-58-56](https://github.com/ggarra13/mrv2/assets/10547601/41f427ef-4af6-42d2-adbd-2f223a3be41d)

![Screenshot from 2024-02-23 11-59-24](https://github.com/ggarra13/mrv2/assets/10547601/f2d87924-e596-4d87-8223-dcf22dc9e1ad)

**Comment by ggarra13** [comment]
I still cannot reproduce it.  Here's a screenshot with the paths made to be like yours (see the path and the start/end frames.  I also tried .jpegs):

![Sequence](https://github.com/ggarra13/mrv2/assets/6072843/d46caee9-f591-493c-ba7c-894f11e5b55a)

Can you:

1) Send out the version information as seen in the About window (ie. compile date, etc).
2) Start it command-line with:

mrv2 -log <fullpath/to/first/image.jpg> &> loading.log

3) Attach the loading.log file that is created in 2) in your comment.

**Comment by mzigaib** [comment]
I am trying to send all the info I have.
I tried this on command line and this is the result:

/opt/mrvr2/bin/mrv2.sh /media/roofstudio/projects/macallan/users/Michel/Studies/Houdini/flipbook/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg 
       [app] mrv2 v1.0.5 - Built Feb 17 2024 04:51:55
       [app] Set Language to en_US.UTF-8, Numbers to C
       [prefs] Reading preferences from "/home/mzigaib/.filmaura/mrv2.prefs".
       [prefs] Loaded color themes from "/usr/local/mrv2-v1.0.5-Linux-64/colors/mrv2.colors".
       [ocio] Setting OCIO config from preferences.
       [prefs] Path mappings have been loaded from "/home/mzigaib/.filmaura/mrv2.paths.prefs".
       [prefs] Loading hotkeys from "/home/mzigaib/.filmaura/mrv2.keys.prefs".
       [ocio] OCIO config is now:
       [ocio] /home/mzigaib/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio

**Comment by mzigaib** [comment]
Now I move it to my Downloads directory

/opt/mrvr2/bin/mrv2.sh /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg 
       [app] mrv2 v1.0.5 - Built Feb 17 2024 04:51:55
       [app] Set Language to en_US.UTF-8, Numbers to C
       [prefs] Reading preferences from "/home/mzigaib/.filmaura/mrv2.prefs".
       [prefs] Loaded color themes from "/usr/local/mrv2-v1.0.5-Linux-64/colors/mrv2.colors".
       [ocio] Setting OCIO config from preferences.
       [prefs] Path mappings have been loaded from "/home/mzigaib/.filmaura/mrv2.paths.prefs".
       [prefs] Loading hotkeys from "/home/mzigaib/.filmaura/mrv2.keys.prefs".
       [ocio] OCIO config is now:
       [ocio] /home/mzigaib/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio

The same problem occours

**Comment by ggarra13** [comment]
You are missing the -log flag.

`/opt/mrvr2/bin/mrv2.sh -log /media/roofstudio/projects/macallan/users/Michel/Studies/Houdini/flipbook/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg`

**Comment by mzigaib** [comment]
Sorry, here we go:

/opt/mrvr2/bin/mrv2.sh -log /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg 
       [app] mrv2 v1.0.5 - Built Feb 17 2024 04:51:55
       [app] Set Language to en_US.UTF-8, Numbers to C
       [prefs] Reading preferences from "/home/mzigaib/.filmaura/mrv2.prefs".
       [prefs] Loaded color themes from "/usr/local/mrv2-v1.0.5-Linux-64/colors/mrv2.colors".
[LOG] 0.00 tl::system::Context: 
    System: Linux 6.7.5-200.fc39.x86_64 x86_64
    Cores:  32
    RAM:    126GB
[LOG] 0.00 tl::time::TimerSystem: Create
[LOG] 0.00 tl::image::FontSystem: Create
[LOG] 0.00 tl::audio::System: Create
[LOG] 0.00 tl::audio::System: RtAudio version: 5.1.0
[LOG] 0.00 tl::audio::System: Audio API: Pulse
[LOG] 0.00 tl::audio::System: Audio API: ALSA
[LOG] 0.00 tl::audio::System: 
    Device 0: PCM2902 Audio Codec
        Channels: 0 output, 1 input, 0 duplex
        Sample rates: 8000 16000 22050 32000 44100 48000 96000 192000 
        Preferred sample rate: 48000
        Native formats: S16 S24 S32 F32 
    Device 1: Starship/Matisse HD Audio Controller
        Channels: 2 output, 2 input, 0 duplex
        Sample rates: 8000 16000 22050 32000 44100 48000 96000 192000 
        Preferred sample rate: 48000
        Native formats: S16 S24 S32 F32 
    Device 2: Easy Effects Sink
        Channels: 2 output, 2 input, 0 duplex
        Sample rates: 8000 16000 22050 32000 44100 48000 96000 192000 
        Preferred sample rate: 48000
        Native formats: S16 S24 S32 F32 
    Device 3: GA104 High Definition Audio Controller
        Channels: 2 output, 2 input, 0 duplex
        Sample rates: 8000 16000 22050 32000 44100 48000 96000 192000 
        Preferred sample rate: 48000
        Native formats: S16 S24 S32 F32 
    Device 4: Easy Effects Source
        Channels: 0 output, 2 input, 0 duplex
        Sample rates: 8000 16000 22050 32000 44100 48000 96000 192000 
        Preferred sample rate: 48000
        Native formats: S16 S24 S32 F32 
    Default input device: 0
    Default input info: 1 F32 48000
    Default output device: 1
    Default output info: 2 F32 48000
[LOG] 0.00 tl::gl::GLFWSystem: Create
[LOG] 0.00 tl::gl::GLFWSystem: GLFW version: 3.4.0
[LOG] 0.01 tl::io::System: Create
[LOG] 0.01 tl::io::ffmpeg::Plugin: Codecs: a64multi, a64multi5, alias_pix, amv, asv1, asv2, avrp, avui, ayuv, bitpacked, bmp, cfhd, cinepak, cljr, comfortnoise, dnxhd, dpx, dvvideo, ffv1, ffvhuff, fits, flv, gif, h261, h263, h263p, huffyuv, jpeg2000, jpegls, ljpeg, magicyuv, mjpeg, mpeg1video, mpeg2video, mpeg4, msmpeg4v2, msmpeg4, msvideo1, pam, pbm, pcx, pfm, pgm, pgmyuv, phm, ppm, prores, prores_aw, prores_ks, qoi, qtrle, r10k, r210, rawvideo, roqvideo, rpza, rv10, rv20, s302m, sgi, smc, snow, speedhq, sunrast, svq1, targa, tiff, utvideo, v210, v308, v408, v410, vbn, vc2, wbmp, wrapped_avframe, wmv1, wmv2, xbm, xface, xwd, y41p, yuv4, aac, ac3, ac3_fixed, alac, aptx, aptx_hd, dca, dfpwm, eac3, flac, g723_1, hdr, mlp, mp2, mp2fixed, nellymoser, opus, real_144, sbc, sonic, sonicls, truehd, tta, vorbis, wavpack, wmav1, wmav2, pcm_alaw, pcm_bluray, pcm_dvd, pcm_f32be, pcm_f32le, pcm_f64be, pcm_f64le, pcm_mulaw, pcm_s8, pcm_s8_planar, pcm_s16be, pcm_s16be_planar, pcm_s16le, pcm_s16le_planar, pcm_s24be, pcm_s24daud, pcm_s24le, pcm_s24le_planar, pcm_s32be, pcm_s32le, pcm_s32le_planar, pcm_s64be, pcm_s64le, pcm_u8, pcm_u16be, pcm_u16le, pcm_u24be, pcm_u24le, pcm_u32be, pcm_u32le, pcm_vidc, roq_dpcm, adpcm_adx, adpcm_argo, g722, g726, g726le, adpcm_ima_amv, adpcm_ima_alp, adpcm_ima_apm, adpcm_ima_qt, adpcm_ima_ssi, adpcm_ima_wav, adpcm_ima_ws, adpcm_ms, adpcm_swf, adpcm_yamaha, ssa, ass, dvbsub, dvdsub, mov_text, srt, subrip, text, ttml, webvtt, xsub, libsvtav1, libvpx, libvpx-vp9, vnull, anull, aasc, aic, alias_pix, agm, amv, anm, ansi, arbc, argo, asv1, asv2, aura, aura2, avrp, avrn, avs, avui, ayuv, bethsoftvid, bfi, binkvideo, bitpacked, bmp, bmv_video, brender_pix, c93, cavs, cdgraphics, cdtoons, cdxl, cfhd, cinepak, clearvideo, cljr, cllc, comfortnoise, cpia, cri, camstudio, cyuv, dds, dfa, dirac, dnxhd, dpx, dsicinvideo, dvaudio, dvvideo, dxtory, dxv, eacmv, eamad, eatgq, eatgv, eatqi, 8bps, 8svx_exp, 8svx_fib, escape124, escape130, ffv1, ffvhuff, fic, fits, flic, flv, fmvc, 4xm, fraps, frwu, gdv, gem, gif, h261, h263, h263i, h263p, h264, hap, hevc, hnm4video, hq_hqa, hqx, huffyuv, hymt, idcinvideo, iff, imm4, imm5, indeo2, indeo3, indeo4, indeo5, interplayvideo, ipu, jpeg2000, jpegls, jv, kgv1, kmvc, lagarith, loco, m101, magicyuv, mdec, media100, mimic, mjpeg, mjpegb, mmvideo, mobiclip, motionpixels, mpeg1video, mpeg2video, mpeg4, mpegvideo, msa1, msmpeg4v1, msmpeg4v2, msmpeg4, msp2, msrle, mss1, mss2, msvideo1, mszh, mts2, mv30, mvc1, mvc2, mvdv, mxpeg, notchlc, nuv, paf_video, pam, pbm, pcx, pfm, pgm, pgmyuv, pgx, phm, photocd, pictor, pixlet, ppm, prores, prosumer, psd, ptx, qdraw, qoi, qpeg, qtrle, r10k, r210, rawvideo, rka, rl2, roqvideo, rpza, rv10, rv20, rv30, rv40, s302m, sanm, scpr, sga, sgi, sgirle, sheervideo, simbiosis_imx, smackvid, smc, smvjpeg, snow, sp5x, speedhq, speex, sunrast, svq1, svq3, targa, targa_y216, theora, thp, tiertexseqvideo, tiff, tmv, truemotion1, truemotion2, truemotion2rt, tscc2, txd, ultimotion, utvideo, v210, v210x, v308, v408, v410, vb, vbn, vble, vc1, vc1image, vcr1, vmdvideo, vmnc, vp3, vp4, vp5, vp6, vp6a, vp6f, vp7, vp8, vp9, vqavideo, vqc, wbmp, webp, wrapped_avframe, wmv1, wmv2, wmv3, wmv3image, wnv1, xan_wc3, xan_wc4, xbm, xface, xl, xpm, xwd, y41p, ylc, yop, yuv4, 012v, aac, aac_fixed, aac_latm, ac3, ac3_fixed, acelp.kelvin, alac, als, amrnb, amrwb, apac, ape, aptx, aptx_hd, atrac1, atrac3, atrac3al, atrac3plus, atrac3plusal, atrac9, binkaudio_dct, binkaudio_rdft, bmv_audio, bonk, cook, dca, dfpwm, dolby_e, dsd_lsbf, dsd_msbf, dsd_lsbf_planar, dsd_msbf_planar, dsicinaudio, dss_sp, dst, eac3, evrc, fastaudio, wavesynth, flac, ftr, g723_1, g729, gsm, gsm_ms, hca, hcom, hdr, iac, ilbc, imc, interplayacm, mace3, mace6, metasound, misc4, mlp, mp1, mp1float, mp2, mp2float, mp3float, mp3, mp3adufloat, mp3adu, mp3on4float, mp3on4, mpc7, mpc8, msnsiren, nellymoser, on2avc, opus, paf_audio, qcelp, qdm2, qdmc, real_144, real_288, ralf, sbc, shorten, sipr, siren, smackaud, sonic, tak, truehd, truespeech, tta, twinvq, vmdaudio, vorbis, wavarc, wavpack, wmalossless, wmapro, wmav1, wmav2, wmavoice, ws_snd1, xma1, xma2, pcm_alaw, pcm_bluray, pcm_dvd, pcm_f16le, pcm_f24le, pcm_f32be, pcm_f32le, pcm_f64be, pcm_f64le, pcm_lxf, pcm_mulaw, pcm_s8, pcm_s8_planar, pcm_s16be, pcm_s16be_planar, pcm_s16le, pcm_s16le_planar, pcm_s24be, pcm_s24daud, pcm_s24le, pcm_s24le_planar, pcm_s32be, pcm_s32le, pcm_s32le_planar, pcm_s64be, pcm_s64le, pcm_sga, pcm_u8, pcm_u16be, pcm_u16le, pcm_u24be, pcm_u24le, pcm_u32be, pcm_u32le, pcm_vidc, cbd2_dpcm, derf_dpcm, gremlin_dpcm, interplay_dpcm, roq_dpcm, sdx2_dpcm, sol_dpcm, xan_dpcm, wady_dpcm, adpcm_4xm, adpcm_adx, adpcm_afc, adpcm_agm, adpcm_aica, adpcm_argo, adpcm_ct, adpcm_dtk, adpcm_ea, adpcm_ea_maxis_xa, adpcm_ea_r1, adpcm_ea_r2, adpcm_ea_r3, adpcm_ea_xas, g722, g726, g726le, adpcm_ima_acorn, adpcm_ima_amv, adpcm_ima_alp, adpcm_ima_apc, adpcm_ima_apm, adpcm_ima_cunning, adpcm_ima_dat4, adpcm_ima_dk3, adpcm_ima_dk4, adpcm_ima_ea_eacs, adpcm_ima_ea_sead, adpcm_ima_iss, adpcm_ima_moflex, adpcm_ima_mtf, adpcm_ima_oki, adpcm_ima_qt, adpcm_ima_rad, adpcm_ima_ssi, adpcm_ima_smjpeg, adpcm_ima_wav, adpcm_ima_ws, adpcm_ms, adpcm_mtaf, adpcm_psx, adpcm_sbpro_2, adpcm_sbpro_3, adpcm_sbpro_4, adpcm_swf, adpcm_thp, adpcm_thp_le, adpcm_vima, adpcm_xa, adpcm_xmd, adpcm_yamaha, adpcm_zork, ssa, ass, cc_dec, dvbsub, dvdsub, jacosub, microdvd, mov_text, mpl2, pgssub, pjs, realtext, sami, srt, stl, subrip, subviewer, subviewer1, text, vplayer, webvtt, xsub, libdav1d, libvpx, libvpx-vp9, bintext, xbin, idf, av1, vnull, anull
[LOG] 0.01 tl::io::ndi::Plugin: 
[LOG] 0.09 tl::usd::Render: 
    Renderers: GL
[LOG] 0.09 tl::timeline::System: Create
[LOG] 0.09 tl::timeline::System: register type RawMemoryReference: 1
[LOG] 0.09 tl::timeline::System: register type SharedMemoryReference: 1
[LOG] 0.09 tl::timeline::System: register type RawMemorySequenceReference: 1
[LOG] 0.09 tl::timeline::System: register type SharedMemorySequenceReference: 1
[LOG] 0.09 tl::timeline::System: register type ZipMemoryReference: 1
[LOG] 0.09 tl::timeline::System: register type ZipMemorySequenceReference: 1
[LOG] 0.09 tl::ui::FileBrowserSystem: Create
[LOG] 0.09 tl::ui::MessageDialogSystem: Create
[LOG] 0.09 tl::ui::ThumbnailSystem: Create
[LOG] 0.17 tl::image::FontSystem: Create
       [ocio] Setting OCIO config from preferences.
       [prefs] Path mappings have been loaded from "/home/mzigaib/.filmaura/mrv2.paths.prefs".
       [prefs] Loading hotkeys from "/home/mzigaib/.filmaura/mrv2.keys.prefs".
       [ocio] OCIO config is now:
       [ocio] /home/mzigaib/houdini20.0/ocio/houdini-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio
[LOG] 0.29 tl::timeline::create: 
    Create from path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Audio path: 
[LOG] 0.29 tl::timeline::Timeline 0x7efbb8001320: 
    File sequence audio: BaseName
    File sequence audio file name: 
    File sequence audio directory: 
    Video request count: 16
    Audio request count: 16
    Request timeout: 5ms
    AV I/O FFmpeg/ThreadCount: 0
    AV I/O FFmpeg/YUVToRGBConversion: 0
    AV I/O OpenEXR/IgnoreDisplayWindow: 0
    AV I/O SequenceIO/DefaultSpeed: 24
    AV I/O SequenceIO/ThreadCount: 16
    AV I/O USD/complexity: 1
    AV I/O USD/diskCacheByteCount: 0
    AV I/O USD/drawMode: ShadedSmooth
    AV I/O USD/enableLighting: 1
    AV I/O USD/renderWidth: 1920
    AV I/O USD/sRGB: 1
    AV I/O USD/stageCacheByteCount: 10
    Path max number digits: 9
[LOG] 0.29 tl::timeline::Timeline 0x3ea2c00: 
    Read: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg
    Video: 1280x720 RGB_U8
    Video time: 980.000000/20.000000/24.000000
    Audio: 0 None 0
    Audio time: -1.000000/-1.000000/-1.000000
[LOG] 0.29 tl::timeline::Timeline 0x7efbb8001320: 
    Time range: 980.000000/20.000000/24.000000
    Video: 1280x720 RGB_U8
    Audio: 0 None 0
[LOG] 0.29 tl::timeline::Player 0x7efbb8002390: 
    Cache read ahead: inf/1.000000
    Cache read behind: inf/1.000000
    Timer mode: System
    Audio buffer frame count: 2048
    Mute timeout: 500ms
    Sleep timeout: 5ms
[LOG] 0.29 tl::timeline::Player 0x3eaa6e0: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Current time: 980.000000/24.000000
    In/out range: 980.000000/20.000000/24.000000
    I/O options: 
    Cache: inf/1.000000 read ahead, inf/1.000000 read behind
    Video: 0 requests, 0 cached
    Audio: 0 requests, 0 cached
    T...............................................................................
    ................................................................................
    ................................................................................
    (T=current time, V=cached video, A=cached audio)
[LOG] 0.31 tl::timeline::create: 
    Create from path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Audio path: 
[LOG] 0.31 tl::timeline::Timeline 0x7efbb8001a60: 
    File sequence audio: BaseName
    File sequence audio file name: 
    File sequence audio directory: 
    Video request count: 16
    Audio request count: 16
    Request timeout: 5ms
    AV I/O FFmpeg/ThreadCount: 0
    AV I/O FFmpeg/YUVToRGBConversion: 0
    AV I/O OpenEXR/IgnoreDisplayWindow: 0
    AV I/O SequenceIO/DefaultSpeed: 24
    AV I/O SequenceIO/ThreadCount: 16
    AV I/O USD/complexity: 1
    AV I/O USD/diskCacheByteCount: 0
    AV I/O USD/drawMode: ShadedSmooth
    AV I/O USD/enableLighting: 1
    AV I/O USD/renderWidth: 1920
    AV I/O USD/sRGB: 1
    AV I/O USD/stageCacheByteCount: 10
    Path max number digits: 9
[LOG] 0.31 tl::timeline::Timeline 0x3ea2c00: 
    Read: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg
    Video: 1280x720 RGB_U8
    Video time: 980.000000/20.000000/24.000000
    Audio: 0 None 0
    Audio time: -1.000000/-1.000000/-1.000000
[LOG] 0.31 tl::timeline::Timeline 0x7efbb8001a60: 
    Time range: 980.000000/20.000000/24.000000
    Video: 1280x720 RGB_U8
    Audio: 0 None 0
[LOG] 0.31 tl::timeline::Player 0x7efbb80024e0: 
    Cache read ahead: 2.000000/1.000000
    Cache read behind: 0.500000/1.000000
    Timer mode: System
    Audio buffer frame count: 2048
    Mute timeout: 500ms
    Sleep timeout: 5ms
[LOG] 0.31 tl::timeline::Player 0x3a7cf10: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Current time: 980.000000/24.000000
    In/out range: 980.000000/20.000000/24.000000
    I/O options: 
    Cache: 2.000000/1.000000 read ahead, 0.500000/1.000000 read behind
    Video: 0 requests, 0 cached
    Audio: 0 requests, 0 cached
    T...............................................................................
    ................................................................................
    ................................................................................
    (T=current time, V=cached video, A=cached audio)
[LOG] 0.31 tl::gl::GLFWWindow: Create window: 1x1
[LOG] 0.32 tl::gl::GLFWWindow: Window size: 1x1
[LOG] 0.32 tl::gl::GLFWWindow: Frame buffer size: 1x1
[LOG] 0.32 tl::gl::GLFWWindow: Content scale: 1,1
[LOG] 0.32 tl::gl::GLFWWindow: OpenGL version: 4.1.0
[LOG] 0.36 tl::gl::GLFWWindow: Create window: 1x1
[LOG] 0.41 tl::gl::GLFWWindow: Window size: 1x1
[LOG] 0.41 tl::gl::GLFWWindow: Frame buffer size: 1x1
[LOG] 0.41 tl::gl::GLFWWindow: Content scale: 1,1
[LOG] 0.41 tl::gl::GLFWWindow: OpenGL version: 4.1.0
[LOG] 0.46 tl::image::FontSystem: Create
[LOG] 0.47 tl::gl::GLRender: Creating display shader
[LOG] 0.48 tl::gl::GLRender: Creating display shader
[LOG] 0.50 tl::gl::GLRender: Creating display shader
[LOG] 10.09 tl::usd::Render: 
    Requests: 0
    Stage cache: 0/10
    Disk cache: 0/0GB
[LOG] 10.31 tl::io::ISequenceRead 0x38b5060: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg
    Requests: 0, 0 in progress
    Thread count: 16
[LOG] 10.31 tl::timeline::Timeline 0x3ea2c00: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Video requests: 0, 0 in-progress, 16 max
    Audio requests: 0, 0 in-progress, 16 max
    Read cache: 1
[LOG] 10.32 tl::timeline::Player 0x3a7cf10: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0982.jpg
    Current time: 980.000000/24.000000
    In/out range: 980.000000/20.000000/24.000000
    I/O options: FFmpeg/ThreadCount:0, FFmpeg/YUVToRGBConversion:0, Layer:0, OpenEXR/IgnoreDisplayWindow:0, SequenceIO/DefaultSpeed:24, SequenceIO/ThreadCount:16, USD/complexity:1, USD/diskCacheByteCount:0, USD/drawMode:ShadedSmooth, USD/enableLighting:1, USD/renderWidth:1920, USD/sRGB:1, USD/stageCacheByteCount:10
    Cache: 802.613728/1.000000 read ahead, 200.653432/1.000000 read behind
    Video: 0 requests, 20 cached
    Audio: 0 requests, 0 cached
    T...............................................................................
    VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV....
    ................................................................................
    (T=current time, V=cached video, A=cached audio)
[LOG] 10.46 tl::ui::ThumbnailGenerator: 
    Info requests: 0
    Thumbnail requests: 0
    Waveform requests: 0
    Cache: 1, 0.0333333%
    I/O cache: 1, 0.1%
[LOG] 10.52 tl::io::ISequenceRead 0x7efb4896fac0: 
    Path: /home/mzigaib/Downloads/fractal_1/RND_paper_growth_v19.hip/fractal_1.0980.jpg
    Requests: 0, 0 in progress
    Thread count: 16

**Comment by mzigaib** [comment]
Attaching log file.
[loading.log](https://github.com/ggarra13/mrv2/files/14394493/loading.log)

**Comment by ggarra13** [comment]
Ok. I *FINALLY* was able to reproduce it.  I'll investigate.  Expect some news in a day or two.

**Comment by mzigaib** [comment]
Thanks man!

**Comment by ggarra13** [comment]
Ok.  It was a weird one.  It happened only randomly when the filesystem returned the files in a different order.  I fixed it now.  You can download v1.0.7 beta from:

.deb:
https://mega.nz/file/OPQ2ETBI#ebL7tV72MHotNmad6C9JR8iWJim47cyV7k8gXd0jmDY

.rpm:
https://mega.nz/file/SToWmJLY#3ycqjDOXuC_2vyqHOvfQ3YfRn35_xETd2wagiUnVygU

tar.gz:
https://mega.nz/file/OP4VCbxb#hlAhoZDllepgmxiwggj7mO2eCfmWuTFu2JonAewAiVk

**Comment by ggarra13** [comment]
OK.  It was a weird one.  It would happen randomly depending on how the filesystem listed the files.  Anyway, here are betas of v1.0.7 for Linux:

.deb:
https://mega.nz/file/abIwBBxI#PA-uVYwjU6EyBHxJl5ScPk340Ufxhe0cix4hEOTQEI0

.rpm:
https://mega.nz/file/ySZCGaJA#-UK8_os2bLoGB_bwgE3ZQiYq0RVyZkr_dNqBkPKcrps

.tar.gz:
https://mega.nz/file/bDAnkBgQ#tDEhNsyJLmIedqDPP012bla9XuFSyCpS2jCAlewH6QQ

**Comment by ggarra13** [comment]
> Thanks for the help I love this player by the way.

You are very welcome!  Let me know if the new v1.0.7 beta fixes your loading issues.

Cheers,
@ggarra13

**Comment by mzigaib** [comment]
Seems to be working now, Awesome!
Thanks man!
