### ISSUE TITLE
MacOS - File permissions

### ISSUE THREAD

**Issue by p2or** [ggarra13/mrv2#195]
Hi @ggarra13,

I have just noticed that I cannot load a file that was copied from a network drive and I need to run `chmod -R 644 /path/to/file` for each file in the first place, to get loaded properly into _mrv2_. 

Default permissions:

![Screenshot 2024-02-25 at 12 16 33](https://github.com/ggarra13/mrv2/assets/512368/2b306269-192d-4f17-b401-bcf1617ad090)

After the call (working):

![Screenshot 2024-02-25 at 12 35 44](https://github.com/ggarra13/mrv2/assets/512368/f6d2c87e-8139-4722-8ff1-2d8e6627c8a6)

Nothing urgent, but since this is a bit cumbersome, do you see a way around it?

Cheers,
Christian

**Comment by ggarra13** [comment]
Not sure how macOS deals with permissions, but in Unix, the default permissions flags are taken from the "umask" command.

Usually, I set "umask 0022" and add that command to the end of my ~/.zshrc file or similar.  Give it a test with:

```
cd ~
touch orig_file.txt
ls -l orig_file.txt
```

vs

```
cd ~
umask 0022
touch umask_file.txt
ls -l umask_file.txt
```

**Comment by p2or** [comment]
Hi @ggarra13,

thanks for your quick reply! I'll give it a whirl... However, as other players like OpenRV and DJV are able to load the data (just tested), do you see a way to solve this issue programmatically without us having to mess around with the file permissions?

Cheers,
Christian

**Comment by ggarra13** [comment]
How exactly are you loading the files?  With:

1) Finder: Select image.  RMB->Open With.  (does not work with mrv2.app but according to you works for mrv2.sh.app)
2) Finder: Drag and Drop to mrv2 started from /Applications/mrv2.app
3) Finder: Drag and Drop to mrv2.sh started from your trick of Automator  /Applications/mrv2.sh.app
4) Command-Line:  mrv2 <file>
5) mrv2's File->Open menu item with macOS normal file requester.
6) mrv2's File->Open menu Item with mrv2's custom file requester.
7) Some other way I am unaware....

**Comment by p2or** [comment]
Just tested all the options in your list (1-6) and the same error comes up for all of them:

> File does not exist or does not have read permissions.

Does this help? If you need more details, just let me know.

**Comment by ggarra13** [comment]
> Does this help? If you need more details, just let me know.

Okay, something is not right, as I know 5 is *sure* to work.

1. Did you copy the files from another disk?
2. Are you reading them from a network drive?
3. Are you reading them from a private user folder like Documents, etc?
4. Did you start mrv2 from /Applications/mrv2.sh (ie the normal install) or your Automator install?

Give me the output of the following commands:

5. whoami
6. ls -l "file"

**Comment by ggarra13** [comment]
I found out I had a BUG as big as a truck!!! I am compiling macOS binaries of v1.07 betas for you to play with.

**Comment by p2or** [comment]
Great, looking forward to it! Thanks for taking the time to tackle this issue.

**Comment by ggarra13** [comment]
Here are amd64 binaries of v1.0.7:

https://mega.nz/file/rSxHzL7R#4ya6-iIv5TvsM1CB5E4DwQzL2s180I39f7yuolAyIow

**Comment by p2or** [comment]
Good news: The new build works without any issues and _mrv2_ is able to load the data. Many thanks for your fix! 

Cheers,
Christian

*I leave it to you to close this issue in case you want to reference a specific commit.*

**Comment by ggarra13** [comment]
Here are arm64 (M1/M2/M3) binaries of v1.0.7 beta:

https://mega.nz/file/mKwlwBwb#pWzTQhGDQbkzGvUPz1t7qWe6Nnz8YdIYW90dR82P-6I
