### ISSUE TITLE
Image rotate 90 degrees

### ISSUE THREAD

**Issue by qsek** [ggarra13/mrv2#198]
In the original Program there were options to rotate the image or movie by +90 and -90 degrees.
For example to correct for vertical recorded videos on a smrtphone.
Can you readd this function again please?

**Comment by ggarra13** [comment]
I have added Render->Rotate->90 Degrees and Render->Rotate->-90 Degrees to the menus.  They have hotkey + and - by default.   It is there in the main branch.

If you want binaries, go to www.sourcefoge.net/projects/mrv2/files/beta.  Windows and arm64 macOs have already finished compiling.

**Comment by qsek** [comment]
Thanks, just tested it, but its not usable because mouse input is also rotated.
So if i move my mouse up, the cursor on screen moves to the right for "Rotate -90"

**Comment by ggarra13** [comment]
Please download v1.0.9 beta from:

http://www.sourceforge.net/projects/mrv2/files/beta

and see if it fixes your issues.  I fixed three things: the drawing tools (the cursor moving incorrectly), the pixel coordinates (not being rotated) and the color lookup (also incorrect).

**Comment by qsek** [comment]
GUI works as intended now. Thanks for the fast reply 👍
