### ISSUE TITLE
Specify Input Colour Space from command line

### ISSUE THREAD

**Issue by jtomori** [ggarra13/mrv2#199]
Hello,
thanks for developing this, it's very useful.

I'd like to ask whether you would consider adding a command line option for specifying Input Colour Space from command line. For example: `mrv2 image.exr -ics ACEScg`.

It could be helpful for integrating mrv2 into vfx tools, for example for previewing an image sequence in a given colour space, without requiring the user to select it manually.

Best,
Juraj

**Comment by ggarra13** [comment]
Added in v1.0.8 and main branch if you compile from source.  

The beta binary should be available on sourceforge's mrv2 beta directory in a couple of hours.

**Comment by jtomori** [comment]
Hello,
I've tested the Sourceforge 1.0.8 beta build and can confirm that it works well.

Many thanks,
Juraj
