### ISSUE TITLE
Command line args help not printed to terminal on Windows

### ISSUE THREAD

**Issue by jtomori** [ggarra13/mrv2#20]
Hello,
first, thanks for your awesome work, it's a really impressive project and very useful (especially with the good OCIO support).

While searching for a potential command line flag which would let me specify a path to `mrv2.prefs` (to preconfigure it automatically for multiple users) I've realized that no command line help gets printed to the terminal. Not sure if it's an intended behavior or a bug, thus filing this issue.

Tested mrv2 0.3.4 on Windows 10.

- Running `mrv2.exe -h` or `mrv2.exe --help` prints a blank line and nothing starts
- Running `mrv2.exe -v` or `mrv2.exe --version` starts mrv2 with a log window with a message `ERROR mrv2: failed to open file for reading: --version`

A quick code search has revealed [this](https://github.com/ggarra13/mrv2/blob/main/mrv2/lib/mrvApp/App.cpp#L186), which looks like a list of command line options.

Best,
Juraj

**Comment by ggarra13** [comment]
@jtomori Thanks for the bug report about the console.  It works under Msys but it will not work under cmd.exe or similar.  I have now added a fix to it.

There's no --version switch yet.  I'll see to add one.

Regarding mrv2.prefs, I am a little bit puzzled, as the preferences are picked from the home directory of the user automatically  That is, in this order:

%HOME%\.filmaura\mrv2.prefs
%USERPROFILE%\.filmaura\mrv2.prefs
%HOMEDRIVE%\%HOMEPATH%\%USERNAME%\.filmaura\mrv2.prefs

So just logging in as a different user should automatically switch the location of mrv2.prefs.  If you are sharing the same login with another user, then I recommend creating a .bat file that sets %HOME% to the location of where you want to store your preferences.

**Comment by jtomori** [comment]
Hello,
thank you for quick reply.

I see, haven't realized that it uses the `HOME` env var. You are right, that's enough to control which prefs will be read.

**Comment by jtomori** [comment]
Since you've fixed it then I will close this issue. Will test it with the next release.

**Comment by ggarra13** [comment]
@jtomori I am reopening the issue to send you the link to a beta for you to try.

https://mega.nz/file/mWpSGCiR#z8amUU29LTjesXlKHy8AjsFZ2XpRbSn3uGWNrT5WpAk

Give a try and see if it addresses your command-line issues.

P.S. Note that at this point not all command-line switches are functional.

**Comment by jtomori** [comment]
Hello,
I've just tested the `mrv2 0.3.5-beta1` and it prints the help message as expected.
