### ISSUE TITLE
How to let mrv2 remember initial window size and position on desktop?

### ISSUE THREAD

**Issue by pstein** [ggarra13/mrv2#201]
How to let mrv2 remember initial window size and position on desktop?

Currently I always have to adjust window manually at startup

**Comment by ggarra13** [comment]
Go to Window->Preferences->User Interface->Positioning.

Check Fixed Positioning and Fixed Size.  Push on the button Take Current Window Values.  

That will use those settings for each time it opens.

If you also want to update the size and positioning every time you exit the program, Check the "Always Save on Exit2 toggle.
