### ISSUE TITLE
Can't open EXR's in MacOS 14.4

### ISSUE THREAD

**Issue by Sosoyan** [ggarra13/mrv2#203]
<img width="322" alt="Screenshot 2024-03-12 at 9 50 04 PM" src="https://github.com/ggarra13/mrv2/assets/5727306/58ecdff6-8ffa-42f3-9f3a-331ed60adb48">

**Comment by ggarra13** [comment]
How are you trying to open it?  Are you doing RMB->Open With.  See Issue #184.

**Comment by Sosoyan** [comment]
I see, cheers
