### ISSUE TITLE
Load sequences issue on Linux with 1.1.1

### ISSUE THREAD

**Issue by mzigaib** [ggarra13/mrv2#210]
I am not able to load image jpg images or even sequences on Fedora39 with 1.1.1 it is saying that it cannot open, same thing with verison 1.1.0
Working fine loading exrs.

Update:
I just tested the same with version 1.09 and it is working fine with the same files.

**Comment by ggarra13** [comment]
> I am not able to load image jpg images or even sequences on Fedora39 with 1.1.1 it is saying that it cannot open, same thing with verison 1.1.0 Working fine loading exrs.
> 
> Update: I just tested the same with version 1.09 and it is working fine with the same files.

I was able to reproduce the issue, when dragging files from Nautilus to mrv2.  Is that how you are loading them?  Or is there any other way that don't load either (command-line, File->Open->Movie or Sequence, etc)?

**Comment by ggarra13** [comment]
Here's a beta of v1.1.2 that should fix the issue.  There was a conflict with the FLTK JPEG library and the one used in tlRender:

.deb:
https://mega.nz/file/nCJTCIQL#PsVVT8-SZTmwfeMu1ZrR05RP9ts2JFOFrBzinSLROsE

.rpm:
https://mega.nz/file/3PwzDIjL#9PC_XYxG3R6dmBboiw6nfySE2ukY-YpGs_AdcqEkmhI

.tar.gz:
https://mega.nz/file/uCwxDYbb#qKlys6xaAsQxMQaOhl5JJw9ql5RQxz2WjGYKNV6Uieo

**Comment by ggarra13** [comment]
I did a more correct fix to the problem.  Please us these instead of my previous (now deleted) email:

.deb:
https://mega.nz/file/qXBTlKBA#bJcQuVFSPPVrbb_sLuIs_i-7jpoRJydGlIn0nCcA2Io

.rpm:
https://mega.nz/file/iDQxXTRA#1TblabGz7r5ERy3JCGmgA2jZPVqC6elFo1VyenzUQeo

.tar.gz:
https://mega.nz/file/6KAjgJZR#ZOrgzDPtIP1LhSRC8Drk2zd4Z7a7FylexCbpPyrq2TY

**Comment by mzigaib** [comment]
It is working fine now when I double click the jpg files to load now.
Thanks!

**Comment by ggarra13** [comment]
Fixed in v1.1.2.
