### ISSUE TITLE
Crashes if set to use native file browser

### ISSUE THREAD

**Issue by mzigaib** [ggarra13/mrv2#211]
It crashes if I set to use the native file browser to open files on Fedora 39.

**Comment by ggarra13** [comment]
It works for me on Rocky Linux 8.9 (where I compiled it) and crashes on Ubuntu 22.04.3 LTS, with this error:

```
(mrv2:5171): GdkPixbuf-WARNING **: 11:48:11.310: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command (as sudo)
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
```
Run it command-line to see if you get the same error.  If you do, you might fix it by running the above command or by installing gdk-pixbuf-2.0.  On Ubuntu 22.04.3 LTS to fix it, I had to do:

```
sudo apt update
sudo apt reinstall libgdk-pixbuf2.0-0
```

**Comment by mzigaib** [comment]
I will let you know soon

**Comment by mzigaib** [comment]
Hi!
That is the error I get
(mrv2:7991): Gtk-WARNING **: 23:19:51.318: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/Adwaita/scalable/status/image-missing.svg: Unable to load image-loading module: /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: /usr/lib64/librsvg-2.so.2: undefined symbol: pango_context_set_round_glyph_positions (gdk-pixbuf-error-quark, 5)
GOT SIGNAL 6
frame 1: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0xb1263e]
frame 2: ??:0
         /usr/lib64/libc.so.6(+0x3e9a0) [0x7f7178c5c9a0]
frame 3: ??:0
         /usr/lib64/libc.so.6(+0x90834) [0x7f7178cae834]
frame 4: ??:0
         /usr/lib64/libc.so.6(raise+0x1e) [0x7f7178c5c8ee]
frame 5: ??:0
         /usr/lib64/libc.so.6(abort+0xdf) [0x7f7178c448ff]
frame 6: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(+0x1c2b3) [0x7f717761c2b3]
frame 7: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(g_assertion_message_error+0xb2) [0x7f7177675ee2]
frame 8: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x205b65) [0x7f7179c05b65]
frame 9: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2062d5) [0x7f7179c062d5]
frame 10: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x206394) [0x7f7179c06394]
frame 11: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x206588) [0x7f7179c06588]
frame 12: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x219e61) [0x7f7179c19e61]
frame 13: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17b747) [0x7f7179b7b747]
frame 14: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17fa79) [0x7f7179b7fa79]
frame 15: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x21a657) [0x7f7179c1a657]
frame 16: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e47d1) [0x7f7179ce47d1]
frame 17: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 18: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_width+0x7e) [0x7f7179ce50ee]
frame 19: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x12a8c2) [0x7f7179b2a8c2]
frame 20: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17b747) [0x7f7179b7b747]
frame 21: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17fa79) [0x7f7179b7fa79]
frame 22: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x12b3a7) [0x7f7179b2b3a7]
frame 23: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e47d1) [0x7f7179ce47d1]
frame 24: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 25: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_width+0x7e) [0x7f7179ce50ee]
frame 26: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e47d1) [0x7f7179ce47d1]
frame 27: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 28: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_width+0x7e) [0x7f7179ce50ee]
frame 29: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x1256c9) [0x7f7179b256c9]
frame 30: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2c08fa) [0x7f7179cc08fa]
frame 31: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e47d1) [0x7f7179ce47d1]
frame 32: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 33: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_width+0x7e) [0x7f7179ce50ee]
frame 34: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17b747) [0x7f7179b7b747]
frame 35: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17fa79) [0x7f7179b7fa79]
frame 36: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2344cb) [0x7f7179c344cb]
frame 37: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e47d1) [0x7f7179ce47d1]
frame 38: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 39: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_width+0x7e) [0x7f7179ce50ee]
frame 40: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2341c5) [0x7f7179c341c5]
frame 41: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17b747) [0x7f7179b7b747]
frame 42: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17fa79) [0x7f7179b7fa79]
frame 43: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x234340) [0x7f7179c34340]
frame 44: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17b747) [0x7f7179b7b747]
frame 45: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x17fa79) [0x7f7179b7fa79]
frame 46: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x23445e) [0x7f7179c3445e]
frame 47: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e489b) [0x7f7179ce489b]
frame 48: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x2e5000) [0x7f7179ce5000]
frame 49: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_get_preferred_height+0x81) [0x7f7179ce4501]
frame 50: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x38b43f) [0x7f7179d8b43f]
frame 51: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x38b9f5) [0x7f7179d8b9f5]
frame 52: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_set_valist+0x3db) [0x7f717b218a8b]
frame 53: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_set+0xf4) [0x7f717b219364]
frame 54: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_scrolled_window_set_hadjustment+0x164) [0x7f7179cceea4]
frame 55: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(+0x16379) [0x7f717b216379]
frame 56: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_newv+0x24d) [0x7f717b217a6d]
frame 57: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x132352) [0x7f7179b32352]
frame 58: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x134e63) [0x7f7179b34e63]
frame 59: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(+0x512f1) [0x7f71776512f1]
frame 60: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(g_markup_parse_context_parse+0xe61) [0x7f7177652391]
frame 61: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x13586e) [0x7f7179b3586e]
frame 62: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_builder_extend_with_template+0x1f0) [0x7f7179b30660]
frame 63: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_init_template+0xef) [0x7f7179da0d0f]
frame 64: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x1d783f) [0x7f7179bd783f]
frame 65: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_type_create_instance+0x31a) [0x7f717b2339da]
frame 66: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(+0x15fc8) [0x7f717b215fc8]
frame 67: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_newv+0x24d) [0x7f717b217a6d]
frame 68: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x132352) [0x7f7179b32352]
frame 69: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x133985) [0x7f7179b33985]
frame 70: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x13543d) [0x7f7179b3543d]
frame 71: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(+0x51432) [0x7f7177651432]
frame 72: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libglib-2.0.so.0(g_markup_parse_context_parse+0x1016) [0x7f7177652546]
frame 73: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x13586e) [0x7f7179b3586e]
frame 74: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_builder_extend_with_template+0x1f0) [0x7f7179b30660]
frame 75: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_widget_init_template+0xef) [0x7f7179da0d0f]
frame 76: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(+0x1cecd2) [0x7f7179bcecd2]
frame 77: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_type_create_instance+0x31a) [0x7f717b2339da]
frame 78: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(+0x15fc8) [0x7f717b215fc8]
frame 79: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_new_valist+0x42e) [0x7f717b217f4e]
frame 80: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgobject-2.0.so.0(g_object_new+0x9d) [0x7f717b2182ad]
frame 81: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libgtk-3.so.0(gtk_file_chooser_dialog_new+0x78) [0x7f7179bcf888]
frame 82: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN33Fl_GTK_Native_File_Chooser_Driver22fl_gtk_chooser_wrapperEv+0x88) [0x7f717c989c08]
frame 83: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0x728e9a]
frame 84: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0x72a32d]
frame 85: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0x71bf38]
frame 86: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN8Fl_Menu_6pickedEPK12Fl_Menu_Item+0x6a) [0x7f717c9190da]
frame 87: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN11Fl_Menu_Bar6handleEi+0x51) [0x7f717c919c91]
frame 88: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN8Fl_Group6handleEi+0x55b) [0x7f717c90261b]
frame 89: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN8Fl_Group6handleEi+0x55b) [0x7f717c90261b]
frame 90: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN8Fl_Group6handleEi+0x55b) [0x7f717c90261b]
frame 91: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN8Fl_Group6handleEi+0x55b) [0x7f717c90261b]
frame 92: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0xa32580]
frame 93: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN2Fl7handle_EiP9Fl_Window+0x5de) [0x7f717c8e4dde]
frame 94: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_Z9fl_handleRK7_XEvent+0x9fb) [0x7f717c99495b]
frame 95: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(+0x142702) [0x7f717c996702]
frame 96: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN21Fl_Unix_Screen_Driver25poll_or_select_with_delayEd+0x292) [0x7f717c9729b2]
frame 97: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN21Fl_Unix_System_Driver4waitEd+0x5b) [0x7f717c97dabb]
frame 98: ??:0
         /usr/local/mrv2-v1.1.2-Linux-64/lib/libfltk.so.1.4(_ZN2Fl3runEv+0x21) [0x7f717c8e3da1]
frame 99: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0x58c63f]
frame 100: ??:0
         /usr/lib64/libc.so.6(+0x2814a) [0x7f7178c4614a]
frame 101: ??:0
         /usr/lib64/libc.so.6(__libc_start_main+0x8b) [0x7f7178c4620b]
frame 102: ??:?
         /usr/local/mrv2-v1.1.2-Linux-64/bin/mrv2() [0x5ad04e]

**Comment by mzigaib** [comment]
I already did reinstall gtk3 and the issue is the same.

**Comment by mzigaib** [comment]
I can live without having the native file browser, but would be to have it

**Comment by ggarra13** [comment]
I am asking around and searching.  You seem to have two issues: a misconfiguration of the icons (which is likely harmless) and a library incompatibility (which makes it crash).

**Comment by mzigaib** [comment]
Yeah it seems so, I try to always keep bleeding edge and sometimes new stuff gets conflicted, I love Linux but this distro differences are a turn off.

**Comment by mzigaib** [comment]
Well if you know something that can help I appreciate but I won't bother you with this anymore.
Thanks for the help anyway.
