### ISSUE TITLE
Reloading image sequences

### ISSUE THREAD

**Issue by robertvoy** [ggarra13/mrv2#212]
Hello,

It would be great to have the ability to reload image sequences so that new frames are added.

i.e. when I'm rendering and I'm previewing the frames that are rendered so far, it would be nice to be able to just reload the image sequence, so the new frames are added to the preview. Even better if this would happen automatically.

**Comment by ggarra13** [comment]
I am on my phone now.  But I think if you go to the Files panel and press the Right Mouse Button there's a Refresh Cache option.

**Comment by ggarra13** [comment]
I just checked and the feature is broken in the latest release.  Sorry.  I'll see to fix it for v1.1.2.

**Comment by robertvoy** [comment]
> I just checked and the feature is broken in the latest release. Sorry. I'll see to fix it for v1.1.2.

Great, thank you!

**Comment by ggarra13** [comment]
> Great, thank you!

You can check the beta of v1.1.2 at:

https://sourceforge.net/projects/mrv2/files/beta/

and see if Files Panel->Select image / RMB->File->Refresh Cache works for you.

**Comment by ggarra13** [comment]
Added in v1.1.2.
