### ISSUE TITLE
mrv 1.1.3 arm64 immediate crash after start

### ISSUE THREAD

**Issue by verstaerkermusic** [ggarra13/mrv2#220]
just downloaded mrv 1.1.3 and tried to start it on my mac Studio M2  .. it directly crashes after start 

i have this crashlog
[mrv2-2024-04-21-142104.ips.zip](https://github.com/ggarra13/mrv2/files/15051895/mrv2-2024-04-21-142104.ips.zip)

**Comment by verstaerkermusic** [comment]
the last working one is 1.1.1

**Comment by ggarra13** [comment]
Give a go again to v1.1.3 in either github or sourceforge and report back if it the crashes still persist.

**Comment by verstaerkermusic** [comment]
thank you, this works now!
