### ISSUE TITLE
mrv2 v1.1.3 keeps crashing on Windows 11

### ISSUE THREAD

**Issue by pxt777** [ggarra13/mrv2#223]
Hi,

I've installed mrv2 v1.1.3 on Windows 11, and I can launch it without any issues. However, it consistently crashes/closes after a few seconds of use. 
I've attempted to resolve this by trying older versions like mrv2 v1.1.2 and mrv2 v1.1.1, but unfortunately, I encounter the same problem.

System specs:
12th Gen Intel(R) Core(TM) i7-12700K   3.60 GHz
RAM 32.0 GB
NVIDIA GeForce RTX 4070 Ti

Thanks

**Comment by ggarra13** [comment]
Can you be more specific?  Is there anything in particular that you do that makes it crash?  Opening a file?  Playing back a movie?  Playing back EXRs?  Saving Sequences or Movies? Using the UI? Changing OCIO configurations?

**Comment by pxt777** [comment]
There doesn't seem to be a specific trigger causing the crashes. I've recently started using mrv2 and have been testing simple tasks. 
Typically, I open small video files (mp4, mov, wmv), manipulate the timeline, experiment with annotation tools like arrows, pencils, and text tools and save movies.
Everything appears to be functioning normally, but at random intervals, mrv2 unexpectedly closes without warning. 
This occurs even when using different tools, so it's not tied to a specific function.

**Comment by ggarra13** [comment]
Okay.  You are the first one to report actual crashes with mrv2, so it is likely something related either to your machine configuration or your workflow.  I assume you don't have another machine on your network to test, so to debug this issue you will have to be patient with me and do some chores.

I'll have you do some things (stick with mrv2-v1.1.3):

1) Attach your actual preference configuration.  It is in `C:/Users/<YourLogin>/.filmaura/mrv2.prefs`  or `%HOME%/.filmaura/mrv2.prefs` if you have that variable defined.
2) Upgrade your NVidia video drivers to the latest version, just in case.
3) Are you comfortable with the Terminal / cmd.exe?  If you are, I would like you to open a Terminal and start mrv2.exe from there.  To start mrv2.exe, you would do:

    If it is in your PATH already, just:

    `mrv2-v1.1.3.exe`

    If it is not in your PATH, type the full path to it:

    `C:\Program Files\mrv2-v1.1.3\bin\mrv2-v1.1.3.exe`
    
    Leave the terminal open and use the program until it crashes.  It should print out a stack trace log of the crash.  It may not tell us much, but it might help.  Copy and Paste the stack trace here without pressing Enter on the terminal.

4) Record yourself with a screen recording tool using the program until it crashes.  I personally use FreeCam (https://www.freescreenrecording.com/) but if you have other tool you like is fine.  Upload the video without editing it to some web upload service like www.mega.nz, dropbox, etc.  Post the link here.

**Comment by pxt777** [comment]
I've installed and tested mrv2 on a similar machine, and unfortunately, it's experiencing the same random crashes. 

Following your instructions, I've:

1. Located my preference configuration at `C:/Users/USER1/.filmaura/mrv2.prefs`
2. Updated my Nvidia drivers
3. Started mrv2 with the Terminal, crashed as expected and encountered the following output:

```
C:\Users\USER1>mrv2-v1.1.3.exe

C:\Users\USER1>       [app] mrv2 v1.1.3 - Built Apr 20 2024 21:12:19
       [app] Running on: Windows 8+
       [app] Set Language to en_US.UTF-8, Numbers to C
       [prefs] Reading preferences from "C:\Users\USER1/.filmaura/mrv2.prefs".
       [prefs] Loaded color themes from "C:/Program Files/mrv2-v1.1.3/colors/mrv2.colors".
       [ocio] Setting OCIO config to default:
       [ocio] ocio://default
       [prefs] Path mappings have been loaded from "C:\Users\USER1/.filmaura/mrv2.paths.prefs".
       [prefs] Loading hotkeys from "C:\Users\USER1/.filmaura/mrv2.keys.prefs".
GOT SIGNAL 11
0: RtAudio::getDefaultInputDevice - 0x140699075959504
1: log2f - 0x140711774566800
2: RtApi::verifyStream - 0x140699077557824
3: _C_specific_handler - 0x140711332935328
4: _chkstk - 0x140711815889632
5: RtlFindCharInUnicodeString - 0x140711815338448
6: KiUserExceptionDispatcher - 0x140711815885776
7: Fl_Window::handle - 0x140709297099744
8: Fl_Window::y_root - 0x140709297101632
9: fl_win32_xid - 0x140709297228272
10: Fl_Tiled_Image::draw - 0x140709297052528
11: fl_control_modifier - 0x140709296916000
12: Fl_Window::icons - 0x140709297290000
13: Fl::run - 0x140709296628080
14: RtAudioError::~RtAudioError - 0x140699073157680
15: RtAudioError::~RtAudioError - 0x140699073157680
16: RtApi::verifyStream - 0x140699077557824
17: BaseThreadInitThunk - 0x140711794189664
18: RtlUserThreadStart - 0x140711815588384
```

4. At this moment, I'm unable to record my screen.

I hope this information proves helpful.

**Comment by ggarra13** [comment]
Okay.  I compiled debug builds of mrv2 (v1.1.4) for you to test.  It won't fix your crashes but it will give me a useful stack trace with line numbers now.

.exe:
https://mega.nz/file/SO4UATCD#pU0jY6E98pJX0lBW5caHCAChD6XQZWTeR2GpqRRCDXw

.zip:
https://mega.nz/file/vGQmAZoA#Wr5MRQP5xtKPZ-yteKBgF9w_pwKbxb_zj6hzlU3O0xI

Install them and run them from the terminal as you did before, like:

C:\Program Files\mrv2-v1.1.4\bin\mrv2-v1.1.4.exe

When it crashes, it may open a popup window.  If it does, click on Retry.  It will print out the stack trace to the terminal but with files and line numbers now.

**Comment by ggarra13** [comment]
I updated the mega.nz links.

**Comment by pxt777** [comment]
I've installed mrv2-v1.1.4.exe, but when I try to run it, I encounter the following errors:

![image](https://github.com/ggarra13/mrv2/assets/167889539/bc13fa71-fb09-4541-992a-bbaddbe80aeb)

![image](https://github.com/ggarra13/mrv2/assets/167889539/a6a323ca-536d-4b39-9ce1-c1b349128fb1)

![image](https://github.com/ggarra13/mrv2/assets/167889539/5415c29e-93ca-499a-93fb-ff6e18807b6f)

![image](https://github.com/ggarra13/mrv2/assets/167889539/471a1ad2-4853-41c8-b8ba-7e074721984c)

I've reinstalled it, but the errors persists.

**Comment by ggarra13** [comment]
I apologyze for that.  Windows and cmake prevent distributions of the debug versions of their DLLs for security reasons.  I've compiled overnight a Release version but with line numbers in sourceforge:

https://sourceforge.net/projects/mrv2/files/beta/mrv2-beta-Windows-amd64.exe/download

This should work fine.  If it crashes it will report the crash to the terminal and save a copy to %TEMP%/mrv2_crash.log.

**Comment by alexvng** [comment]
I am also seeing this issue, or at least something similar to it. I will get inconsistent random crashes while I am playing a video file (which is the only thing I use mrv2 for).

Would I be able to install the above version and help you troubleshoot too?

More info / potential hints:
- Usually, I see it happen immediately as my mouse exits the window boundaries. (I think. Not 100% sure).
  - - I've seen it crash while not in focus as well, with no input from me. But the above is way more common.
- It happens inconsistently, not every time.
- I've seen this crash on videos with the container/codec/audio settings of WEBM/VP9/OPUS and MOV/QT/noaudio so far.
- I open videos on an rclone network drive (a software-based NAS kinda thing), which tends to have pretty high latency?
- I use mrv2 primarily for viewing videos with an alpha channel (the WEBMs and MOVs are partial passes from 3D CGI footage).

```
Processor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installed RAM	16.0 GB (13.9 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 20 touch points

Edition	Windows 11 Home
Version	23H2
Installed on	‎10/‎4/‎2022
OS build	22631.3447
Experience	Windows Feature Experience Pack 1000.22688.1000.0
```

**Comment by ggarra13** [comment]
> I am also seeing this issue, or at least something similar to it. I will get inconsistent random crashes while I am playing a video file (which is the only thing I use mrv2 for).

Thanks for reporting this major problem and how you use it.  Please download the beta version from sourceforge that has debugging information on it and try to crash it.

If you are already using it and getting a crash, look in:

%TMP%/mrv2.crash.log

Attach that file here (you might need to rename it as mrv2.crash.txt as GitHub might reject it).

**Comment by ggarra13** [comment]
> Would I be able to install the above version and help you troubleshoot too?

Yes, please!  Download the beta from sourceforge and try it out.  The sooner we can get a stack trace with files and line numbers, the sooner we can fix the issue.

**Comment by alexvng** [comment]
Just got a crash while viewing a MP4/H264/AAC file on my local drive. It crashed when I left clicked on the timeline to jump ahead. Here's that crash log:

```
0: RtAudio::getDefaultInputDevice - 0x140696634054128 (line number unavailable)
1: log2f - 0x140712599992720 (line number unavailable)
2: RtApi::verifyStream - 0x140696635975232 (line number unavailable)
3: _C_specific_handler - 0x140712359947296 (line number unavailable)
4: _chkstk - 0x140712637973216 (line number unavailable)
5: RtlFindCharInUnicodeString - 0x140712637422032 (line number unavailable)
6: KiUserExceptionDispatcher - 0x140712637969360 (line number unavailable)
7: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
8: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
9: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
10: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
11: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
12: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
13: Fl_Widget::activate - 0x140711328125695 (line number unavailable)
14: RtAudioError::~RtAudioError - 0x140696631345440 (line number unavailable)
15: RtAudioError::~RtAudioError - 0x140696631345440 (line number unavailable)
16: RtApi::verifyStream - 0x140696635975232 (line number unavailable)
17: BaseThreadInitThunk - 0x140712619091296 (line number unavailable)
18: RtlUserThreadStart - 0x140712637671968 (line number unavailable)
```

**Comment by alexvng** [comment]
It looks like the audio was a problem, so I'll give you some info about my system regarding that.

File I was playing is:
~500MB MP4 file, h.264 codec, AAC audio
Audio bit rate 316kbps
2 channel stereo
Sample rate 48 kHz

Various screenshots of audio drivers attached, if that could possibly be useful
![image](https://github.com/ggarra13/mrv2/assets/18650322/ad602c5b-1425-4044-b839-c5d76f3c768d)
![image](https://github.com/ggarra13/mrv2/assets/18650322/14c0b904-d4eb-4a74-b770-e873f0d42a13)
![image](https://github.com/ggarra13/mrv2/assets/18650322/180d3c2f-0fd6-4b09-b8ac-599cd1214975)

**Comment by ggarra13** [comment]
Sadly, we did not get line numbers, because I found out that on Windows you have to do something else: give you .pdb files.

**Downloads**

First, download this new .exe installer of mrv2-v1.1.4:
https://mega.nz/file/HW4FXCCR#3jC_WpVkFAg8Br-t170yI6ReMM_bLMwCQ_Pb6qMtxeM

Install the program wherever you want.

Then, download the .pdb files in this zip archive:
https://mega.nz/file/SSRAQZST#q24vnadeLxCzS4AfYySgM7dO0D5yDiV7fR9uScG2xOw

**PDB Setup**

I hope you have a D: drive with 500Mb or so.  If you don't, I'll have to do a recompile for your C:\ drive assuming you have space there.  The tricky thing is that you need to create a directory that matches my setup:

`D:\code\applications\mrv2`

Put the .zip archive there and uncompress it with unzip, winzip or winrar, so that you get:

`D:\code\applications\mrv2\BUILD-Msys-amd64\`  

and all .pdb files and subdirectories mimicking my setup.

**Testing** 

Start this new installed version of mrv2 v1.1.4.  I put "a crash" in the button for frame window button (at the top right corner next to the Edit button).  Hit that button to make it crash.  If you installed the .pdb files correctly, you will get a stack trace in %TMP% but with files and line numbers now.  If you don't get files and line numbers, check that you created the directory **exactly** as shown above.

**Now for the real crash**

If that worked, then play with the new mrv2 v1.1.4 until you make it crash.  The new stack trace should have files and numbers, which will tell us clearly where it is crashing.

**Comment by alexvng** [comment]
I do not have a D drive, sorry! Laptop here.

**Comment by ggarra13** [comment]
Do you have abot 700Mb on your C: drive for the full mrv2?  If not I can send you a trimmed version of mrv2 for testing with just movie playback (no python, no pdf, no network, no tiff, no raw, no tga.  Just movies, codecs and exrs).

**Comment by ggarra13** [comment]
I've updated the instructions and links to the files to a trimmed version of mrv2.  Please see above instructions again.

**Comment by alexvng** [comment]
I just followed the instructions again and when I did your test crash, I got this back. 

```
0: mrv::callback - 0x140701647072160 (C:\code\mrv2\mrv2\lib\mrvCore\win32\mrvSignalHandler.cpp:37)
1: raise - 0x140705405068464 (line number unavailable)
2: abort - 0x140705405073008 (line number unavailable)
3: ViewerUI::cb__i - 0x140701646731424 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\mrv2\src\mrv2-build\lib\mrvWidgets\mrViewer.cxx:1127)
4: ViewerUI::cb_ - 0x140701646731312 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\mrv2\src\mrv2-build\lib\mrvWidgets\mrViewer.cxx:1131)
5: Fl_Widget::do_callback - 0x140701644890720 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_Widget.cxx:382)
6: Fl_Button::handle - 0x140701644892464 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_Button.cxx:207)
7: mrv::Button::handle - 0x140701646764144 (C:\code\mrv2\mrv2\lib\mrvWidgets\mrvButton.cpp:19)
8: send_event - 0x140701644885120 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl.cxx:1223)
9: Fl::handle_ - 0x140701644880800 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl.cxx:1439)
10: mouse_event - 0x140701645068592 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_win32.cxx:1091)
11: WndProc - 0x140701645054800 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_win32.cxx:1724)
12: DispatchMessageW - 0x140705430340128 (line number unavailable)
13: DispatchMessageW - 0x140705430340128 (line number unavailable)
14: Fl_WinAPI_System_Driver::wait - 0x140701645075376 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_win32.cxx:414)
15: Fl::run - 0x140701644884672 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl.cxx:605)
16: main - 0x140701644700128 (C:\code\mrv2\mrv2\src\main.cpp:70)
17: WinMain - 0x140701644699808 (C:\code\mrv2\mrv2\src\main.cpp:125)
18: __scrt_common_main_seh - 0x140701651483248 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
19: BaseThreadInitThunk - 0x140705406854496 (line number unavailable)
20: RtlUserThreadStart - 0x140705442605600 (line number unavailable)
```

I assume this means the steps worked, so I'll keep an eye out for my next crash and send the crashdump once it happens.

**Comment by alexvng** [comment]
Well, that was quick. I started clicking around randomly in the timeline again (outside of the blue buffer bar) and got a crash within 10 clicks.

Real crash dump:
```
0: mrv::callback - 0x140701647072160 (C:\code\mrv2\mrv2\lib\mrvCore\win32\mrvSignalHandler.cpp:37)
1: log2f - 0x140705404926352 (line number unavailable)
2: `__scrt_common_main_seh'::`1'::filt$0 - 0x140701651910942 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:304)
3: _C_specific_handler - 0x140705005169712 (line number unavailable)
4: _chkstk - 0x140705442906848 (line number unavailable)
5: RtlFindCharInUnicodeString - 0x140705442355664 (line number unavailable)
6: KiUserExceptionDispatcher - 0x140705442902992 (line number unavailable)
7: Fl_Window::handle - 0x140701644897184 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_Window.cxx:595)
8: Fl_Window_Driver::hide_common - 0x140701644960032 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_Window_Driver.cxx:173)
9: Fl_WinAPI_Window_Driver::hide - 0x140701645080560 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\drivers\WinAPI\Fl_WinAPI_Window_Driver.cxx:470)
10: Fl_Timeout::do_timeouts - 0x140701644961840 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_Timeout.cxx:490)
11: Fl_System_Driver::wait - 0x140701645030560 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_System_Driver.cxx:360)
12: Fl_WinAPI_System_Driver::wait - 0x140701645075376 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl_win32.cxx:362)
13: Fl::run - 0x140701644884672 (C:\code\mrv2\BUILD-Msys-amd64-small\Release\FLTK-prefix\src\FLTK\src\Fl.cxx:605)
14: main - 0x140701644700128 (C:\code\mrv2\mrv2\src\main.cpp:70)
15: WinMain - 0x140701644699808 (C:\code\mrv2\mrv2\src\main.cpp:125)
16: __scrt_common_main_seh - 0x140701651483248 (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
17: BaseThreadInitThunk - 0x140705406854496 (line number unavailable)
18: RtlUserThreadStart - 0x140705442605600 (line number unavailable)
```

**Comment by ggarra13** [comment]
Excellent!  We found at least one crashing bug thanks to your help.  Here's a fix to the bug and new .pdb files for you to keep testing:

.exe:
https://mega.nz/file/eTAhiRJL#1cKZ3jHpy0oAtrQtNENpJklGJ_8v8nhrLazJjt3qp8o

.pdb files to install again on the same place (just remove the BUILD-MSys-Windows-small directory):
https://mega.nz/file/zORFmJjI#icfy2YFjt2FxNaTXisWjU4-VsUgqN3x3NB4Fqrk9ghk

If you get further crashes, please report them.

**Comment by ggarra13** [comment]
Bug fixed in v1.1.4.

**Comment by ggarra13** [comment]
@pxt777 While you wait for v1.1.4 to be released (probably sometime next week), you can work around the crashes if you go to:

`Window->Preferences`

and then go to:

`Timeline`

and uncheck:

`Preview Thumbnails`

**Comment by pxt777** [comment]
> @pxt777 While you wait for v1.1.4 to be released (probably sometime next week), you can work around the crashes if you go to:
> 
> `Window->Preferences`
> 
> and then go to:
> 
> `Timeline`
> 
> and uncheck:
> 
> `Preview Thumbnails`

Yes, that worked! I disabled off the timeline and the crashes stopped.
And thanks to [alexvng](https://github.com/alexvng) for all the testing. I didn't have access to the PC during the weekend, so i wasn't able to help you.

Tommorrow, i will try v1.1.4.
