### ISSUE TITLE
M3 Max Crash MacOs 14.4.1

### ISSUE THREAD

**Issue by piotrnikov** [ggarra13/mrv2#228]
Hi!
Sorry but I'm having crashes when playing/Scrubbing with v1.1.5.
I've attached the log file.
Thanks!

Piotr
[CrashLogs_AppleM3.txt](https://github.com/ggarra13/mrv2/files/15217794/CrashLogs_AppleM3.txt)

**Comment by ggarra13** [comment]
Try turning off Timeline Thumbnails.  I just found the issue myself too.

Preferences->Timeline->Preview Thumbnails unchecked.

**Comment by piotrnikov** [comment]
Ah yes, that solves it, thanks!

**Comment by ggarra13** [comment]
Please download v1.1.5 again and try it.  I found other additional problems with the timeline viewport (it could not be dragged for example).

**Comment by piotrnikov** [comment]
Just downloaded it again.
No more crashes, but the Timeline still acts weird with Quicktimes (seems to work as intended on sequence files).

**Comment by ggarra13** [comment]
> No more crashes, but the Timeline still acts weird with Quicktimes (seems to work as intended on sequence files).

What do you mean by "weird"?  It does not jump to the right frame?  It does not show thumbnails in Edit mode?  It shows the above "preview thumbnail" icorrectly or not centered?

**Comment by ggarra13** [comment]
> Does that make sense?

Yes.  I see.  i don't have an M3 box to reproduce it.  But now I know what I'm looking for.  Some more questions:

1) Video resolution of the .qt file? (if you can provide it, better!  Send a link privately if need be at ggarra13@gmail.com)
2) Can you attach your mrv2.prefs file?  (it is in $HOME/.filmaura/mrv2.prefs)

**Comment by ggarra13** [comment]
Please download the re-release of v1.1.5 and report if the problem persists.

**Comment by piotrnikov** [comment]
Hello again!
Everything (Timeline + Thumbnails) seems to be working great again!!
Thanks so much!
