### ISSUE TITLE
Pixel bar always pops up when paused

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#234]
**Describe the bug**
I just updated from 1.0.7 to the latest release, only to see that now the pixel bar pops up whenever i pause a video. I read in the release notes that this might have something to do with a setting called "auto hide pixel bar" in the preferences, however this had no effect on this behavior.

**To Reproduce**
play and pause any video

**Expected behavior**
Keeping the pixel bar hidden

**Desktop (please complete the following information):**
 - OS: Windows 11
 - mrv2 v1.1.6

**Comment by ggarra13** [comment]
Here's a beta of v1.1.7 with a bug fix for it:

Windows' .exe:
https://mega.nz/file/rDRkwA5K#A6bZwuzq_1afXu33tsguaOwXyLRsRZcqpv8qRIxHDl0

Windows' .zip:
https://mega.nz/file/2GJTRSSC#KVq98N-cfTdd4uG58B5qikgGM8Ol5D-uuQB-uu5QNeA

**Comment by ggarra13** [comment]
Linux .deb:
https://mega.nz/file/zfhSBapB#Pjr7E_u6VuNjpGxkWblDwbhxCtTTPojtiWr6Jx4inig

Linux .rpm:
https://mega.nz/file/aWh2AYzL#Xst2LjalDrxJTnCBeXup7UR6jOpyxd2ffUTwslnMXzU

Linux .tar.gz:
https://mega.nz/file/DOxmkLCK#daeoy4Lh1VhlWXgFDTZwA6BtivrMPqwTpvLKKK_HzjQ

**Comment by ggarra13** [comment]
Linux .deb:
https://mega.nz/file/rbAC1JBa#6KEPsu-azS2iA62x4_QkZteGGQsdTv9vSYZHOCqOMaA

Linux .rpm:
https://mega.nz/file/eeJVhA7T#IOdaw1SKZ2Gf-e08ZvdJ6Kljmebnx2PfWVog6eoXOO0

Linux .tar.gz:
https://mega.nz/file/vXA1zaBI#ku4PXSlApEHPPz3stPqtHZGDENk2-tmBeUDk4uq_71Y

**Comment by ggarra13** [comment]
Fixed in these betas and upcoming v1.1.7 release.
