### ISSUE TITLE
Getting pure white where alpha is 0 using v1.1.8

### ISSUE THREAD

**Issue by lucyk3d** [ggarra13/mrv2#243]
When loading any exr with alpha information the background shows as pure white which is very distracting, how can this be changed? My older version didn't do this but for some reason it still happens even when rolling back to a previous version. I'm on windows 10 version v1.1.8.

**Comment by ggarra13** [comment]
It works fine for me.  Things to check:

1) Go to Panel->Background and check that is not to Solid and White.  You probably want it transparent.
2) Go to Preferences->Language and Colors and check the color of the Background box (ie. used for Transparent).

If that's not it, let me know if the problem shows up in Normal view as well as in Presentation Mode (F12).

**Comment by lucyk3d** [comment]
The first option worked thanks so much!

**Comment by lucyk3d** [comment]
How do you save the preferences so that it's always set like that? It seems to reset each time I reload the software

**Comment by ggarra13** [comment]
It should save it automatically in the type specified when you exit the program.  I just tested and it works for me.  Isn't working for you?  Let me know the steps you use.

**Comment by lucyk3d** [comment]
Ah ok! Steps are double click on exr -> change background color in panel -> close program -> reopen program and background settings are not saved. I have also tried just opening normally in start window and repeating the same process with no luck.

**Comment by ggarra13** [comment]
I was finally able to reproduce it.  I will look into it and will provide you with a fix.

**Comment by lucyk3d** [comment]
This works for me thanks so much! Love the software btw :)
