### ISSUE TITLE
Mouse-wheel zoom depends on side panel scroll bar

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#249]
Small UX annoyance: 

I docked my "Media Information" panel to the right side of the screen.
When i hover my cursor over the panel and scroll, two things can happen:

- If the side panel displays the scroll bar, the mouse wheel will scroll the panel up and down
- If the scroll bar is hidden (for example when enough categories are collapsed) the mouse wheel will zoom in and out of the image

This feels pretty inconsistent, so i suggest disabling the image zoom when the cursor is outside of the image display area or over a panel.

**Comment by ggarra13** [comment]
Here you go for you to try (also check I spelled your name properly in the Help->About->Thanks).

.exe:
https://mega.nz/file/bPhU0BSL#Pk36ID_Hj65QN3nuSHwDfUkMs5s1ROqZl4n8VwLtnDc

.zip:
https://mega.nz/file/PKZVlQAQ#XRneZ0dqIFgBjEjuGP0OZmo11ue1Zdnm8CyPMM_rejQ

**Comment by Thane5** [comment]
There seems to be some bug where is sometimes cant scroll a panel, even if the scroll bar is displayed.

Steps to reproduce:

1. collapse all categories in media info panel
2. un-collapse them until the scrollbar appears
3. the mouse wheel will now do nothing

It seems that hovering or clicking on the scrollbar fixes it sometimes, but i'm not really sure yet what the requirements are for that to happen.

**Comment by ggarra13** [comment]
I can confirm the bug in v1.1.9, but it was always there in v1.1.8 too.  This will need some more time to fix.

**Comment by ggarra13** [comment]
Ok.  This should fix the scroll issue as well as resizing problems when the Media Info Panel was in a window.   There are still some minor redraw issues when in a window, which I can't seem to get rid of.

.exe:
https://mega.nz/file/DTAmSCoA#ScatFqUdmdzmpjkwKxGI4ng2SL0EkFACwGdfkJj2HOg

.zip:
https://mega.nz/file/2bwkDB5Y#zg0X1pgxmOrS8LiMaYlK7fruVfSJkzdxmpVtkOWUZTA

**Comment by Thane5** [comment]
Alright that version looks good now.
