### ISSUE TITLE
Load OCIO Config window bug & also a crash and ocio reverting

### ISSUE THREAD

**Issue by KonkaBass** [ggarra13/mrv2#250]
**Describe the bug**
In Preferences, OCIO menu, when click "Pick" the Load OCIO Config window appears for a tick then moves behind both the preferences and main mrv2 window. I can then drag both windows aside to see the selection window, but I can't interact with it. 
If I press "Okay" on the Preferences window, preferences window will close and the Load OCIO Config window will stay open.
I then can use the Load OCIO Config window as normal, and select the custom .ocio [in the folder copied from Blender 4.1 installation].
Now, when I open Preferences again, I can see new OCIO is selected, but the selections in both the main Color tab the Preferences OCIO Defaults menu have not updated.
If I click Okay at this point. mrv2 crashes, and on open the OCIO Config File has reset.

**okay, in the process of writing this and testing I've figured out a work around, but this is not acceptable**
If I close mrv2 after selecting the custom OCIO, the program would open then immediately crash when trying to open and EXR, but if I open with the program .exe, it will open properly, the Custom OCIO is retained, and I can go ahead and select my Default color space selections. Close the mrv2 again. And now my EXR files will open properly with the correct color space.

I'm going to be honest, after I got it working now I'm not sure why it was crashing or why EXR's wouldn't open until I opened mrv2 without a file loader.

**Expected behavior**
I just expect the Load OCIO Config window to behave normally and for selections made there to not revert.

**Desktop (please complete the following information):**
Windows 10  v10.0.19045 Build 19045
mrv2 v1.1.8

**Additional context**
Doing this since Blender updated to 4.1 and has utilized a new color space called AGX, I've moved to exporting in that space to support HDR in my renders. So I updated to 1.1.8, from v0.7.1, and tried the same process of copying the _entire ocio folder_ in the blender installation into the mrv2 folder.

**Comment by ggarra13** [comment]
I can reproduce the bug.  You can also work around it if you select to use the Native File Chooser  (Window->Preferences->User Interface->File Requester).

**Comment by ggarra13** [comment]
Here's a beta of v1.1.9 that should fix the issue:

.exe:
https://mega.nz/file/LD5ywIoC#_XJgv6P9QiPFzEtrP_b57i76Mu-j7iKwHITrbu_iEkk

.zip:
https://mega.nz/file/Xa4g2ITQ#pTm--vyoBxYhC_HBTmm7BylCLl2dLSenOR0iEyJ7ueU
