### ISSUE TITLE
The Ability to Specify Image Sequence Frame Range

### ISSUE THREAD

**Issue by jlapreviz** [ggarra13/mrv2#261]
Firstly, thank you for creating MRV2. It's amazing!

I searched the MRV2 documentation and could not find any reference to the ability to specify an image sequence frame range.
It would be helpful to be able to launch mrv2 on the linux command line with a specified image sequence, start frame and end frame.
This could be implemented as command line options.
e.g. to start on frame 100 and end on frame 200, with an EXR image sequence that's padded to 5 digits:
`mrv2 -s 100 -e 200 myImageSequence.#####.exr`
Alternatively, it could be specified as part of the image sequence character string itself:
`mrv2 myImageSequence.#####.exr[100-200]`

**Comment by ggarra13** [comment]
You can already do it, but it is a tad less intuitive as it uses OpentimelineIO time ranges, like:

mrv2 -inOutRange start/end/fps yourseq.0001.exr

For example (in your example this should work):

mrv2 -inOutRange 100/200/30 yourseq.0001.exr

**Comment by syntheticperson** [comment]
That works.
In that case, could you add documentation to the --help command line option?
Could you also point me to the OpenTimelineIO documentation that describes this in detail?
Thanks

**Comment by ggarra13** [comment]
> In that case, could you add documentation to the --help command line option?

I'll try to remember to add it.

> Could you also point me to the OpenTimelineIO documentation that describes this in detail?

Sadly, the OpenTimelineIO documentation is, shall we say, very sparse and orientated towards programers.  You really need to see the printout of TimeRange in C++ or in Python code.

https://opentimelineio.readthedocs.io/en/stable/tutorials/otio-serialized-schema-only-fields.html#timerange-1

**Comment by syntheticperson** [comment]
Cool.
Lol.
How do I mark this feature request as closed?
Thanks again.

**Comment by ggarra13** [comment]
> How do I mark this feature request as closed?

At the bottom of the Add comment section there should be a "Close Issue" button.  If you start typing, there should be another button that says "Close with comment".

**Comment by syntheticperson** [comment]
I'm only seeing a Comment button, not "Close with comment".
<img width="803" alt="Screenshot 2024-07-09 at 2 37 56 PM" src="https://github.com/ggarra13/mrv2/assets/119148/78746815-c2ba-472f-b338-b1319ab9a95e">
Can you close this issue for me?
Thanks
