### ISSUE TITLE
Step through collection of unrelated images

### ISSUE THREAD

**Issue by jlapreviz** [ggarra13/mrv2#263]
I have a collection of historic photographs that have been scanned with the following naming convention:
```
SS119_Davidson_Bx24Fr2_N18728_back.tif
MSS119_Davidson_Bx24Fr2_N18728_front.tif
MSS119_Davidson_Bx24Fr2_N19450_back.tif
MSS119_Davidson_Bx24Fr2_N19450_front.tif
```
I'd like to be able to load them into MRV2 and step through them.
I've tried loading them as individual frames. MRV2 does appear to load them all, but I can't figure out how to step through them.
Greater than and less than <> don't work. Page up and page down don't work either.
What am I mssing?
Thanks

**Comment by ggarra13** [comment]
Sadly, you are not missing anything.  The hotkeys should be PageUp and PageDown but they are not active currently.  You can only switch from one image to the next if you open the Files Panel and click on the <- -> arrow buttons.

**Comment by ggarra13** [comment]
Here are new v1.2.2 builds:

Linux .deb:
https://mega.nz/file/GaYkFTgI#Djgz0EGY8iwPXQcyTE8TS7voN728UEKnn7wXGsPlf6w

Linux .rpm
https://mega.nz/file/iOZTHYYK#q80w3nUAB1ZKwRFunRH2CzlMkVGHoGg152FxpC680Dw

Linux .tar.gz:
https://mega.nz/file/fG5hFRzT#TWAyovQVv-XVAXJmc3fX3Mi7-xL1L7QnpD5NIFmNkp0

Windows .exe:
https://mega.nz/file/3GRykTQS#DK7-E1bbtrOY12MJWzQJaOljsE8d5JfCsaCQdLnk4Uo

Windows .zip:
https://mega.nz/file/ebJE3ThJ#AqAwpCzo4ldProIM_u8DoBnMim1e2kEYUDyVJ8zzsk4

**Comment by ggarra13** [comment]
I've re-relased v1.2.1 with the addition of Image/Next and Image/Previous (PgUp/PgDown).  You can download it from github.  To close the issue, you will need to be logged in.

**Comment by jlapreviz** [comment]
Many thanks!
