### ISSUE TITLE
scrub with LMB - stop when mouse stops

### ISSUE THREAD

**Issue by michalfratczak** [ggarra13/mrv2#266]
Is it possible to configure ScrubbingTool so that the playback stops when the mouse stops?
Currently the playback continues unless I lift mouse button.

**Comment by ggarra13** [comment]
This was fixed in v1.2.1 released today.  If it does not work for you or you don't want to upgrade due to some other bug, please report it.

**Comment by ggarra13** [comment]
NOTE: for it to work, you need to have started scrubbing from a Stop position in the first place.  Otherwise, the playback will continue.

**Comment by ggarra13** [comment]
For more info, see: https://github.com/ggarra13/mrv2/issues/260

**Comment by michalfratczak** [comment]
I can confirm this works OK now! Thank you !
