### ISSUE TITLE
EXR maultilayer next/previous channel hotkeys not working

### ISSUE THREAD

**Issue by AltaArts** [ggarra13/mrv2#267]
**Describe the bug**
By default, the hotkeys for next channel and previous channel (of multilayer exr's) are mapped, but do not seem to be working.

**To Reproduce**
Load a multi layer .exr image.  Change the displayed layer using the UI button in the TopBar, and the layer changes correctly.  Then try and use the default "[" and "]" does not work.

I tried mapping the action to different key-bindings, but that did not work either.  I have not tried mutlipart exrs.

**Expected behavior**
The layer (channel) will change using the hotkeys.

**Desktop (please complete the following information):**
Win10 using the latest release .exr installer (mrv2 64 bits - v1.2.1 - Built Jul 12 2024 06:53:52)

**Comment by ggarra13** [comment]
I confirm the bug and have a fix for it already in place for v1.2.2.

**Comment by ggarra13** [comment]
You can try the beta at:

https://sourceforge.net/projects/mrv2/files/beta/

**Comment by AltaArts** [comment]
Got the beta, and can confirm it works.  Thanks so much!

Do you want me to close this, or leave it open until the release?

**Comment by ggarra13** [comment]
I am closing it.  Thanks.
