### ISSUE TITLE
Option to Disable Allways on Top

### ISSUE THREAD

**Issue by jlapreviz** [ggarra13/mrv2#269]
The current version of MRV2 for Linux always pushes itself in front of other windows. This can be annoying when I'm trying to compare information between a browser, terminal shell, and MRV2.
This is the default behavior of the `mplay` utility included with SideFX Houdini. However, they do provide the option to disable Always on Top in preferences
Please add an option in preferences to disable Always on Top in MRV2.
thanks

**Comment by ggarra13** [comment]
mrv2 has an Always on Top feature already in Window->Float On Top.  The default behavior for that setting is set in Window->Preferences->User Interface->Always on Top.   That setting keeps the Window above all others, regardless of what you do.

However, most likely the behavior you are seeing is your Window Manager (GNOME, etc) misbehaving.  Basically, when mrv2 gives the keyboard focus as you enter the view window.  Unfortunately, most Window Managers these days incorrectly, imo, automatically raise the window to the top.  I can basically turn off the keyboard focus for the window, which means it would not raise to the top, but you would have to click on the view window to have keyboard shortcuts accepted again.

Is that acceptable behavior?  Is that how mplay works, or do they do something else?
