### ISSUE TITLE
The Ability to Reload Frame(s)

### ISSUE THREAD

**Issue by jlapreviz** [ggarra13/mrv2#270]
One of the features I like in Autodesk RV is the ability to reload a frame after re-rendering/comping without having to exit and relaunch RV,
I looked through the MRV2 menus and also tried the RV hot key "shift r", but that's mapped to the rectangle shape in MRV2.
Could you add the ability to reload the frame where the play-head is positioned?
Thanks\

**Comment by ggarra13** [comment]
I believe Timeline->Cache->Update Frame (Shift+U) should do what you want.

**Comment by jlapreviz** [comment]
Thanks.
I also found that if you right mouse over the image sequence in the Files window, you can select File->Refresh cache, which appears to reload all files.
![MRV2_File_RefreshCache v02](https://github.com/user-attachments/assets/1f65f9b0-d7b3-47b8-8bb6-68f5c112517d)
