### ISSUE TITLE
Installing mrv2 breaks theming in Pop!_OS.

### ISSUE THREAD

**Issue by fusion-9** [ggarra13/mrv2#271]
**Describe the bug**
The installation somehow breaks theming completely, I track it down to the process gsd-xsettings stopping to work and initialize all-together, trying to execute the process manually prompts you with the error shown in the attached screenshot.

This happened to me several times until I was able to figure out the root cause, don't exactly know how or why it happens but installing Mrv2 1.2 causes this issue, the screenshot is from a virtual-machine with fresh Pop! installed that I was using to figure out what was breaking the theming.

**To Reproduce**
Install Mrv2 1.2

**Expected behavior**
No problems..

**Screenshots**
![mrv2_01](https://github.com/user-attachments/assets/a41fa818-6a91-4d61-89fd-1357a12ecf68)

**Desktop (please complete the following information):**
 - OS: POP!_OS
 - Version 22.02LTS

**Comment by ggarra13** [comment]
First, are you running under Wayland or X11?  I would expect the issue to happen with Wayland, but not X11.

mrv2 patches:

`/usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.xml `

as it would create problems on Ubuntu 22.04 LTS with Wayland.

You should be able to find the original non-patched file as, I believe:

` /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.xml.orig.mrv2`
 
See if replacing it back fixes the issue and I will remove the patching from the installer.

When installing from dpkg or rpm, you should have gotten the warnings about it, like:

"Deprecated antialiasing found in $file"
"Must patch for newer Wayland."

Also, when you answer, please attach the orig.mrv2 non-patched file so I can compare it to Ubuntu's.

**Comment by fusion-9** [comment]
I'm running X11 but I did a refresh install since I couldn't fix the issue back then but the VM is giving me the error so I can try this, I'll come back with some updates soon.

**Comment by ggarra13** [comment]
I've updated the installer.   You can try downloading the latest v1.2.2 beta from:

https://sourceforge.net/projects/mrv2/files/beta/
