### ISSUE TITLE
adding audio to an image sequence

### ISSUE THREAD

**Issue by verstaerkermusic** [ggarra13/mrv2#272]
**Is your feature request related to a problem? Please describe.**

i'm trying to open an image sequence, add the audio and save it as movie-file 
but i'm failing to add the audio - so this might be a bug report 

i'f i just drag the audio into mrv i get the error message 

```
WARN : [ffmpeg] (wav) Could not find codec parameters for stream 1 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
ERROR: [] /Users/xyz/Projekte/Video/2024/zzz/myfile.wav: /Users/xyz/Projekte/Video/2024/zzz/myfile.wav: No video codec found
```

if i use the "open with seperate audio"  function i get this
```
`ERROR: [] /Users/xyz/Projekte/Grafik/3D/Blender/2024/render/zzz/zzz/v003/myFile.wav: /Users/xyz/Projekte/Grafik/3D/Blender/2024/render/zzz/zzz/v003/myFile.wav: No such file or directory`
```
wich is interesting as this is the path to image-sequence.. the audio file is not there

**Describe the solution you'd like**
preferably i'd be able to open the image sequence via drag n drop and then just drag n drop the audio 

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by ggarra13** [comment]
Unfortunately, you cannot drag the audio, as you found out.

You have to use the "Open with separate audio" or the "-a <audio_file>" from the command-line.

But indeed these were broken.  You can find a fix in v1.2.2 at:

https://sourceforge.net/projects/mrv2/files/beta/

**Comment by verstaerkermusic** [comment]
i hate to say it but it still seems broken 

i used 1.2.2 and the "Open with separate audio" .. set the .png sequence for video and the .wav as audio 

```
WARN : [ffmpeg] (wav) Could not find codec parameters for stream 1 (Video: png, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
ERROR: [] /Users/xyz/Projekte/Video/2024/fortklang/fortklang_Angst24-48.wav: /Users/xyz/Projekte/Video/2024/fortklang/fortklang_Angst24-48.wav: No video codec found
ERROR: [] //Users/xyz/Projekte/Video/2024/fortklang/fortklang_Angst24-48.wav: //Users/xyz/Projekte/Video/2024/fortklang/fortklang_Angst24-48.wav: No video codec found
```

**Comment by ggarra13** [comment]
It is working for me.  It seems in your case the .wav file is being loaded as video for some reason.
Can you upload one .png of your sequence and the .wav file to some place on the cloud and post the link to them?

**Comment by verstaerkermusic** [comment]
hi.. sorry for the delay
here's a short png sequence and the .wav  - let me know when you downloaded it, so i can erase it
https://e.pcloud.link/publink/show?code=XZ1SSgZOLNRPV0MoX8Te5L3Lz8t2bBTUPHV

**Comment by ggarra13** [comment]
You can delete it now.

**Comment by ggarra13** [comment]
@verstaerkermusic I understand what is happening.  Your .wav file contains an embedded PNG image and mrv2 expects only audio tracks.  The option in FFmpeg (the video library mrv2 uses) to support embedded images is by default turned off as it is really a corner case and makes compiling it slower.  So, at this moment in time, I am going to label this issue as won't fix.

You can get a working .wav file if you:

a) Save out a .wav file without a PNG image.
b) Extract the .wav file alone with ffmpeg, like (on the terminal):

```
brew install ffmpeg
ffmpeg -i fortklang_Angst24-48.wav -c:v none -c:a copy fixed.wav
```

**Comment by ggarra13** [comment]
Actually, I found a way to support the .wav file with embedded PNGs, except for the warnings.  
It will be there on v1.2.2.  Now it is compiling the beta builds.  Once it finishes (about an hour or so), you will find it at:

https://sourceforge.net/projects/mrv2/files/beta/
