### ISSUE TITLE
importing image sequence starts only at fr 1000 

### ISSUE THREAD

**Issue by verstaerkermusic** [ggarra13/mrv2#273]
**Describe the bug**
i have a image-sequence from 0990 to 1010 
the files are named file.0990.png to file.1010.png
when import that sequence it only goes from 1000 to 1010 
 
**To Reproduce**
1. Go to File->Open->Movie or Sequence
2. go to a sequence with this range (0999 to 1001 is good enough to test)
3. check timeline .. you'll only get from 1000 to 1001 
4. even manually setting it to start 999 doesn't help

**Expected behavior**
open full image-sequence .. it should work correctly even with variable sequence # ... 999 - 1001 should work as well as 0999 to 1001

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Version mrv2 v1.2.1]

**Additional context**
i just realized if i remove the leading 0 it works
it'S true for all leading 0 , so also with a sequence from 09 to 11

**Comment by ggarra13** [comment]
I confirm the bug and put a fix for v1.2.2.  You can try it from:

https://sourceforge.net/projects/mrv2/files/beta/

**Comment by verstaerkermusic** [comment]
thank you thats fixed in 1.2.2
