### ISSUE TITLE
Fullscreen mode always moves mrv2 to primary display

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#276]
**Describe the bug**
When using mrv2 on a secodary display, pressing F11 or F12 will move the window back to display 1. Leaving any of the fullscreen modes will move the window back to where it was.

**Expected behavior**
mrv2 should enter fullscreen mode on the same window that it is currently on.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. mrv2 v1.2.1]

**Comment by Thane5** [comment]
Somewhat related: Is there an option to open mrv2 in fullscreen?

**Comment by ggarra13** [comment]
Yes.  Windows->Preferences->User Interface.

Under Window Behavior, to the right, you have "Normal" (default), "Fullscreen" and "Presentation".

**Comment by Thane5** [comment]
How about a "maximised window" mode though?

**Comment by ggarra13** [comment]
What do you mean exactly by "maximised window"?  Isn't that what Fullscreen/Presentation do?  What would be the difference?

**Comment by Thane5** [comment]
i mean that instead of beeig a floating window, the window is in its maximised state. The same state that it goes in when you click the rectangle in the top right corner of every Windows window.
![image](https://github.com/user-attachments/assets/b9d997a6-3da3-4071-8045-7a4968521afe)

**Comment by ggarra13** [comment]
Can you verify v1.2.2's Window->Preferences->Maximize does what you want?

**Comment by Thane5** [comment]
Yep, that does work. Though it currently says "Maximizado" in the preferences, but i am using the english version.

**Comment by ggarra13** [comment]
Thanks.  I'll fix it.
