### ISSUE TITLE
Option to disable scrub-looping

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#277]
**Is your feature request related to a problem? Please describe.**
Beeing able to scrub back and forth by moving the mouse on screen is my favorite thing about mrv2. However, if you scrub beyond the end of a video, it will simply loop back to the start of the video. This can be quite useful, but there are cases where i would prefer to not have this behavior and instead lock the scrubbing range to the start and end of the video.

**Describe the solution you'd like**
Either introduce a new setting to disable/enable scrub looping (_preferred solution_), or disable it when "Looping Mode" is set to "Stop".

**Comment by ggarra13** [comment]
Try these new v1.2.2 betas which should fix both the scrub behavior (when loop is off) and some fullscreen/presentation issues:

.exe:
https://mega.nz/file/yeY0mbiL#DlWmaGGPKb58JOpEOrDRfiumvW_U1HranRrK5CASkNU

.zip:
https://mega.nz/file/fK5k2R5S#3sYCKj6fay3lRdHOhIbWUU3U3ilWtV7CbM52TsiENuc

**Comment by Thane5** [comment]
Works beautifully! Both problems solved then.
