### ISSUE TITLE
mrv2 does not start

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#278]
**Describe the bug**
I am on a new (kinda old) PC that i freshly installed windows on, and it mrv2 simply will not start.

**To Reproduce**
1. Go to my place to pick up my computer
2. Start my computer up
3. Double click on the mrv2 executable on my computer

**Expected behavior**
to not not run

**Screenshots**
here is a screenshot of mrv2 not running on my computer
![image](https://github.com/user-attachments/assets/cbf6422e-5ee7-4ff4-8f63-a2930bc44cb0)

**Desktop (please complete the following information):**
-  Its a PC with an Intel Broadwell i5 5675c with integrated iris Pro graphics. I installed Windows 11.
- tested with latest mrv2 1.2.1

**Additional context**
It's no big deal if this cant get fixed because this is not my primary PC setup, but i am open to do some troubleshooting.

**Comment by ggarra13** [comment]
Can you try downloading and installing the beta of v1.2.2 from sourceforge?

https://sourceforge.net/projects/mrv2/files/beta/mrv2-beta-Windows-amd64.exe/download

If it is crashing, it should output a crash.log file to %TMP%, usually:

`C:\Users\<username>\AppData\Local\Temp`

**Comment by Thane5** [comment]
I could not find any crash logs in my temp folder. But that beta build works.
