### ISSUE TITLE
Installer - Program version and platform not showed on top left

### ISSUE THREAD

**Issue by bovirus** [ggarra13/mrv2#281]
@ggarra13 

**Describe the bug**

The NSIS installer script don't contain info to show on top left the program version to install and platform

**To Reproduce**
1. Riun the installer
2. Check on top left after program name

**Expected behavior**
Modify the NSIS script to show on top left after program name the program version and platform (32bit or 64bit)

**Screenshots**

![image](https://github.com/user-attachments/assets/58b965c5-76c0-4114-a0b9-dbd4f6f2ab63)

**Desktop (please complete the following information):**
 - OS: Windows 10 22 h2 64 bit Italian
 - Version 1.2.2 64bit

**Additional context**

**Comment by ggarra13** [comment]
Fixed in v1.2.3 currently in beta.
