### ISSUE TITLE
Suggestions for modifying the default icon.

### ISSUE THREAD

**Issue by JomW** [ggarra13/mrv2#282]
This is a fantastic software, and I appreciate the author's active maintenance. 
I have a small suggestion: could the default software icon be changed, or could dedicated icons be created for different formats (Maybe i can provide artistic support)? The current icon is a bit scary; I mean, when I open a folder, those eyes look a bit frightening. This is just my personal feeling. I don't want to affect your development progress, and I apologize for this very subjective and selfish request. I would be very grateful if you could consider it.

![QQ20240807-234352](https://github.com/user-attachments/assets/e53e3c11-9a40-42a2-881f-eb8850a84f6c)

**Comment by AltaArts** [comment]
I humbly agree.  It is striking, but also looks a bit odd when somebody is looking over your shoulder.

I would like something like the existing, but maybe just outline strokes of an abstract eye over alpha.

**Comment by JomW** [comment]
Thank you for your response. I agree that abstraction is a wonderful choice. 
From a psychological perspective, abstract styles do not convey very concrete emotions through the eyes. 
Flat or illustrative styles might also achieve a similar effect. 
If you need my help with creative design, please feel free to leave your email, and I will send you the draft once it’s ready. Currently, this service is free, and I hope this request does not put any pressure on you. 
Additionally, AIGC is also a good option.

**Comment by ggarra13** [comment]
Thank you for your comments.  You can avoid seeing the ugly icon if you use mrv2's custom file requester instead of relying on Windows Explorer.
Regarding the icon, if you can provide me with an .svg drawing of it, you can send it to ggarra13@gmail.com.

**Comment by Thane5** [comment]
Hi, i also had some designs in mind when reading this issue. They are are bit more modern, and clearly inspired by current Windows 11 App icons – but i think this is a good direction for mrv2 to go in.

If you want any more variations or suggest something on these icons, just shoot it out. 

![image](https://github.com/user-attachments/assets/1dcb06ca-92da-4ecf-b51e-2036b3d396ee)

**Comment by JomW** [comment]
![image](https://github.com/user-attachments/assets/b9d69bd7-9c63-45db-931e-49d8cd75e725)
![eye_icon](https://github.com/user-attachments/assets/9790f6f8-73c2-4eec-af0d-00aac073b77d)

I designed an icon, sorry it took some time, my graphic design skills still need improvement. This is an SVG file, you can open it in AI or a browser.

**Comment by ggarra13** [comment]
@JomW  Your icon is very similar to mrv2's original icon and I think it would not be much of an improvement.
@AltaArts Sent me two icons privately which are similar to the mrv2 icon currently in beta, which, after trying it, I don't fancy it much.
@Thane5  Your design of Icon_02 is BY FAR my preferred icon.  It is elegant and the pupil as a play button conveys mrv2's use rather well.  It also sits well with both Windows 11 and its rounded design works with macOS too.  Contact me privately with the details (.svg file or large .png file, etc).  If you want compensation for it, I would need to know how much and whether you have a Paypal account.

**Comment by AltaArts** [comment]
I agree, Thane5's look like they will work well!  Nice!

**Comment by Thane5** [comment]
Glad you like them. 
Here you have an archive with the final version as an SVG, PNG, and my Affinity Designer file:  [Export.zip](https://github.com/user-attachments/files/16618551/Export.zip)

![mrv2_icon_02](https://github.com/user-attachments/assets/1681a87d-3c7f-4fe1-9aa4-6354b8b8f3cd)

(No money needed, i'm just doing my part at making this free software even better.)

**Comment by Thane5** [comment]
here is a slightly revised version. with the corner readius matching that of other macOS apps. The PNG now also has a dropshadow from Apple's design templates, which their app icons apparently need. 
[mrv2_Icon.zip](https://github.com/user-attachments/files/16622838/mrv2_Icon.zip)

**Comment by AltaArts** [comment]
I just updated to 1.2.3 and congrats!  The icons look great and work well!

Nicely done @Thane5  and @ggarra13!

**Comment by Thane5** [comment]
I noticed that the last icon looks too small on Windows.  Therefore i made seperate png for Windows, without the shadow and no transparent border.
[mrv2_icon.zip](https://github.com/user-attachments/files/16634409/mrv2_icon.zip)


Can you define seperate icons per platform, or do they all just use one shared icon? In case thats not possible, it would probably make sense to use the windows icon globally. Though i would like to see a screenshot from a mac user to make sure it does not look bad.

**Comment by ggarra13** [comment]
> Though i would like to see a screenshot from a mac user to make sure it does not look bad.

Here's how it looks on the macOS dock with the original design.  To me it looks great!

![Dock](https://github.com/user-attachments/assets/8ab83b5b-603a-499c-925d-ad7821374121)

**Comment by Thane5** [comment]
Good to hear it looks as expected. 

Unfortunately the Mac icon looks kind of tiny on the Windows 11 taskbar. Here it is to the left of the windows icon:
![image](https://github.com/user-attachments/assets/8d765c1a-79ab-4f02-8b4e-f34236a0ec16)

**Comment by ggarra13** [comment]
On my Windows 11 Pro machine, it looks the same size as most other icons:

![Captura de pantalla 2024-08-17 095328](https://github.com/user-attachments/assets/b4382979-3a0e-4e83-8b4e-02f24ae7491f)

**Comment by ggarra13** [comment]
Weird...  v1.2.4 that I just installed for testing and used for setting the file associations looks small.  The previous version (v1.2.3 no longer with file associations) looks fine.  Recent Files associated to it also look small.  But on Explorer, where I used Windows' Photo Associations first and then mrv2 associations again to get preview pictures all looks fine.

![image](https://github.com/user-attachments/assets/964707b1-7629-4596-9344-ad411f0a960a)

Something in Windows or in my installer is doing some funky stuff....

**Comment by Thane5** [comment]
Btw are you able to define a "File type" icon for this program? Many programs have specific icons that are different from the program icon, when a file is associated with that program but has no thumbnail image. Most of the Adobe apps do this, like Photoshop but also Acrobat
![image](https://github.com/user-attachments/assets/852649b9-fbf4-4e72-b511-5bc839813480)

**Comment by ggarra13** [comment]
Okay.  I fixed the Windows resize issue, which was tricky as Windows 11 Pro kept caching the thumbnails making me think it was not working.  
Regarding different file types for different extensions, I am afraid I will not do it.  Doing so involves using COM (a technology that I think even Microsoft no longer uses) and it is really ugly code.
What I suggest, if you have Windows 11 Pro is to take advantage of the Windows Photo utility (as documented in mrv2's docs), which will show a thumbnail of most images/movies but still open it with mrv2.  See the mrv2 FAQ - Windows.

**Comment by ggarra13** [comment]
Fixed in v1.2.4 beta.  Closing the issue.
