### ISSUE TITLE
Stuttering playback depending on mouse position

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#29]
Stupid title and maybe not reproducible on every OS / hardware. But here goes:

I noticed that with higher resolution image sequences I get stuttering playback despite of a sufficient RAM cache WHEN (and only when) the mouse pointer is over the viewer and mrv2's color picker is showing a color.
As soon as I move the mouse pointer away from the area where the sequence is shown on screen all is smooth. Same goes if I press F12 to go to fullscreen: everything is playing back nicely.
It looks like the color picker / display is causing a delay somehow?

It's not happening with 1920x1080 sequences on my hardware, so I attached a very simple image sequence to hopefully reproduce the problem: https://1drv.ms/u/s!AlOpRG0iPvzdhKMZuZBy9KfbkZYk6w?e=6hXCI9

Just play it back and move the mouse over the image -> it stutters. Move the mouse anywhere else so the color picker doesn't pick up anything -> smooth playback.

**Comment by ggarra13** [comment]
I can reproduce it on my NVidia GTX 3080 (albeit not a dramatic stutter).

This is probably the limitation of OpenGL on most gamer cards.  For reading the pixel color values, it is necesary to bring the color transformed (OCIO, gamma, gain, etc) image from the graphics card onto the CPU RAM and that takes time with 4K or higher images.   The solution is to temporarily hide the color picker ( F2 ) when playing 4K or higher sequences (or go full screen like you did).

The other solution is to switch to pixel color values without OCIO transform by switching from Full Mode to Original Mode on the pixel color bar (the F / O menu button in the middle of the pixel bar.  That of course will display the pixel color values as they are in the OpenEXR image and not the transformed pixel values (with LUT, Gamma, OCIO, etc).  You can also set it forever in the Preferences window if you don't care about the color transformed pixel values.

**Comment by ggarra13** [comment]
>


> The other solution is to switch to pixel color values without OCIO transform by switching from Full Mode to Original Mode

Which I just found out it is not working properly.  I'll have to fix this.

**Comment by SteffenDuenner** [comment]
I could totally live with a hidden or inactive color picker during real time playback. One can't read the display of the color picker during playback anyway. To me at least it's much more important to be able to play back and review at a consistent frame rate. But that's just me ;)

**Comment by ggarra13** [comment]
You can hide it forever if you uncheck Window->Preferences->User Interface->Pixel Toolbar.
BTW, I fixed the Oriignal Mode of pixel color lookup.  I was not taking anamorphic content into account,
