### ISSUE TITLE
Save movie failed

### ISSUE THREAD

**Issue by Insecty** [ggarra13/mrv2#290]
**Describe the bug**
I download the prebuilt version of mrv2 in this link: https://github.com/ggarra13/mrv2/releases/download/v1.2.4/mrv2-v1.2.4-Windows-amd64.zip
Firstly, i tried some main features, this tool is really easy to use and can help our art pipeline a lot.

When i try to export video with some annotations, it failed since all the frames are black , no pixel color at all....

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version mrv2 v1.2.4

![image](https://github.com/user-attachments/assets/1010d3d7-6759-452f-871a-167312f57899)
![image](https://github.com/user-attachments/assets/76b4716d-6034-4bc7-9346-d6da98151905)
Results:
![image](https://github.com/user-attachments/assets/0db59710-94fc-40af-b951-f0e5fe3cee55)

**Comment by ggarra13** [comment]
First, download this beta of v1.2.5 and see if it fixes the issue:

.exe:
https://mega.nz/file/SOYyzAaB#kRQSO_dsnLxwSpd9neGkzahiNtfdnW41gW_cl40Es5k

.zip:
https://mega.nz/file/XOIjBJqY#JGLQ3-qJEor_P_pOOIpqWZ994dneFAHwdUpYv9T2ATY

If not, try:

1) Saving without annotations.  What happens?
2) Saving with a different profile, like "None"?

**Comment by Insecty** [comment]
> First, download this **new** beta of v1.2.5 and see if it fixes the issue:
> 
> .exe: https://mega.nz/file/WagnRTzC#kPlt9BYtx5u5LUJYbeATS9zH1aBOnrjMvhT-gzD7fVg
> 
> .zip: https://mega.nz/file/WKw3CSpC#q2fKUgaoMQZHS-xGmjlOzzmKcFpVXV-V1fvaafLlqHQ
> 
> If not, try:
> 
> 1. Saving without annotations.  What happens?
> 2. Saving with a different profile, like "None"?

**Comment by Insecty** [comment]
> @Insecty I noticed you closed and reopened the issue. Is the problem still present in v1.2.5 linked above? Did you try the other things I suggested? Can you provide a sample movie where it fails?

Sorry, i clicked the wrong button this morning, but I just verified the latest version v1.2.5, and this issue has been fixed. I think i can close this issue now. Thank you !  :)
