### ISSUE TITLE
crashing on sequoia beta

### ISSUE THREAD

**Issue by srinivasdotc** [ggarra13/mrv2#297]
when I open the app, it is crashing, with the below error.

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/mesa/lib/libGL.1.dylib
Referenced from: <0ECD963C-3A8F-38D5-978C-E427502C4EDA> /Applications/mrv2.app/Contents/Resources/bin/mrv2
Reason: tried: '/Applications/mrv2.app/Contents/Resources//lib/libGL.1.dylib' (no such file), '/libGL.1.dylib' (no such file), '/usr/local/opt/mesa/lib/libGL.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/mesa/lib/libGL.1.dylib' (no such file), '/usr/local/opt/mesa/lib/libGL.1.dylib' (no such file), '/Applications/mrv2.app/Contents/Resources//lib/libGL.1.dylib' (no such file)
(terminated at launch; ignore backtrace)

**Desktop (please complete the following information):**
 - OS: Sequoia Beta 6
 - Version MRV2 1.2.5 Darwin amd64

**Comment by ggarra13** [comment]
I mistakenly misconfigured my macOS Intel machine and lead to a bad compilation with the mesa libraries.

Please download again mrv2 v1.2.5 macOS amd64 from either github or sourceforge.

**Comment by srinivasdotc** [comment]
Thank you. Even 1.2.4 has same issue.

**Comment by ggarra13** [comment]
> Thank you. Even 1.2.4 has same issue.

Oh well.  I am sorry that noone reported this previously.

**Comment by srinivasdotc** [comment]
Tried the updated version and got this error. This time with a different path to library.

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/X11/*/libGL.1.dylib
Referenced from: <F8FDD5F0-5771-360C-A657-81C1CB367D2C> /Applications/mrv2.app/Contents/Resources/bin/mrv2
Reason: tried: '/Applications/mrv2.app/Contents/Resources//lib/libGL.1.dylib' (no such file), '/libGL.1.dylib' (no such file), '/opt/X11/*/libGL.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/*/libGL.1.dylib' (no such file), '/opt/X11/*/libGL.1.dylib' (no such file), '/Applications/mrv2.app/Contents/Resources//lib/libGL.1.dylib' (no such file)
(terminated at launch; ignore backtrace)

**Comment by ggarra13** [comment]
Please try this beta of v1.2.6.  I will be fixing v1.2.5 and v1.2.4 afterwards:

https://mega.nz/file/SHhEBC5I#MUyfvVW9gLXhqwBMLNEg_SCfF9-0gWgiZMqI_bDDuRw

**Comment by ggarra13** [comment]
I've update v1.2.4 and v1.2.5.  They should all be fine now.

**Comment by srinivasdotc** [comment]
beta 1.2.6 is working. Thank you.
