### ISSUE TITLE
Automated OCIO settings

### ISSUE THREAD

**Issue by lukas-remis** [ggarra13/mrv2#299]
Hi,

I'm trying to pass Input color space and OCIO Display/View settings to mrv2 with ENV variables from Nuke, but it doesn't seem to work. It seems I'm able to pass the the OCIO Display/View with OCIO_ACTIVE_DISPLAYS and OCIO_ACTIVE_VIEWS, but still the OCIO Display/View is set to None (although the correct option is on the list and it needs to be selected manually). 

Also, is there a ENV variable that would control the Input Color Space setting?

**Comment by ggarra13** [comment]
There used to be but I took it out in a recent version.  However, tou can use the command-line for it, with:

mrv2 -ics "<ICS>" -od "<Display"> [-ov "<View>"]

[ what is in brackets is optional]

You can also set the values in the UI in Window->Preferences->OCIO Defaults.

If you really need an environment variable, let me know exactly how Nuke handles it and I'll add it for the next version.

**Comment by lukas-remis** [comment]
Ohh, nice. Let me try the command line parameters then. It doesn't have to be ENV variables. 
Can the OCIO config also be passed using command line ?

**Comment by ggarra13** [comment]
Currently not.   But you can use the OCIO environment variable for it.

**Comment by lukas-remis** [comment]
So an example command should be: mrv2 -ics "linear" -od "rec709" ?
Cause I'm getting an error: ERROR: [app] Filename '-ics linear -od rec709; does not exist or does not have read permissions.

Also, is seems that the new mrv2 version (v1.2.6) has an error, and the OCIO Display/View list can't be changed to anything else than "None". It was working fine in v1.2.5. I'm on Ubuntu 20.04

**Comment by ggarra13** [comment]
It's working for me.  It seems you have a quoting issue, as you are passing all '-ics linear -od rec709' as a single string.

Go to the console and with the studio config, try:

mrv2-v1.2.6 -ics 'scene_linear' -od 'sRGB - Display'

**Comment by lukas-remis** [comment]
![Zrzut ekranu z 2024-09-09 12-42-58](https://github.com/user-attachments/assets/6b34ee99-8cd9-43a2-9026-5313d92ecd9b)
Here the parameters are passed with correct quoting I think, but mrv2 still complaining about it, although it correctly loads the footage.
The full command is:
/usr/bin/mrv2 -ics 'scene_linear' -od 'rec709' /VFX/KQ/shots/KQ_SC013b_S001/export/KQ_SC013b_S001_comp_v004/KQ_SC013b_S001_comp_v004.1001.exr

**Comment by ggarra13** [comment]
It works for me.  Do this exactly (copy and paste):

```
export OCIO=/usr/local/mrv2-v1.2.6-Linux-64/ocio/cg-config/cg-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio
cd /VFX/KQ/shots/KQ_SC013b_S001/export/KQ_SC013b_S001_comp_v004/
/usr/bin/mrv2 -ics 'scene_linear' -od 'sRGB - Display' KQ_SC013b_S001_comp_v004.1001.exr
```

**Comment by lukas-remis** [comment]
Alright, this works correctly from command line - thank you! However if I switch the OCIO to nuke-deault then mrv2 doesn't allow to change the OCIO Display/View setting.
And I need to further investigate, cause I'm trying to launch mrv2 from Nuke, and there the same command is causing that "ERROR: [app] Filename..." error.

**Comment by ggarra13** [comment]
Here's with the nuke-default:

```
export OCIO=/usr/local/mrv2-v1.2.6-Linux-64/ocio/nuke-default/config.ocio 
/usr/bin/mrv2 -ics 'scene_linear' -od 'default' -ov 'rec709'
```

**Comment by ggarra13** [comment]
I think you might need to use backslashes on the quotes in Nuke to avoid getting parsed differently.

**Comment by ggarra13** [comment]
Here's a beta of v1.2.7 that should fix the nuke-default config issue:

.deb:
https://mega.nz/file/GPglUJbC#n-56m9fXCyEXIrpTQViq222nyyiOy5wLiwLCEDn4yPE

.rpm:
https://mega.nz/file/XegW1B5T#FHpJKl65Aez1rNVPsIG6FBZDs70Hs-slfqrCzLnafLo

.tar.gz:
https://mega.nz/file/HLAH1axC#l3BuYUShxAblolrwKANChj5oIewSFu0UxcIbJczjOLc

**Comment by ggarra13** [comment]
@lukas-remis Hi. I was able to reproduce the and I should have a fix for it, among other improvements.  Try this new v1.2.7 beta:

.deb:
https://mega.nz/file/DS43gA7I#A76KZNzvPi-hJBQFA2Eup_Z78KmdBNg3bjxPdyt7A_c

.rpm:
https://mega.nz/file/6XJDGR6Y#41KLQqaYr_1fRgyiOXCC4gy4dVCJbjWZ5Mh2ZEYYa0s

.tar.gz:
https://mega.nz/file/Cfh2gQbT#eF4qngqJB2ztXy8BDktyASowOJjyPbusYKBiLuuSy2Q

**Comment by lukas-remis** [comment]
Hey Gonzalo! This works, thank you very much for the quick fix :)

But... ;) I think I found another bug - it seems mrv2 can't load dpx sequences. It just freezes.
If you need some dpx files for testing, you can download from here: https://ds.imaginary-pixels.com:6661/sharing/94UENzWR6

**Comment by ggarra13** [comment]
Those .dpx are corrupt. They have a Film Frame Rate of 0.  I've added a check for it just in case in mrv2.  Will have a new beta shortly.

**Comment by lukas-remis** [comment]
OK, that's strange. I had the same problem with original dpx plate, so this must have been passed in meta data.

**Comment by ggarra13** [comment]
DPX work around at:

.deb:
https://mega.nz/file/KShFBL6A#8WGKWTImwQQ-d5zO7KDJe0_ecDrIHixqOrrs_C2_DC8

.rpm:
https://mega.nz/file/ybRE0CSB#i1F8llPmRZf7XWrS2eFhR2v5cwnZJDEe45RoZXdqunY

.tar.gz:
https://mega.nz/file/7WZlHICZ#oWQ5sfAR8rIWp9-9SYBkVpDj7MCWv1Z3JW-H_O8FCN8

**Comment by lukas-remis** [comment]
Nice! This solves it. Thank you :)

btw, is there a setting in mrv2 of how much RAM should be used for buffering? I can't find anything like that.

**Comment by ggarra13** [comment]
> btw, is there a setting in mrv2 of how much RAM should be used for buffering? I can't find anything like that.

Panel->Settings->Cache/Gigabytes.  The default is to use half your RAM, but you can set it to whatever you want.

**Comment by lukas-remis** [comment]
Great. I was looking in Preferences. Thanks!
