### ISSUE TITLE
Add support for audio stepping frame by frame

### ISSUE THREAD

**Issue by ggarra13** [ggarra13/mrv2#3]
This is a tricky one, as it requires major revamping of the tlRender audio core.

**Comment by ggarra13** [comment]
Sccribbomg wiwht audio in fact already works.  You need to start playback and then scrub and the audio will be heard.  What is missing is scrubbing when stepping through each frame.

**Comment by BigRoy** [comment]
An artist here reported that for a video file if you change the FPS manually in the UI that unfortunately the audio also mutes - it'd be nice if the player could still play back with the audio even if the playback is slowed down or playing back at higher speeds.

**Comment by ggarra13** [comment]
mrViewer supported that, so I was hoping that I could add it too.  I am still not fully familiar with that portion of tlRender's source code but I think it can be done.  Probably for v0.8.5 or v0.9.0.

**Comment by ggarra13** [comment]
I went ahead and added it to v0.8.0, currently in beta.  It is in the beta branch and you can download binaries (if you have a compatible platform) at:

https://sourceforge.net/projects/mrv2/files/beta/

**Comment by BigRoy** [comment]
Both audio stepping and audio playback at different FPS works for me.

There is _not_ however audio playback during scrubbing through the timeline. (I'm not sure if we'd want that?)
If this issue is only about the first points then I'd assume this issue can be closed.

_I tested in 0.8.2 beta._

**Comment by ggarra13** [comment]
You can get audio playback during scrubbing if you Play Forwards or Backwards and *then* scrub.

**Comment by ggarra13** [comment]
I'll see if I make that automatically for v0.8.2, so that you don't have to manually play forwards when scrubbing.

**Comment by ggarra13** [comment]
Added in v0.8.2 beta.
