### ISSUE TITLE
mrv2-v0.3.7-Linux-64/bin/mrv2: symbol lookup error: /lib64/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language

### ISSUE THREAD

**Issue by LichiMan** [ggarra13/mrv2#30]
Hi,

I've just downloaded the .tar.gz release to avoid installing the rpm and I get this error when I try to run `sh mrv2-v0.3.7-Linux-64/bin/mrv2.sh`:
`mrv2-v0.3.7-Linux-64/bin/mrv2: symbol lookup error: /lib64/libfreetype.so.6: undefined symbol: hb_ot_tags_from_script_and_language`

I'm on Fedora 37 Silverblue.

Thank  you!

**Comment by ggarra13** [comment]
We compile mrv2 with Rocky Linux 8.1 which ships with freetype 2.10.  Fedora 37 Silverblue is cutting edge and ships with freetype2.11, which has a dependency on a newer libharfbuzz.

You may try this:

1) Rename the libharfbuzz.so.0 in the lib/ directory of mrv2.  If the /lib64/libharfbuzz.so in Fedora is a different version (not .0 ), you may need to add a symlink in the lib/ directory of mrv2.  
2) Download freetype 2.10 and install it in the lib/ directory of mrv2.

**Comment by LichiMan** [comment]
That worked. Thanks Gonzalo!
