### ISSUE TITLE
Difference/clamp of high values ​​in saved images or sequences as opposed to the preview in the application

### ISSUE THREAD

**Issue by joelRVC** [ggarra13/mrv2#304]
**Describe the bug**
When I save an image or sequence that is viewed with OCIO it seems to be exported with clamp, as if OCIO was not applied to the image. Here you can see a screenshot of the application and the images/video that are exported.

**To Reproduce**
1. Download [test.txt](https://github.com/user-attachments/files/17007806/test.txt), rename the file from .txt to .rar and extract the EXR
2. Open the file in the program.
3. Assign input color space acecg and display ACES video (or similar)
4. Save an image (preferably png)

**Expected behavior**

The exported image or video should have the view transform (display) baked into the final image in the case of png, jpeg, tiff, etc. formats (in videos it should be in SDR formats such as .mov. mp4, etc.).

**Screenshots**
mrv2 view
![screenshot](https://github.com/user-attachments/assets/56e944a0-1a60-4c9e-99fa-85d8cf441d20)
saved image
![peces](https://github.com/user-attachments/assets/9d0c8bec-5f5d-4029-a22b-0b137000f3a6)

video

https://github.com/user-attachments/assets/cf92a828-f8db-4d59-b3a6-9f3277d9ba15

**Desktop (please complete the following information):**
 - Windows 11
 - mrv2 v1.2.7

**Comment by ggarra13** [comment]
Try using:

Save Annotations

when you save the movie or image.  That should bake the OCIO transform.  If it does not, please upload the file again to a donwload site and send the link to it instead of sending a .txt file as it seems it got corrupted (I could not open it).

**Comment by ggarra13** [comment]
I am attaching the PNG saved with "Save Annotations" on.

![baked](https://github.com/user-attachments/assets/1f10c234-a1ad-4f18-ae79-0b8d00afdbd7)

**Comment by joelRVC** [comment]
Oh interesting, that helps thanks, although as a suggestion the function would be clearer if it was renamed to something like bake view to image, but if that operator is mainly for annotations you could separate the bake button into an additional option.

**Comment by ggarra13** [comment]
> by the way, it seems that exporting an image with save annotations activated affects the resolution of the image, I share an example, I don't think that should be happening, the resolution of the original image is 1920 x 1080.

The maximum image resolution when baking annotations (in your case OCIO), is the resolution of your screen.   I am not sure what program you are using to test the resolution.  Please use mrv2.

Check the resolution with:

    Media Information (F5) -> Video Tab -> Width/Height.

**Comment by joelRVC** [comment]
![{EBE5DA5B-DDF4-46DD-8434-61F5254089FC}](https://github.com/user-attachments/assets/1ba8d761-66e0-40de-80b8-2e1bf278be68)

**Comment by ggarra13** [comment]
I apologize for doubting you.  Some questions:

1) What's your screen (ie. monitor) resolution?
2) Can you save the image and check the Panel->Log?  It should print something like:
```
       [save] Image info: 1920x1080 RGB_F16
       [save] Viewport Size: 1920x1080 - X=0, Y=0
       [save] Output info: 1920x1080 RGB_U16
       [save] OpenGL info: RGBA_F32
```

I think we may be running into some floating point precission issues depending on your screen size.

**Comment by joelRVC** [comment]
![{52C17A4D-751E-467F-BF67-4ACEF45776A7}](https://github.com/user-attachments/assets/8b4ddb4f-e6b4-40ff-911e-80f1625319e4)

It seems that it may be because of that. To confirm from my laptop, how do I find the actual resolution of my screen. If I do it from the display properties it tells me that it is 1920 x 1080.

**Comment by ggarra13** [comment]
> It seems that it may be because of that. To confirm from my laptop, how do I find the actual resolution of my screen. If I do it from the display properties it tells me that it is 1920 x 1080.

1. Go to the Search button in the Taskbar.
2. Type Settings.
3. Click on the three lines at the top of the Settings Window to bring the panel to the left.
4. Select System
5. Select Display
6. In the Scale and Layout section, see the values of Scale and Display Resolution.

**Comment by ggarra13** [comment]
> It seems that it may be because of that. To confirm from my laptop, how do I find the actual resolution of my screen. If I do it from the display properties it tells me that it is 1920 x 1080.

Please run this little program:
[fullscreen.zip](https://github.com/user-attachments/files/17026160/fullscreen.zip)

1. Run the program.
2. Unselect "Border".
3. Select "Fullscreen"
4. Send me a screen capture of the values printed.

Send me a scree

**Comment by joelRVC** [comment]
Before closing this report to open the other one, I share the result of the program you sent:
![{A95801D6-050E-473B-83E5-4B2C550543A9}](https://github.com/user-attachments/assets/57ebfc59-6ca8-47b1-8ad0-9841afec3b7f)

I think I already found one of the factors that induce this behavior in mrv2. My display scaling in system configuration is set to 115% by default (I think because I haven't changed it before), changing it to 100% and exporting the image through mrv2 again exports correctly. Unfortunately for me, scaling at 100% makes the UI elements and texts less readable than they were until now (more noticeable using other programs).

**Comment by ggarra13** [comment]
Please try this beta version of mrv2 v1.2.8.  It fixes some floating point problems with exporting, albeit not sure if it will completely fix the issue you report.

.exe:
https://mega.nz/file/fTAHRQjI#Af1ucvOxu-T2RDA8zp0-xxwQkrxysfd8czVGUw53cQg

.zip:
https://mega.nz/file/jPwFEJ4J#7ocWM0sMRXhPImbekGLHm0L5hIYMkiAUAA_hu934ghc
