### ISSUE TITLE
Compare mode

### ISSUE THREAD

**Issue by lukas-remis** [ggarra13/mrv2#305]
Hi,

When using compare panel, changing the gain, gamma or saturation values affects only the A file - which makes it impossible to compare the footage. It should affect A and B the same way.

Also, when using wipe option, the wipe line appears in the possition of the cursor when you alt+click - but that only works when footage fits in the window. When you zoom in or out it doesn't work anymore, and the wipe line doesn't follow the cursor - this one is more of a bug I guess.

Lukas

**Comment by ggarra13** [comment]
Find a beta of v1.2.8 with both problems (and some other Python issues) addressed:

macOS amd64:
https://mega.nz/file/nagXWTiY#9rWyYlRzfKR6xPS8vZCkM-8IwM11rqoTozj3Ak41QJA

macOS arm64:
https://mega.nz/file/6Sh1UYjS#68QMRwLQjXa-fY1HqtZS0yChm_6Xt-kzI80uZj32Fo0

Linux .deb:
https://mega.nz/file/jXAyXTDI#f_n4EywTR-cP_55WFMFkYKo_vLquh_ILHStygd_SqWc

Linux .rpm:
https://mega.nz/file/3eJUUAaL#mWsL7RrkP5wJgrWhcZ-joybK7KKBIYrfzx3j9IIyess

Linux .tar.gz:
https://mega.nz/file/WSRCgKxK#sdMeKv724fd_VSS_R5O5RcLybf6aqFnjTSIB-znvKJk

Windows .exe:
https://mega.nz/file/mCZHWRyI#MpGddRC0KMQwcf40b4YaKfniExVRl2uAg9iQSEzvBUM

Windows .zip:
https://mega.nz/file/DOIT2ADY#5iggC40IWCpGewsDQDag-8kyAouGS_NEglzAI9hSejk

**Comment by lukas-remis** [comment]
Gonzalo, this works perfectly. Thank you very much!
