### ISSUE TITLE
Exported image resolution different from source, also Warn note in Panel -> log when exporting images "image too large for annotation options"

### ISSUE THREAD

**Issue by joelRVC** [ggarra13/mrv2#306]
**Describe the bug**
It's a behavior I encountered when #304 was resolved. When I save an image this notice appears. 
![image](https://github.com/user-attachments/assets/f20b041a-583a-4b59-83b2-71a7a00ea357)

When reviewing the exported image, the resolution differs from the original image (by a few pixels, which makes it more curious)

**Expected behavior**
The exported image should have the same resolution as the source image.

**Screenshots**
exported image (see resolution)
![{EBE5DA5B-DDF4-46DD-8434-61F5254089FC}](https://github.com/user-attachments/assets/1ba8d761-66e0-40de-80b8-2e1bf278be68)

**Desktop (please complete the following information):**
 - Windows 11
 - mrv2 v1.2.7

EDIT: I must clarify that investigating more about the cause seems that it also has to do with the display scale configuration (in my case Windows display settings), by default it is set to 115%. I mention it because perhaps when trying to reproduce the error it will not appear for you if your monitor uses 100% scaling.

**Comment by joelRVC** [comment]
@ggarra13 Ok, I already closed the other report. Responding to your last message there, I tried that version but the warning keeps appearing and the image continues to appear with altered resolution.

![{5E947C2E-4BC5-4BC0-B756-30E66EF180CC}](https://github.com/user-attachments/assets/4b739a04-31c1-40b4-a441-3229da5125a8)

It still continues to export with a different resolution. I compared it with the image that was exported correctly and I noticed one thing, it seems that apart from varying slightly in resolution it also generates a blurrier image.

correct image

![{1F2C816D-0FAC-49DC-96AF-2C9E40D805AD}](https://github.com/user-attachments/assets/f6ac0aa0-25a4-42ed-8cc0-422c5ee73777)

issue image

![{C090616B-01CA-4E66-8B1A-6EAF86F76CBE}](https://github.com/user-attachments/assets/6c1cda0f-52c5-4e62-a837-5ed4c6f82d98)

**Comment by joelRVC** [comment]
I think you mentioned before that mrv2 exports images as if they were screenshotted, right? (I apologize if I assume incorrectly) That would explain why it can look blurry and why the message appears: the program captures the image according to the current resolution of the screen (taking it as 100% scale) and then rescale it to assimilate it to the source, that is where the floating point problems could be happening.

**Comment by ggarra13** [comment]
> I think you mentioned before that mrv2 exports images as if they were screenshotted, right? (I apologize if I assume incorrectly) That would explain why it can look blurry and why the message appears: the program captures the image according to the current resolution of the screen (taking it as 100% scale) and then rescale it to assimilate it to the source, that is where the floating point problems could be happening.

Your assumption is likely correct.

I am going to reference this issue with the FLTK guys, so I am reposting the FLTK fullscreen demo to show them your screen settings.

![{A95801D6-050E-473B-83E5-4B2C550543A9}](https://github.com/user-attachments/assets/57ebfc59-6ca8-47b1-8ad0-9841afec3b7f)

**Comment by ggarra13** [comment]
Here's a beta of v1.2.8 that fixes the problem for me.  Please give it a try and report back:

.exe:
https://mega.nz/file/3epmHJwJ#d2GBkSeG5NHnNJy82nBy0Q2cXPJ2BzQAuNx7reW7KOo

.zip:
https://mega.nz/file/WeB1HLKY#OFB40WzMioQcHdoG_2Uo9Qz21f7XazQDWhBkNbl34fg

**Comment by joelRVC** [comment]
> @joelRVC I have a question for you. How do you set the Windows 11 Display scaling to 1.15. In my Windows 11 Pro, I can only set it to rounded numbers like 125%, 150%, etc?

it was set like this

![{115DBCFC-B97C-4B03-89A5-DCC2C6BAD6A3}](https://github.com/user-attachments/assets/f1783595-78a9-4b90-8e7d-ddbcc667f337)

by entering the scaling options you can choose a custom scale, it will ask you to sign out


![ApplicationFrameHost_R4aac0f4SN](https://github.com/user-attachments/assets/4ecf4a2b-8fbc-4b39-a6d9-ef4bc0944231)

![ApplicationFrameHost_F1wG1Qn0Ke](https://github.com/user-attachments/assets/5dda367a-d64e-4519-bd5d-c824e19b426a)

**Comment by joelRVC** [comment]
> Here's a beta of v1.2.8 that fixes the problem for me. Please give it a try and report back:
> 
> .exe: https://mega.nz/file/3epmHJwJ#d2GBkSeG5NHnNJy82nBy0Q2cXPJ2BzQAuNx7reW7KOo
> 
> .zip: https://mega.nz/file/WeB1HLKY#OFB40WzMioQcHdoG_2Uo9Qz21f7XazQDWhBkNbl34fg

It seems to work correctly now, thank you!! I attach examples with the test image.

Windows 1920 x 1080, display settings scale 100% (reference):

![peces_aces 1 2_01](https://github.com/user-attachments/assets/001f381f-a632-4d1a-ab83-af5969f67fb2)

Windows 1920 x 1080, display settings scale 115% - v1.2.7:

![peces_aces 1 2_02](https://github.com/user-attachments/assets/26ee2653-ac1c-4ff7-a848-86bb64ba0272)

Windows 1920 x 1080, display settings scale 115% - v1.2.8 fix:

![peces_aces 1 2_03](https://github.com/user-attachments/assets/e931216b-4329-401d-bc0b-07d1dc1cdeb3)
