### ISSUE TITLE
Saving Image Sequence Frame numbering

### ISSUE THREAD

**Issue by timfritzksu** [ggarra13/mrv2#312]
**Describe the bug**
Saving image sequences counts 1, 2, 3 ... 10, 11, 12 ... 100, 101. This isn't typical for how tools such as Maya, Blender, Premiere, Davinci Resolve, etc, read or write image sequences. 
![2024-10-14_15-12](https://github.com/user-attachments/assets/df4a402f-bd00-410e-bdc9-dd43e5eba818)

**To Reproduce**
1. Load a video
3. Save as a sequence
4. enter file name
5. Images exported with names such as ImageSequence1.jpg

**Expected behavior**
Image sequences should include (configurable) leading zeroes. Example: ImageSequence001.jpg or ImageSequence0001.jpg. This reads properly into various tools such as Adobe products, Maya, Blender, Davinci Resolve. This would also sort properly in Windows File Explorer or Linux equivalent.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 11
 - Version mrv2 1.2.8

**Additional context**

**Comment by ggarra13** [comment]
mrv2 (Darby's tlRender actually) automatically detects padding based on how you save your images.

If in the file requester, you type:

imageSequence.0001.exr

or:

imageSequence_0001.exr

the padding should be automatically detected.  I've tried it with v1.2.8 Win11 and LInux with both the Native and mrv2's built-in requester and it works.

**Comment by timfritzksu** [comment]
Just tested it, can confirm. Works as you explained. 
Thank you!
