### ISSUE TITLE
App doesn't start on Windows 11

### ISSUE THREAD

**Issue by ChrisFriendly** [ggarra13/mrv2#313]
I both installed it and then tried without installation (zip file).

It doesn't start.

Edition	Windows 11 Pro
Version	23H2
OS build	22631.4317
Processor	13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
Installed RAM	128 GB (128 GB usable)

**Comment by ggarra13** [comment]
I tried both v1.2.8 and v1.2.9 beta and they both worked for me when starting them from a .zip file.

1) What version of mrv2 are you trying and where are you downloading it from?
2) Can you fire it from the command-line (cmd.exe, Windows terminal, etc) and see if you get any errors?

**Comment by ChrisFriendly** [comment]
Downloaded from here, github, both v1.2.8 and v1.2.9 beta
vie commandline it tells me:
ERROR: RtApiWasapi::getDeviceInfo: Unable to retrieve device mix format.

**Comment by ggarra13** [comment]
I am sorry to say, Chris, that this is one of the long standing bugs in mrv2.  It seems this is the same issue as that of #194.  So far you are the second person that reports it.  It seems to happen with some audio cards.  Unfortunately, I don't have a way to test it or debug it.

As a final test, please do this:

1) Update your audio drivers and see if that addresses it.
2) Make sure you don't have any applications that use audio running.
3) Start mrv2 again from the command-line and use the -log option to see what it prints out.  Report it back here.
4) Upload an image or description of your audio setup here to see if there's a correlation between your setup and that of #194.

**Comment by ChrisFriendly** [comment]
It happened because usually I do not install the audio driver of my nvidia graphics card. Just the display driver.
My mainboard has it's own sound and I didn't want to have those additional audio interfaces showing up.
Apparently this caused the error. I just installed the newest version of nvidia studio driver with the audio driver and it starts without an issue.
