### ISSUE TITLE
Playback cache

### ISSUE THREAD

**Issue by lukas-remis** [ggarra13/mrv2#317]
Hi,

I'm wondering if it would be possible to have an option for disk cache, instead of RAM cache, or some sort of mix of both.
We usually play file sequences over the network (from a network drive), so it needs to be buffered for smooth playback. But on some very long shots more than 80 GB of RAM is needed to buffer the whole shot. Perhaps NVMe drives are fast enough to handle the caching ?

Cheers,
Lukas

**Comment by lukas-remis** [comment]
So Read Ahead/Read Behind reads from disk? But in case of network drive, it's reading from network? Not creating any disk cache ?
I was rather thinking of having an option to switch the RAM cache to Disk cache. Would that be possible?

**Comment by ggarra13** [comment]
> So Read Ahead/Read Behind reads from disk? But in case of network drive, it's reading from network? Not creating any disk cache ?

If you set the Gygabytes value to a small value (but higher than 0), mrv2 will only cache on RAM that small amount of images.  When the amount of memory is filled, the caching will read from disk.  If the disk is on the network, the reading will then have to go through the network too.

> I was rather thinking of having an option to switch the RAM cache to Disk cache. Would that be possible?

Set the Gygabytes value to 1, and you should see mrv2 reading mostly from Disk.   You will need a fast Disk and a fast network connection, thou.   You will likely find it disappointing unless your images are small.

**Comment by ggarra13** [comment]
Your best bet for long images is to create an .mp4 file with ffmpeg (for the fastest workflow) or with mrv2 (slower).

**Comment by lukas-remis** [comment]
Alright, thanks for the information
