### ISSUE TITLE
Previous/Next image version is buggy

### ISSUE THREAD

**Issue by hollov** [ggarra13/mrv2#318]
**Describe the bug**
Previous/Next image version feature seems to be doing the same as First/Last image version.

**To Reproduce**
1. Open an image sequence that has at least 3 different versions
2. Click on Image --> Version --> Next / Previous
3. You'll see that it will jump to the First / Last version instead of the Next / Previous one

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - Version mrv2 1.3.0

**Comment by ggarra13** [comment]
Here's version v1.3.1 beta that should fix it:

.exe:
https://mega.nz/file/LaRlERIB#vI6QK_N30JDFis_be3yQsuHA-G4faS_WbCYjowboprA

.zip:
https://mega.nz/file/Xbx3WAiC#F-RS0XYnya9chsbMoU4uLlCAXpWk6wez-mbUB0KzZ_g

**Comment by ggarra13** [comment]
@hollov Can you confirm it is fixed and can the issue be closed?

**Comment by hollov** [comment]
Yep, it's fixed 🙏
