### ISSUE TITLE
images menu missing when versioned clip is loaded

### ISSUE THREAD

**Issue by cgene75** [ggarra13/mrv2#323]
Images menu missing when versioned clip is loaded.

our naming convention for frame stacks is as follows: shotname_task_version.####.exr

According to the documentation when I load such a sequence, I should have access to an 'images' menu that allows version switching, however I do not seeing on Rocky Linux 9 nor Windows [v1.3.1].

![Uploading images_menu_missing_v01.png…]()

**Comment by cgene75** [comment]
![images_menu_missing_v01](https://github.com/user-attachments/assets/284c74f4-9580-4962-8777-1f77fab458ee)

uploading screenshot since it failed above.

**Comment by ggarra13** [comment]
Works for me.  Two things:

1) Do you happen to have a "_v###" in the path that may be different than the version name of the files?  That will trip mrv2.
2) Do you happen to have missing frame(s) in the sequences?  
3) Try a simple test:
          * Create a comp_v01.1001.exr and comp_v02.1001.exr.
          * Open mrv2 comp_v01.1001.exr

**Comment by cgene75** [comment]
Strange.  I get the menu in linux, but I do not on on windows.

the contents of the folder is pretty straight forward and strictly obeys the naming convention.  There are no missing frames in the sequence, Nor are there any stray files:

![folder_contents_v01](https://github.com/user-attachments/assets/8cdcd93a-252d-4e5d-8c5a-d6027c2b0c44)

**Comment by ggarra13** [comment]
Make sure you are using the latest v1.3.1 beta of Windows from sourceforge beta, as one of the things fixed was exactly the versioning.  If you cannot get it to work with the latest release, I will download it and install it to see if something is indeed broken as my developer builds work.

**Comment by ggarra13** [comment]
Oh... btw.  Loved your lss command.  I wrote one for ILM in Perl to beat the performance of their python implementation back in the old days.

**Comment by ggarra13** [comment]
@cgene75 I just downloaded the latest mrv2 from sourceforge beta for Windows and it works fine for me.

**Comment by cgene75** [comment]
I have more strangeness to add into the mix.  I decided to copy the frames onto local storage... and sure enough:

![folder_contents_local_v01](https://github.com/user-attachments/assets/b33cd566-b283-4dd2-b308-fbeb24dab9fb)

vs, loaded over NFS:

![folder_contents_nfs_v01](https://github.com/user-attachments/assets/2f2e981e-d4f7-42c4-889f-fe6cf214ef44)

I wonder if the same mechanism that's preventing the path mapping from working is at play here.

ps: I love the lss command too.  it really helps to be able to abstract frame stacks into single entities.  there are few useful companion scripts too, _mv_s, _offset_s, etc...

**Comment by ggarra13** [comment]
> I wonder if the same mechanism that's preventing the path mapping from working is at play here.

You may be onto something there! Here's a new version for you to try:

.exe:
https://mega.nz/file/TTBQHITA#ex1tAe8ehAeYXx4EoxYjbxlhHy41PbJ5KMLJrBeKaJI

.zip:
https://mega.nz/file/qKQjgISC#0dfP0yNApw9GL0gbcjOy6WFNT6mx-z0NYCnpsJbr-hQ

> ps: I love the lss command too. I've first run into these at DD in the late 90s, and i've been writing versions ever since trying to get just right ;)

Me too, about the same time during Titanic.  The original author of lss at DD was my dear good friend Greg Ercolano, who first wrote it in awk and then ported it to Perl.
I found that ILM's one, while painfully slower due to being written in Python, got their formatting much nicer and simpler.

**Comment by cgene75** [comment]
does not appear to be working here:

![folder_contents_nfs_v02](https://github.com/user-attachments/assets/299c2ef6-bc5c-4905-bdd5-37044cfda394)

[About window showing build time, and lack of image menu]

**Comment by ggarra13** [comment]
> does not appear to be working here:
> 

Could it be a network permissions issue?  Here's a new version that should log what it is doing:

.exe:
https://mega.nz/file/HSAWFJra#HOPRXq3Wnur8DjZgRpzcuuqcD-T0iGRpq5Jbukq_--8

.zip:
https://mega.nz/file/mb5wkbxI#txLSHQFHphOQ6QCLKmut1VDZG2jTvX2MRnbC1DqCgH4

Send me the log (from the command-line or from Panel->Logs) to ggarra13@gmail.com.

> ps: small world eh?

As the saying goes in Argentina, "el mundo es un pañuelo".  "The world is a handkerchief" and I guess we are the mucus 🗡️

**Comment by ggarra13** [comment]
Oops!  Your problem is that the Image/Version menu does not appear.  Silly me!

According to ChatGPT, it is a problem with the NFS mount and backslashes.  I've compiled a new version that I hope will fix it:

.exe:
https://mega.nz/file/bXwShLzb#IJJZjkYLgymS1sqX1LSOfh5y7sRa7rd60OXoYvp07Yo

.zip:
https://mega.nz/file/WbhAFCSS#Zz7EM5xj9zQGbrNBmDk1xpN0fE8oMppFwTJB9sm1pa4

**Comment by cgene75** [comment]
I'm afraid that wasn't it!
![folder_contents_nfs_v03](https://github.com/user-attachments/assets/2725a0ed-836c-4e10-8a14-7e3d20d9caad)

G

**Comment by cgene75** [comment]
On a dare, I decided to host the images on a different NFS location... I thought perhaps the path length was an issue?

I got the following error message, but the image sequence opens, AND I get the images menu!

![folder_contents_nfs_v04](https://github.com/user-attachments/assets/6d78f526-e9e8-45b0-8cf9-f35561aa9ae9)

**Comment by cgene75** [comment]
Just as a matter of clarify... The mounts P:\ and U:\ are hosted on the same server, with the same AD permissions, accessed via the same user account on the same machine.

**Comment by cgene75** [comment]
Apologies for the stream of messages.  I've decided to try launching from the shell, and I get the following error message. 
![folder_contents_nfs_v05](https://github.com/user-attachments/assets/296a800f-4334-40c6-b999-f36947e403eb)

mrv2 does not start (and will not, until I remove the entry from mrv2.prefs recent_files section).

I'm fairly confident that this is not an NFS problem.  We've been pulling files from that server using the same paths using houdini, and Nuke for years now.  If this WAS a path issue, these file wouldn't be opening.... but they are.  i'm just not getting to see the images menu!  somehow!

G

**Comment by cgene75** [comment]
ok -- here's the latest... I finally feel like I've got a handle on this slippery bug.

I decided to rebuild the network folder structure locally... so I created
C:\gene\project_name_##-####\lem020\images\2d\

the images menu did not appear.

I then moved all the files into C:\gene\project_name_##-####\

the images menu did not appear.

I then renamed the folder to C:\gene\project_name_##_####\

and the images appeared.

my current guess (which falls in line with all the results we've been seeing) is that the '-' character in the path breaks the regex somehow.

phew?!

**Comment by ggarra13** [comment]
Do the ## stand for numbers, letters or both?  I can refine and try to fix the regex.  Here's a python script that should mimic what mrv2 does behind the scenes:

import re
sep = '_v'
path = r'P:\something\lem020\images\2d\lem020_comp_v03.1014.exr'
regex = rf"([\w\\:/]*?[/\._]*{sep})(\d+)([\w\d\./]*)"
m = re.search(regex, path)
if m:
       prefix = m.group(1)  # prefix
       print('prefix',prefix)
       version = m.group(2)  # version number
       print('version',version)
       suffix = m.group(3)  # suffix
       print('suffix', suffix)
else:
      print(f"{regex} did not match {path}")

**Comment by ggarra13** [comment]
Here we go once again.  A fix for the regex:

.exe:
https://mega.nz/file/2PYSBLhC#JMU6166LCs3lSll7o-coXocISc_GIdXITt6tsQv6VWk

.zip:
https://mega.nz/file/DKBDCCJJ#q3aarFyBLlZxw_lAh-xrJXS8AsCNI-M3YI8Nm3RCd40

**Comment by cgene75** [comment]
Winner Winner Chicken Dinner!

![folder_contents_nfs_v06](https://github.com/user-attachments/assets/54643b1a-0d39-4a94-b717-8bb2c811e23e)

Thank you very much for fixing this!  Truly appreciate it!
