### ISSUE TITLE
Many hotkeys do not work

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#35]
For me all the hotkey in the "Panel" and the "Render" category do nothing. The other categories mostly work (except for "F10" in the "Window" category, which should open the preferences window).

**Comment by ggarra13** [comment]
I was able to reproduce a crash with hotkeys on the "Panel" menu.  However, for me the hotkeys in the "Render" category works, as does the "F10" hotkey.
Is it possible you have the focus set to an input widget like the Settings or Color  input values?  Pushing with the LMB on the view window should bring the focus back (albeit it will also start the playback currently -- the next version should fix that).

In any case, what platform are you on?  I can send you a new beta for you to try?

**Comment by ggarra13** [comment]
I know what's happening.  You probably hid the menu bar, did you not?  If so, I have to work on a work-around, but it will take a while.

**Comment by Thane5** [comment]
Yes, i did hide everything except for the timeline.

**Comment by ggarra13** [comment]
I have a fix for it.   Give this Windows 64-bit version a try:

.exe
https://mega.nz/file/PWZigB4D#XJaMp0j3czBmA-sMJ3QYoFhDQxyqvBETPYiiwYUqSIY

.zip
https://mega.nz/file/7SoUzQyC#5_5_s5DTwHYhROuc1Gnof_QbFHa45QXQjANJdIO3kKc

If you need Linux or macOS, let me know.

**Comment by ggarra13** [comment]
I released a new version today with the fixes to the hidden menu bar.  It is version v0.4.0.  You can get it here in the releases section or in sourceforge.net.
