### ISSUE TITLE
Issue with Media Info panel

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#37]
I tried to drag the Media info panel out from the side, to use it as a floating window. The whole process was a bit glitchy, and the menu bar endet up beeing hidden. Basically i now no longer can move that window around.
![Screenshot 2023-04-11 094552](https://user-images.githubusercontent.com/13683581/231093698-7aabc432-066f-4839-86a6-b3378f580577.png)

Adding to this, sometimes when i close and re-open mrv2 in this state, it will only open in a broken way, that displays itself as a large black rectangle on my desktop, where previously the media info panel was.
![Screenshot 2023-04-11 094900](https://user-images.githubusercontent.com/13683581/231094018-c04c5b24-96c7-4d5e-af08-5b1e6f177860.png)

Of course, after deleting the file `mrv2.prefs` everything is back to normal.

**Comment by ggarra13** [comment]
I was able to reproduce it.   I need to investigate what's happening.

**Comment by ggarra13** [comment]
I released a new re-relase version of v0.4.0 that should address in big part the issue you are seeing.  You can download it from github releases or from sourceforge.net.

**Comment by Thane5** [comment]
Awesome, now it behaves much better. 
However there are still some minor issues, for example this one, it still turns grey if you scroll down and then make the window smaller from the top:
https://user-images.githubusercontent.com/13683581/231210309-a479a398-abf0-4fd2-8217-1fb562d4578f.mp4

The popup window also is far too large by default, and scretches beyond the borders of my screen, so i can not even read some lines that are at the very bottom, unless i manually resize the window.

**Comment by Thane5** [comment]
Okay, also sometimes when i close mrw2 i am faced with the black rectangle again, which then tells me through a windows dialogue that the program stopped working. But i am having a hard time reproducing this issue consistently.

**Comment by ggarra13** [comment]
What platform are you seeing those issues?  Also if on Linux, what window manager?

**Comment by Thane5** [comment]
It's Windows 11

**Comment by ggarra13** [comment]
I think I solved most issues with resizing and repositioning (they are really fast now).  I also fixed a potential crashing bug on exit on Windows, which might have been what you were seeing.

Anyway, download v0.4.0 again from the github Releases or from sourceforge.net.

**Comment by Thane5** [comment]
Yep, it appears much more stable now. 

The way all but the first categories in the "Media info" panel are collapsed now is a bit odd to be honest, especially since they always collapse when you close and re-open the panel (Though that's just be my personal preference).

There is also this small bug where the contents of the panel can not fully extend to the bottom of the window, if it is attached to the side:

![image](https://user-images.githubusercontent.com/13683581/231394064-e4b405ad-3112-4dc1-8aff-06dea16214ca.png)

**Comment by Thane5** [comment]
Strange, i just had another phantom instance of mrv2 pop up like this even though i last used it an hour ago.

![image](https://user-images.githubusercontent.com/13683581/231435419-ba236d9f-85bf-4511-a30a-5baf5ac22e70.png)

**Comment by ggarra13** [comment]
Ok.  I made yet another release of v0.4.0.  This should fix your zombie mrv2.exe process.  It should also remember the tabs open/closed in the media info panel.  And I think (not tested fully) it should also pack the widgets properly on the side panel.

Download it from github releases or from sourceforge.net.

**Comment by Thane5** [comment]
No more zombies, so thats good. 

Regarding the panel size issue, it looks to me that tat one isnt really resolved by chaning the tabs hehavior, because once those unfold, the window automatically expands towards the bottom, and after that the user still can not see what is at the very bottom without moving and resizing the window. 
I guess, ideally the media info window could know how large the screen is and adjust its size (or maximum size) accordingly.

**Comment by ggarra13** [comment]
The media info panel was already paying attention to the screen size, but only in the resizing, not on creation., so the scrollbar would be wrong  I have a new version that fixes that:

.exe
https://mega.nz/file/rTw2WTAB#BctOzqLZBrH7PkU53Rebj4uuSJLFlqnn1syBfU18hLM

.zip
https://mega.nz/file/jPpDxCYb#esG0RLUHw2wKtZ34BAplLYlbmC0k6QjU9fqOu5KsrH4

Let me know if this version addresses your concerns.

**Comment by Thane5** [comment]
I didnt really see a change here. The panel still expanded downwards beyond my screen when i open the tabs.

**Comment by ggarra13** [comment]
Okay.  Download this version that makes sure the window never extends beyond the bottom of the screen, regardless of its Y position.  Previously it would extend it assuming your window was at Y = 0 and it also read the configuration from your preferences (which, if you saved the window going off-screen it would restore it just like that).

.exe
https://mega.nz/file/CSpFXZQZ#k7Lp4PXf6ZrsfT62koupX-9askXLlicU9DK1ybEofmE

.zip
https://mega.nz/file/vC51EYZC#_mK4Dncj7qV8WSRENDRQ7aaQgicVURHPgxP3WVBsj2s

**Comment by Thane5** [comment]
Could it be that the Windows taskbar is blocking the view?

https://user-images.githubusercontent.com/13683581/232764071-7ec94a0a-8d02-4706-a5bb-87d8347dc7be.mp4

**Comment by ggarra13** [comment]
No, I take the Windows taskbar into account.  Are you using the latest version I uploaded?  Did you clear the Settings (Panel->Settings->Default Settings (or remove the mrv2.prefs file)? It should not allow you to resize past the bottom (with or without taskbar).  If your window is going beyond the desktop, in the latest version, try resizing from the side and it should shrink the window to fit the desktop.

**Comment by Thane5** [comment]
Okay, i deleted my mrv2.prefs file and the UI reverted to its default. But behavior is still the same as in the video above.

**Comment by Thane5** [comment]
Here's a video file the same amount of metadata, in case it helps you test it: https://mega.nz/file/dqAkzB4S#X9jZxBtxfEwARnDrCHxjTYYlciVUA6xNqPCvqWO8BeM

**Comment by ggarra13** [comment]
Can you check the version you are running?   Window->Version.  It should be:

mrv2 64 bits - v0.4.1 - Built Apr 18 2023 07:33:07

**Comment by ggarra13** [comment]
Your video works fine for me.  The Media Info Panel window does not resize past the taskbar and the scroll bar appears.  You are likely running the wrong version of mrv2.

**Comment by Thane5** [comment]
Oh yeah, i just double checked the zip version and reinstalled it again. Now it works for me too - thanks!
