### ISSUE TITLE
Export video with annotation

### ISSUE THREAD

**Issue by dchabashvili** [ggarra13/mrv2#39]
Currently annotations are not exported with mp4 (or any other format) export. And on Windows 11 sometimes gives color error and on consecutive saves does not save the file on a drive.

**Comment by ggarra13** [comment]
I put out a new release v0.5.0 on both github and sourceforge.  After you select a filename to save, a popup will appear to allow you to select to export annotations.  Also, the color error should be gone.

**Comment by ggarra13** [comment]
It turned out v0.5.0 was a tad buggy as you had to manually frame the view or open the viewport to fullscreen to export the videos with annotations.  I have the problem fixed in v0.5.1.  Sorry for the inconvenience.
