### ISSUE TITLE
on macOS 12.6 directories and files aren't visible

### ISSUE THREAD

**Issue by jamesrburgess** [ggarra13/mrv2#44]
You can browse with File->Open->Directory down to your home directory but then it appears as if you have no files or folders in your home dir. 

I would guess this is a security permission issue, macOS should be prompting me for the app to have Disk Access but it doesn't.

**Comment by ggarra13** [comment]
File->Open->Directory does not list files.  Only directories.   It is a browser to load a whole directory of files (somewhat dangerous).

**Comment by ggarra13** [comment]
However, you said that you don't see directories in your home directory.  That's strange, too.  It should show you all the standard macOS directories.

**Comment by jamesrburgess** [comment]
I wasn't super clear, sorry about that.

What meant was, I can browse into my home dir, I'll see the "Documents" folder, but if I double-click and go in there, the directory with my images in doesn't appear. 

I checked in System Preferences->Security & Privacy->Privacy under "Full Disk Access" and "Files And Folders" and mrv2.app was not listed in there, maybe you're just missing a plist request entry? I would have expected macOS to have asked for Files and Folders permission but it didn't.

**Comment by ggarra13** [comment]
As I said, File->Open DIrectory does not show files, only directories.

> I checked in System Preferences->Security & Privacy->Privacy under "Full Disk Access" and "Files And Folders" and mrv2.app was not listed in there, maybe you're just missing a plist request entry? I would have expected macOS to have asked for Files and Folders permission but it didn't.

On older versions of macOS, non-notarized applications like mrv2 were not asked by permissions and were just forbidden access.  In Ventura, at least, Apple seems to have relaxed its security (or fixed what might have been a bug) and now it asks for permissions.

Try to see if you can add it manually.

I admit also I'm not a macOS guy.  I created an Info.plist myself, which you can check in the mrv2.app/Contents directory to see if I made any mistake.

**Comment by ggarra13** [comment]
> I admit also I'm not a macOS guy. I created an Info.plist myself, which you can check in the mrv2.app/Contents directory to see if I made any mistake.

I just checked it and found out that the BundleIntefier was the same as the old mrViewer.  I'll fix it in the next release.

**Comment by ggarra13** [comment]
Here's a beta of v0.5.2 that fixes the BundleIdentifier.  It will probably not address your issue, but it should allow you to have the old mrViewer and the new mrv2 installed together.

https://mega.nz/file/HXg3iJZL#H4x9Gdd3LGR2RTSB_ZpQYon2wHwnnbHmWXatKHX3Hno

**Comment by ggarra13** [comment]
@pmolodo Have you tried downloading the mrv2 on these pages and, after install, manually adding it to System Preferences->Security & Privacy->Privacy under "Full Disk Access" mrv2.app?

**Comment by ggarra13** [comment]
Alternatively, you guys can use the macOS native file chooser instead of mrv2's one, which will likely not have permission issues.  Go to:

Preferences (F10) -> File Requester  and tick the Native FIle Chooser option.

**Comment by jamesrburgess** [comment]
Native file dialog works fine, don't need "Full Disk Access" for that. Full Disk Access does not help with the builtin browser
