### ISSUE TITLE
macOS 12.6 if I drag an image into the window from the finder it looks for the wrong start frame

### ISSUE THREAD

**Issue by jamesrburgess** [ggarra13/mrv2#45]
I have a folder with moving.0001.exr, moving.0002.exr etc. If I drag any one of them into the window, instead of opening them I get the error:

368.611 ERROR tl::io::ISequenceRead (/Users/gga/code/applications/mrv2/tlRender/lib/tlIO/SequenceIORead.cpp: 123): /Users/jrb/Documents/moving/obj/moving.0000.exr: /Users/jrb/Documents/moving/obj/moving.0000.exr: Cannot open file: No such file or directory

note it tried to open frame 0000 which doesn't exist. If I copy a frame and rename it so there is a 0000 then it opens

**Comment by jamesrburgess** [comment]
1 mrv2 64 bits - v0.5.1 - Built Apr 27 2023 17:00:59
With clang 1 1
(C) 2007-2023 Film Aura, LLC.

2 sequence goes from 0001 to 0007

3 If I move the images to ~/ then it works, dragging 0001 into the window opens the sequence

4 no, start mrv2 and then drag the image in

Not sure if you want these kinds of reports but in case you do:
a)  the app doesn't remember its last screen location
b) it would be nice to set default viewed layer, I couldn't find a pref for that. Say I always want to open the layer named "diffuse". Currently it looks like it opens the EXR  "unnamed layer", but if there is no r, g, or b in the unnamed layer, it picks "a" (which I happen to have)

**Comment by ggarra13** [comment]
> 
> 3 If I move the images to ~/ then it works, dragging 0001 into the window opens the sequence
> 

Then it is definitively an issue with security on macOS.  Unfortunately, there's not much I can do as the security issues on macOS were really fragile for non-notarized applications like mrv2.  

You might try adding mrv2.app to the list of Preferences->Security & Privacy->Privacy under "Full Disk Access" and "Files And Folders"  manually and see if that fixes it.

> 
> Not sure if you want these kinds of reports but in case you do: a) the app doesn't remember its last screen location 

You can make it remember the screen location by going to Window->Preferences->Positioning.  You can then take the values of the current window and tick the position and/or the size.
This is not done by default as if you fire several mrv2's, they would pile one on top of each other.

> b) it would be nice to set default viewed layer, I couldn't find a pref for that. Say I always want to open the layer named "diffuse". Currently it looks like it opens the EXR "unnamed layer", but if there is no r, g, or b in the unnamed layer, it picks "a" (which I happen to have)

By default it should open the rgba. layer (calling it Color).  If one does not exist, I don't have a good idea what it would do.  Please provide a dummy image with the example layers you have and open a new issue for a feature request of opening a custom layer.
