### ISSUE TITLE
Feature request: 360 latlong media support

### ISSUE THREAD

**Issue by darkvertex** [ggarra13/mrv2#5]
Hi!

The player is very nice but my studio mostly works in VR and it would be really cool if there was a mode which could reproject latlong projections as a draggable video sphere.

RV implements this as a thirdparty module (originally written and opensourced by The Mill) which adds a menu option that adds in a GLSL shader that does the projection warping from latlong to orbitable sphere. -- Here is the shader code, if it helps somebody make it for mrv2:
https://github.com/AcademySoftwareFoundation/OpenRV/blob/main/src/plugins/rv-packages/lat_long_viewer/LatLongViewer.glsl

**Comment by ggarra13** [comment]
Thanks for the first request!  I also have it in my todo list.  The original mrViewer supported this as well (in the Stereo window).   You can play with it on the meantime (https://sourceforge.net/projects/mrviewer/files/v6.2.3/).  My approach was more rustic.  It mapped the image into a GLU sphere.

**Comment by ggarra13** [comment]
I ported the shader in v0.3.1 (now available both at github and at sourceforge).  It seems to partially work. but it stretches the image pretty badly closer to the poles (ie. rotateX ).  I could not get the GUI to appear in RV to check that it matches. Can you verify that's how it should look?
If you are a coder you can also hack at the GLSL shader code yourself, as it is installed in shaders/opengl/latLong.glsl.

**Comment by darkvertex** [comment]
@ggarra13 First of all, thank you for the efforts.

I ran your latest mrv2 release on my Windows 10 laptop. I'm sorry to say that the latlong viewer does have a number of bizarre warping issues that RV does not (and not just at the poles.)

Three issues that stuck up to me, which may or may not be all the same issue:
- there is a crazy diagonal stretch that appears in some rotation angles.
- rotating in Y has popping at certain angles (almost like some kind of gimbal lock issue.)
- dragging the mouse sometimes orbited the wrong direction, though maybe it's because of the gimbal problem.

I recorded a screen capture showing the visual artifacts:
https://user-images.githubusercontent.com/941331/216382357-4ed90f24-35c2-4b27-857c-bc8be32a69d0.mp4

The video being played is some 360 video from the internet which I downloaded off of this Vimeo link if you wanna repro with the same: https://vimeo.com/215984568

**Comment by ggarra13** [comment]
I never used RV.  I am able to bring the latLong shader with Session Manager.  But I found no way to bring ithe GUI to control it.  That would allow me to debug it more easily.

**Comment by darkvertex** [comment]
It's too bad OpenRV doesn't have binaries yet, but I can show you what it looks like with the ShotGrid-provided RV build (which only works if you have a ShotGrid site.) Do you have access to a SG site?

Here's a capture of orbiting the same video in RV 2022.3.1 and as you can see, there's no diagonal warping and the poles look alright:

https://user-images.githubusercontent.com/941331/216385243-54870ecb-e67f-4dee-b732-8cc107be9335.mp4

---


> I never used RV. I am able to bring the latLong shader with Session Manager. But I found no way to bring ithe GUI to control it. That would allow me to debug it more easily. Can you help me?

Absolutely! Sorry, I took RV knowledge for granted.

So, if you open RV (after you login to SG, if you have the official Autodesk build), click on "RV" in the top left, it's a menu, and go to Preferences. In that window, go to the Packages tab and enable both checkboxes beside the "Lat-Long Media Viewer" package, as it comes disabled by default:

![Enabling the latlong viewer in RV)](https://user-images.githubusercontent.com/941331/216387509-248cfb30-dc1e-4003-a048-6dae2357fed8.gif)
Your prefs should autosave upon closing the window, and the package is loaded as soon as the checkboxes are ticked.

Afterwards, just drag in a latlong video. It will load in normal 2D mode at first. You can drag horizontally to move in time and hit spacebar to play/pause.

(If your computer doesn't have a ton of RAM and you feel RV is going too crazy consuming it and you wanna just "stop" on any one frame without caching you can disable it temporarily from _Tools -> [Cache Mode] "Cache Off"_.)

**To enable the 360 mode**, go to the _Image_ menu and in the _Lat-Long Viewer_ section at the bottom, do "_Add As Top-Level View_". The shader will then activate its magic:

![Add As Top-Level View menu option](https://user-images.githubusercontent.com/941331/216389857-b4b78162-da81-432b-ae40-0ddbc80f972f.png)

When in 360 mode, hold Shift and drag with the left click to orbit.

You can also **adjust the FOV interactively** if go again to the _Image_ menu, _Lat-Long Viewer_ section and "_Adjust Focal Length_":
![Adjust FOV menu option](https://user-images.githubusercontent.com/941331/216419050-28eaf24f-6e94-4292-b96f-219736b600d3.png)
and you should see an overlay explaining at the top:
![FOV mode overlay](https://user-images.githubusercontent.com/941331/216419455-96cd6fa1-eea7-4a19-be45-02c513f3aa30.png)
As it says, hit "?" on your keyboard for additional hotkey tips:
![FOV overlay hotkeys](https://user-images.githubusercontent.com/941331/216419596-da1ddf46-5dcf-49da-b8eb-59bb9dd0059a.png)
As it says in the overlay, you can "scrub" (by mouse-dragging horizontally) to smoothly adjust the FOV, or go in increments with the +/- keys or the mouse wheel:

![interactive FOV adjustment in RV](https://user-images.githubusercontent.com/941331/216420487-1db715a5-289b-4a04-b627-ae6fe7f91ba8.gif)

Hopefully this explainer helps a bit. If you have any other RV questions, shoot away! ;)

**Comment by ggarra13** [comment]
Ok.  I gave up on the shader as that was a really bad approach.  I took a geometric approach like I did with mrVIewer 1.

You should find all issues addressed in this .exe installer of the upcoming v0.3.2:

https://mega.nz/file/3OIjDQzA#beffSmo-JuVjxdKhYlDGHlTvttzDHFXyEtDAUtumyYg

Three things:  

* To move around the projection, you have to use the middle mouse button (as when you do when there's no projection).
* You cannot draw annotaions on the projection.  I am not sure I can lift that limitation easily.
* I added also Cubic projections, as those found in OpenEXR cubic maps.

**Comment by ggarra13** [comment]
I added a subdivision option in the Environment Map panel that controls the subdivision of the sphere.  Let me know if the defaults are too small.  Note that once you change the defaults, they will get saved in the mrv2.prefs file so you will never have to set them again.
I admit I was rather cheap in setting the original subdivisions.   With the nature of a geometric sphere and a mapped cyllinder on it you can never get rid of the distortions, you can only minimize it as you are bound to the UVs being sampled at poles.  RV, using a shader, can get away with it as it samples on every pixel of the shader instead of at triangle verticies.  However, RV's approach also has its drawbacks.  Mainly you need to concatenate shaders if you want to keep the whole pipeline working.  That approach was fine when it was only OpenGL that we were dealing with, but now that we are apparently moving into having to support Metal (and maybe DirectX too) it means writing parsers for multiple shader languages.  Also, supporting cubic environment maps in a shader is afaik problematic.

Anyway, here's a new beta of mrv2 v0.3.2.  Try it and see what you think:

https://mega.nz/file/nDQnlZYK#iUbXuvNM7IGV8NIXOS0HcQ05A49DX3wJa4fLfI2uL84

I was not fully able to grasp the issue with the panning as a joystick (it seems fine to me), so l'll need you to send me a screen capture video for me to see what you mean.

**Comment by ggarra13** [comment]
Here's a new beta of v0.3.3, which adds a spin option to the Envionment Map panel.  With it, the dragging becomes a pushing into one direction, which stops after a while.  I think that's what I interpreted you wanted.

Win64 .exe
https://mega.nz/file/3fJhAAiJ#tW09htz7bPm5hQ8EODYbLEJfTRV1uxUsvh1O_9s_58Y

Win64 .zip
https://mega.nz/file/3OQiTBaC#23-S5CkgAeFaItwmw0jwgMv4eH7jGbtEy3S36VP3-vI
