### ISSUE TITLE
libselinux missing from tarball

### ISSUE THREAD

**Issue by mruegenberg** [ggarra13/mrv2#51]
Hello,
when trying to run the player form the .tar.gz of the latest release I get an error about libselinux missing: 

~~~
./mrv2.sh 
$HOME/Downloads/mrv2-v0.5.2-Linux-amd64/usr/local/mrv2-v0.5.2-Linux-64/bin/mrv2: error while loading shared libraries: libselinux.so.1: cannot open shared object file: No such file or directory
~~~

When copying a libselinux from elsewhere on my computer to the `lib` dir in the distribution it starts successfully.

This is on Arch Linux.

**Comment by mruegenberg** [comment]
Hi @ggarra13 , I'm not using selinux, so it's not available within my main LD_LIBRARY_PATH.
Sounds like maybe this shouldn't really be linked against? Probably it's coming from some dependency?

I found the library on my system in the distributions for Steam and Meshroom, so at least in those cases it's considered worth distributing. (Meshroom is also where I copied the library from to allow me to start mrv2)

**Comment by ggarra13** [comment]
Ok.  Thanks for the advice.  Can you tell me if Steam or Meshroom also distributes libmount with it?  Distributing libselinux only created a warning about lack of version of the library for libmount.so.1 in my Ubuntu 22.04 box when I started mrv2.

**Comment by ggarra13** [comment]
Ok.  It is a dependency of libpango that cannot be avoided.  I am adding libselinux and libmount to the distribution to fix it.  Can you please download this version of v0.5.3 and verify that it works for you with no errors or warnings of any kind:

https://mega.nz/file/aLpUBKRK#swwzcOLVvI1wKpsqpV5NU5vr1zW1vMf6mCf71W4Sdp8

**Comment by mruegenberg** [comment]
Hi, sorry for the slow reply. It seems that Meshroom/Steam do not include libmount, but for instance Natron does, which I imagine might have similar requirements to mrv2.
I do have pango installed, but it seems on my system this does not require libselinux, and neither does libgio/glib2, so it might be theoretically possible to do without, but probably not with the version provided by Ubuntu.

I also tested the new tarball you provided and everything appears to be working perfectly, thank you!
