### ISSUE TITLE
[MacOS 13+] Unable to move the native file browser window

### ISSUE THREAD

**Issue by p2or** [ggarra13/mrv2#56]
Hi @ggarra13,

I just noticed that I can not move/drag the MacOS File Browser while opening an arbitrary image sequence. Also the title of the window is markable which is probably not intended, right?

<img width="665" alt="Screenshot 2023-06-03 at 20 12 46" src="https://github.com/ggarra13/mrv2/assets/512368/03d7e027-ec4b-4269-9a40-0e36573d6169">

Cheers,
Christian

**Comment by ggarra13** [comment]
That's how the native file requester works on macOS on both accounts.  There's nothing special that mrv2 is doing, AFAIK.

On my machine, I can get it to turn on/off at will and upon exiting the application, the latest value set is the one that is stored in the preferences.

You can check (and change/remove) the value at:

/Users/your_name/.filmaura/mrv2.prefs

Look for the key:

native_file_chooser: <VALUE>

in the [./loading] section of the preferences.

Let me know if it is not 0 and if removing the setting does not reset the file chooser.

**Comment by p2or** [comment]
Hi @ggarra13,

> That's how the native file requester works on macOS on both accounts. 

good to know, thanks. If there is no way to customize this behavior, then so be it. I personally can deal with that - I just noticed it and wanted to let you know.

Cheers,
Christian
