### ISSUE TITLE
Have caching be in the form of GB versus seconds

### ISSUE THREAD

**Issue by throb** [ggarra13/mrv2#6]
Please change the caching phrasing to GB versus seconds. I just want to tell the system it has 48gb of ram to work with, and just use what you need to do the job.

**Comment by SteffenDuenner** [comment]
This would be awesome.
Additionally, a "percentage of physical RAM" and an option to "leave at least ...MB" free. :)

Just like this:
![image](https://user-images.githubusercontent.com/33224667/227714953-a2b5957c-f4b0-470a-9519-a40afd0b29d3.png)

**Comment by ggarra13** [comment]
@SteffenDuenner In current HEAD of main, there's a new Cache/Gigabyte setting in the Settings Panel.  When set to a number other than 0, it will use that number to automatically calculate the Read Ahead / Read Behind based on video resolution, bit depth, FPS and active videos (wipes, etc).
Since you compile mrv2 yourself, can you give it a go and let me know you think.

**Comment by SteffenDuenner** [comment]
Great! This sounds very smart. I'll report back as soon as I have access to my workstation, hopefully tomorrow evening.

**Comment by SteffenDuenner** [comment]
I'm finally back and compiled the latest main.
What I nice new feature! With the footage I tested the cache filled up quickly and the cached images were properly kept in memory. I noticed nothing bad or weird so far. 👍🏻

**Comment by ggarra13** [comment]
@SteffenDuenner I updated mrv2's GB cache again in the repository, as I realized that it was over-allocating the seconds read ahead by 5 times.  That's why you were getting mrv2 to use 60GB, instead of 50GB.  Now it is much more conservative.  Give it a try and report back how it works for you.

**Comment by SteffenDuenner** [comment]
Thanks for the update. I just gave it a try and now it looks like the amount of RAM cache that actually gets used is only 1/5 of the size I set. So for example if I set it to 50GB mrv2 only caches 10, if I set it to 62GB I only get get around 12,5.

**Comment by SteffenDuenner** [comment]
While playing around with caching I thought it would be pointless to just throw numbers at you. Sadly I can't upload the sequences I use currently (copyright bla) so I quickly created and uploaded a simple EXR sequence (1000 frames, 4608x3164 pixels resolution, pixel aspect 2:1, DWAB compression). It's just a simple white circle randomly flying around:
https://1drv.ms/u/s!AlOpRG0iPvzdhKMZuZBy9KfbkZYk6w?e=6hXCI9

This sequence can completely fill my 64GB of RAM, so I have something to do some more serious testing with. I'll also use this sequence for a different bug report I'm currently working on ;)

With this sequence if I set my max cache size to 50GB I get around 27GB max. If I set it to 5GB max -> 3,3GB. 10GB max -> 6GB.

**Comment by ggarra13** [comment]
No, the issue is that I was calculating everything as it was RGB, while most movies are YUV.  I talked to @darbyjohnston and he pointed me to a function of his that should give better size estimates. 
I updated main again.  Give it a try and let me know how it goes.

**Comment by SteffenDuenner** [comment]
Ah! After some testing this latest version feels much more predictable. Nice!
