### ISSUE TITLE
Unexpected behavior switching between Fullscreen and Presentation modes.

### ISSUE THREAD

**Issue by danbradham** [ggarra13/mrv2#62]
Hello there, thank you for creating an essential and convenient media player!

I noticed that there are some small conflicts between Fullscreen and Presentation modes.

# Switching from Fullscreen to Presentation mode
### Current Behavior
Pressing F12 for Fullscreen then pressing F11 results in exiting Fullscreen but does not enter Presentation mode. It also results in the background color of the app turning black rather than remaining the standard dark grey.

### Expected Behavior
Pressing F11 should always activate Presentation mode from Fullscreen.

In addition if I enter Fullscreen mode from Presentation mode by pressing F12, then exit Fullscreen again by pressing F12, I am no longer in Presentation mode. Ideally the state of Presentation mode should remain the same if I am toggling Fullscreen mode.

**Comment by ggarra13** [comment]
You got the hotkeys reversed (F12 is for Presentation and F11 is for FullScreen), but I understood what you mean anyway.

**Comment by danbradham** [comment]
Woops, thanks!

**Comment by ggarra13** [comment]
Fixed in main HEAD.
