### ISSUE TITLE
Last frame is not visible in timeline.

### ISSUE THREAD

**Issue by danbradham** [ggarra13/mrv2#63]
The timeline seems like it's 1 frame short. If I scrub to the end the current frame marker ticks just outside view!
![image](https://github.com/ggarra13/mrv2/assets/3354242/bdf52e1c-8d90-4340-a8c4-0e6fbb571308) 
![image](https://github.com/ggarra13/mrv2/assets/3354242/1ea9322f-c0cf-46e5-bbf9-93d864f7a023)

**Comment by ggarra13** [comment]
I'll take a look at it for the next version.

**Comment by ggarra13** [comment]
This is fixed in main HEAD now.
