### ISSUE TITLE
Media Information panel opens with collapsed scroll area.

### ISSUE THREAD

**Issue by danbradham** [ggarra13/mrv2#64]
When I open the Media Information panel, the scroll area does not take up the whole height of the panel. Once I resize the application, the scroll area expands as expected.

## Immediately after open
![image](https://github.com/ggarra13/mrv2/assets/3354242/88e58a5d-8200-4267-af34-5e3d052091f7)

## After resizing application window
![image](https://github.com/ggarra13/mrv2/assets/3354242/961dd65d-1203-4612-9ea7-14a3fe2cb4f3)

**Comment by ggarra13** [comment]
Yes.  I noticed that myself.   I also found out that mrv2 would crash if you leave the media info panel viisible on exiting and re-loading the application with an openexr sequence from the command-line.  I'll see to fix both issues in the next release.

**Comment by ggarra13** [comment]
The problem seems to happen when starting mrv2 from the command-line and with a movie file.  Still investigating...

**Comment by ggarra13** [comment]
Ok.  I have a beta of v0.6.2 for you to try.  I saw you are on Windows, so here are the windows binaries:

.zip file
https://mega.nz/file/ffQS0C4A#gMA0SAOmuG27ggxKRTAMluOZzfgzA5YB6Ua2Z2xYeWA

.exe installer
https://mega.nz/file/WWYkAbKb#6sOA52OqzLk4p7JMvq2gglmXjx8XygwXu1XlWRaW8ks

**Comment by danbradham** [comment]
Thank you!
