### ISSUE TITLE
Request for richer zoom controls and exposed window fitting options.

### ISSUE THREAD

**Issue by danbradham** [ggarra13/mrv2#65]
One thing I'm missing is control over the precise level of zoom. 

Ideally I'd be able to set 25 / 50 / 75 / 100/ 125 / 150/ 200 percent zoom. In conjunction with zoom levels, it's nice to be able to choose whether the video should resize with the application window, or if the video size and position should remain locked even when resizing the application window.

**Comment by danbradham** [comment]
Wait a moment...I found the zoom controls in the bottom left.
![image](https://github.com/ggarra13/mrv2/assets/3354242/f1ce68dd-7c23-435a-8b5d-2b4161b668f9)

This is great, the only thing is that the video is still refit when resizing the application window.

**Comment by ggarra13** [comment]
You can also use the number keys from 1 to 9 for the zoom levels and 0 for 1:1.  You can also use Shift + 1 to 9 to zoom at 1/size.

To make the video not refit, you can go to Window->Preferences->User Interface, and turn off Auto Refit.  Albeit I find that a tad confusing to work with.

**Comment by danbradham** [comment]
Ah thank you! Turning off Auto Refit does work but there are a couple of quirks.

1. The setting doesn't take effect until after restarting the application.
2. With `Auto Refit` off the media seems to be pinned to the lower left corner of the application which is a bit counter-intuitive.

**Comment by ggarra13** [comment]
1,  Fixed in main HEAD.
2. Not much I can do about that one.  You can press "h" to center the view at any time while keeping the zoom factor.
