### ISSUE TITLE
Save Session shortcut on Windows is Meta+S, what key is that? 

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#66]
In File > Save > Session the shortcut is listed as **Meta+S** on Windows. Is this a key that appears usually on a modern keyboard?

![image](https://github.com/ggarra13/mrv2/assets/2439881/f4567647-9b0d-4e74-ae31-82eaefd9b8a4)

The shortcut appears to be defined [here](https://github.com/ggarra13/mrv2/blob/e12a0c73e09bd1f3e6bb3a22aea95a32e872f542/mrv2/lib/mrvCore/mrvHotkey.cpp#L33)

I've personally never heard of the Meta key before. According to this [Wikipedia page on the Meta key](https://en.wikipedia.org/wiki/Meta_key) it's a key that used to be found more keyboards but doesn't appear as much nowadays. I wonder whether it's the currently set to the right shortcut on Windows and something like CTRL+S might make more sense.

**Comment by ggarra13** [comment]
Yes.  The Meta key on Mac is the Cmd key, but on Windows it should be as you guessed the Windows key.  Unfortunately, with Windows 10/11 Microsoft added a lot of internal shortcuts to their OS and you cannot get them to work anymore.

I will move the shortcut to CTRL+s on startup. Note that if you already created a mrv2.keys.prefs file in your home directory you will need to remove it ot manually do the CTRL+s change on the Window->Hotkeys.

**Comment by BigRoy** [comment]
Thanks. Sounds good to me!

**Comment by BigRoy** [comment]
Would it still be possible to also list the shortcut as CTRL+S on Windows. I'm seeing this in 0.7.9:

![image](https://github.com/ggarra13/mrv2/assets/2439881/be2db591-cc8d-4510-947c-ef8205cb6136)
