### ISSUE TITLE
Timeline thumbnail previews make timeline very slow

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#69]
It seems that scrubbing through the timeline (hold mouse down and drag) is quite laggy. It results in frame updates only every 100ms or 200ms, whereas with the Scrubbing Tool the viewport responds pretty instantaneous. I could even reproduce this behavior on for example a very low-res MP4 file. (The timeline is green and thus cached?)

Some more testing showed that the viewport playback also stutters quite a bit if during playback you move the mouse over the timeline. If you keep dragging back and forth over the timeline it seems that during that time the viewport + timeline don't update at all (until your mouse is static for a short moment and it directly plays back again)

This is resolved if you disable the checkbox for **Window > Preferences > Timeline > Preview Thumbnail**. Then both dragging through the timeline + moving over timeline during playback becomes real-time.

As such, there appears to be an update issue related to the timeline thumbnails where it doesn't update the UI whenever it tries to update the thumbnail.

---

Tested on Windows 10 
Build mrv2 0.61

**Comment by ggarra13** [comment]
I will look into this, as I cannot reproduce it at least on Linux.  Do you see the problem with both sequences and movies?  What resolution should I test with?  
For information, the thumbnail picture of the timeline is not reading from the cache but starting a new thread, as the tlRender API is currently still somewhat limited on how to access the cache which is what makes it slow.
This should change in the new version of tlRender I believe, so expect to see some improvements some months from now.

**Comment by BigRoy** [comment]
> Do you see the problem with both sequences and movies? What resolution should I test with?

Yes, both sequences and videos. Resolution didn't seem to matter much. I got it with a png sequence of 1280x895 and with a video of 1920x1080 and a video of 502x334. 

> For information, the thumbnail picture of the timeline is not reading from the cache but starting a new thread, as the tlRender API is currently still somewhat limited on how to access the cache which is what makes it slow.
> This should change in the new version of tlRender I believe, so expect to see some improvements some months from now.
 
Thanks, good to know. It's easily reproducable here on two Windows machines so if you have a machine available definitely give it a go.

**Comment by ggarra13** [comment]
I was able to reproduce it on Windows.  It seems to be an FLTK or Windows bug with windows when repositioning the windows while dragging.  I put a work-around for now, where the thumbnail window will not reposition while dragging and only on mouse release.
If you compile from source, it is in main HEAD now.
