### ISSUE TITLE
Unable to save MP4 movie file with H264 profile

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#70]
### Issue

When using **File > Save > Movie or Sequence** it doesn't seem be able to export H264 profile.

![image](https://github.com/ggarra13/mrv2/assets/2439881/07107fac-0733-49af-a763-1f357b08a197)

To reproduce:
1. Try to save to `hello_world.mp4` 
2. Saving Options > Profile H264

Logs show:
```
ERROR: [save] C:/Users/User/Desktop/hello_world.mp4: Unknown error occurred
```

![image](https://github.com/ggarra13/mrv2/assets/2439881/132f9089-12db-411f-b5f0-d0ecdd05d8f1)
![image](https://github.com/ggarra13/mrv2/assets/2439881/93bb1b71-ba33-4bd0-aa01-74c72a69f295)

---

### Specifications

Tested in mrv2 0.61 on Windows 10.

---

### Additional info

Additional bug, when trying to save again afterwards the Save Dialog remembers the last filename - if that file exists then it directly highlights/selects it in the view as well. Then if you type a different name to write to it will still save to the selected entry and NOT to the manually typed name. The only workaround seems to be to clear the filename, browse to a different folder, go back into the folder and then type the name you want to write to instead.

If you write a `.mp4` or `.m4v` file without a PROFILE selected (it's set to None in the Saving Options) then it writes out a file that mrv2 can read and playback, however when e.g. dropping them into an application like Slack the video will not play back correctly. (Likely unsupported codec?). As such, it currently seems to be impossible to write out a decent MP4 file to share with a client that works in e.g. an app like Slack they might be using.

**Comment by ggarra13** [comment]
@BigRoy Encoding of H264 movies requires x264 with a GPL License.  Unfortunately, that license is incompatible with mrv2's BSD-3 License.

The bug with the file requester is fixed in main HEAD.

**Comment by BigRoy** [comment]
> Encoding of H264 movies requires x264 with a GPL License. Unfortunately, that license is incompatible with mrv2's BSD-3 License.

That's only really the case then for the precompiled releases, right? If one were to compile with ffmpeg manually it could support the x264 just fine? If so, any input on how to do so?

**Comment by ggarra13** [comment]
Alternatively, you can try the instructions (untested by me):

https://www.roxlu.com/2019/062/compiling-ffmpeg-with-x264-on-windows-10-using-msvc

**Comment by ggarra13** [comment]
I placed a script called ffmpeg_windows_gpl.sh in the root of mrv2 that will compile libx264 and ffmpeg on Msys.  The only thing missing is that it will not support webm (libvpx).

**Comment by ggarra13** [comment]
I updated ffmpeg_windows_gpl.sh to also compile libvpx, so you get a full GPL build of mrv2.
