### ISSUE TITLE
Move "About" menu entry from "Window" to "Help" menu

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#71]
### Issue

I was looking for the About dialog for my specific mrv2 build and at first couldn't find it. Then I unexpectedly saw it under the **Window** menu.

As far as I know most applications provide the About pop-up from the **Help** menu entry. A quick look around in some other apps, e.g. VLC, DJV, PyCharm, Maya, Slack desktop app, Firefox, etc. they all seem to have the **About** menu entry in the **Help** menu.

Should we move the About entry to match more with many other applications?

**Comment by ggarra13** [comment]
Agreed.   Fixed on main HEAD.
