### ISSUE TITLE
Tapping Alt stops UI from updating.

### ISSUE THREAD

**Issue by danbradham** [ggarra13/mrv2#74]
# Issue
Pressing the `Alt` key alone causes the UI to freeze until the next user interaction (mouse click or key press). Audio and Video playback continue while the UI is frozen and there don't seem to be any adverse effects or crashes.

I discovered this behavior while attempting to focus / show the top menu using the `Alt` key, which is the standard hotkey on Windows.

**Comment by danbradham** [comment]
Upon closer inspection, it seems the Alt key is focusing on the windows dialogs builtin menu rather than the applications menu.

![image](https://github.com/ggarra13/mrv2/assets/3354242/32a72e0a-61b4-47c2-9da1-d7eccd755086)

**Comment by ggarra13** [comment]
I've fixed it on the recently release v0.6.2.  Note that it is not possible to access the menus with Alt, thou.
