### ISSUE TITLE
Python Panel UnicodeDecodeError when running script single line of code

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#78]
When running a script in the Python Panel then this works fine:

```python
(empty line)
import os
```
_I typed empty line because otherwise Github still didn't show it if it was an empty line.

👇 But this doesn't:
```python
import os
```

The error is:
```python
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte
```

👇 But it does work if you have more than one line of code:
```python
import subprocess
import os
```

Some others:

👇  Does not work:
```python
import os
(empty line)
```

👇 Does work:
```python
import os
(empty line)
import subprocess
```

In short, it seems a bit picky with running a single line of code.

---

Tested on Windows in both MRV2 0.6.3 and 0.6.1.

**Comment by ggarra13** [comment]
Fixed in HEAD.

**Comment by BigRoy** [comment]
Seems fixed 👍
