### ISSUE TITLE
UX: Width of volume slider seems too wide

### ISSUE THREAD

**Issue by BigRoy** [ggarra13/mrv2#79]
When looking at the Volume slider it seems that the draggable control in it appears very wide for the width of the volume control itself, e.g. see this:

![image](https://github.com/ggarra13/mrv2/assets/2439881/88f2982b-3e64-4851-afd1-683790f4bc74)

Even when the UI is less wide it still appears quite large:

![image](https://github.com/ggarra13/mrv2/assets/2439881/b2d9612f-da77-42c0-ad67-94f878896c5a)

I'd have expected a slider look more like the Gamma slider:

![image](https://github.com/ggarra13/mrv2/assets/2439881/da4285ca-a52c-49be-9f09-15b7be1d1435)

When the UI is less wide the gamma slider keeps the same width:

![image](https://github.com/ggarra13/mrv2/assets/2439881/f9f62967-15d1-4ef7-bdd3-d6d270d11111)

As such I suppose the volume slider knob is missing a maximum width (or explicit width)?

---

Side note:

Also visually I think it'd help if the button stands out a bit more of the control's background for all these sliders. For example the "gain" slider I had to look again a few times to spot it:

![image](https://github.com/ggarra13/mrv2/assets/2439881/226f65ed-b562-41d8-a9f6-8d38fe546fbe)

---

Tested on Windows in MRV2 0.6.4 (beta build from [here](https://github.com/ggarra13/mrv2/issues/68#issuecomment-1616495976))

**Comment by ggarra13** [comment]
Both issues Improved on HEAD.  Thanks.
