### ISSUE TITLE
UI preferences refuse to load / 

### ISSUE THREAD

**Issue by KonkaBass** [ggarra13/mrv2#90]
Having an issue where no matter what I've selected in the "UI Elements" tab in Preferences the program will only load the initial startup defaults. 

even on program load, everything is active, and if I go to the "View" dropdown, it even shows the same selections I've made in the Preferences, yet, all the unwanted UI elements are showing. Then when I select one that I dont want, that is on, that says it isn't, it will hide, and then suddenly on the next time I open the View dropdown, everything is selected once again.
![mrv2 issue](https://github.com/ggarra13/mrv2/assets/54293831/5350e04b-e97d-483e-a4d9-13202839bf3c)

**Comment by ggarra13** [comment]
I was able to verify that it was broken in v0.7.0 and the first release version of v0.7.1.  I've re-released v0.7.1.  Please download it from the github code/release page or from sourceforge.net.
