### ISSUE TITLE
OCIO no longer working

### ISSUE THREAD

**Issue by SteffenDuenner** [ggarra13/mrv2#91]
I just noticed that the latest main (maybe even before) version of mrv2 doesn't seem to react to anything OCIO any more.

I tried several OCIO configs (AgX different versions, Filmic Blender, ...) and the "cg-config-v1.0.0_aces-v1.3_ocio-v2.1.ocio" coming with it and none of them works. No matter what I set the input or display transform to, all I get is the same. linear result.

**Comment by ggarra13** [comment]
Thanks for the bug report.  I just realized a last minute change in tlRender let OCIO inoperative.   If you are compiling from main, do: 

$ git pull
$ git checkout main
$ ./runmeq.sh      # or ./runme.sh for the full build.

I'll have new v0.7.1 binaries in about half an hour.

**Comment by ggarra13** [comment]
Binaries are now available at github/releases as well as in sourceforge.net.
