### ISSUE TITLE
DWA compression Value check

### ISSUE THREAD

**Issue by 360highdynamicrangehdr** [ggarra13/mrv2#92]
Options OpenEXR
example DWA compression 2000.0

When using **File > Save > Movie or Sequence**

![Untitled 141](https://github.com/ggarra13/mrv2/assets/25839678/bad5c99e-a398-40de-a908-64f8868399fc)

**before**
![Untitled 142](https://github.com/ggarra13/mrv2/assets/25839678/b4cefa90-a7a3-4f60-a04d-f037bf549869)

**after**
![Untitled 143](https://github.com/ggarra13/mrv2/assets/25839678/aed6987c-23dd-48a3-b807-0d4f8ef5eb5b)

Range of valid values:
`>= 0.0f`

**Comment by ggarra13** [comment]
Not sure I understand your pictures.  Are you saying that:

a) Zip Compression should also be active with DWA compression not only with ZIP and ZIPS?
b) DWA compression should have a bigger range (up to 2000 or more)?
c) Something else?

**Comment by ggarra13** [comment]
I merged your PR #96.  I am closing the issue now.
