### ISSUE TITLE
Ability to save current frame as image 

### ISSUE THREAD

**Issue by Thane5** [ggarra13/mrv2#95]
mr viewer 1 had this useful feature to save the current frame as a still image. I could not find this feature in mrv2, so unless it was moved somewhere that i missed, i would love to see this feature come back.

![image](https://github.com/ggarra13/mrv2/assets/13683581/691e16d2-9937-4b10-9c2f-bd4af3a3f066)

**Comment by ggarra13** [comment]
I have added this for the next release.  On the mean time, you can save a single frame if you set the In and Out points to the same frame and use Save Movie or Sequence.  The image will get saved with a number in it, thou.

**Comment by ggarra13** [comment]
mrv2 v0.7.5 now has this feature available.  Enjoy and make sure to report any bugs you find.
