### ISSUE TITLE
error opening .exr - macOs

### ISSUE THREAD

**Issue by verstaerkermusic** [ggarra13/mrv2#97]
when trying topen an .exr file with right click "open with mrv2" I get an error saying that mrv2 cannot open openexr files
<img width="257" alt="image" src="https://github.com/ggarra13/mrv2/assets/25081656/1905215d-4da5-492c-9221-27eef70186d6">

if I drag n dop the file into mrv2 it works fine

i have the same issue when using the DJVplayer - so maybe that's in one of the libraries in the program ?

**Comment by ggarra13** [comment]
It is an issue with macOS "protected" directories (ie. Desktop, Documents, etc).  Older versions of macOS would not allow non-certified applications to open those directories.  Since both mrv2 and DJVplayer are non-certified (ie. they were not registered with Apple at U$100/a year), they run into those issue.
Fortunately since then, Apple has changed its stance on newer versions of macOS (Ventura, etc).

**Comment by ggarra13** [comment]
Ah.  Okay.  That's new.  Unfortunately, I don't have an external drive to test.  Can you open .exr files from other directories (ie. not the private macOS directories)?  Or it does not work with *any* .exr files?

**Comment by ggarra13** [comment]
Never mind.  I was able to reproduce it.  I'll look into it.

**Comment by verstaerkermusic** [comment]
actually I noticed  this isn't even exclusive to .exr files... it's true for all file.. not matter what type and where they are located
tried local internal drive, external ssd and NAS

I thought for a moment it's related to my M2 machine...  but I remember that DJV2 had the issue also on my Intel_Mac

So maybe macOs 13.x related?  Still how come that DJV1 works fine

**Comment by verstaerkermusic** [comment]
> Never mind. I was able to reproduce it. I'll look into it.

ah cool. Thank you!

**Comment by ggarra13** [comment]
I looked into it, and, unfortunately, I don't have good news.  It is also an issue with macOS' Gatekeeper that prevents non-certified applications from opening files that way.  The solutions are to:

a) compile mrv2 yourself
b) use the file requester or drag and drop
c) contribute U$ 100 so I can register the application (go to mrv2.sourceforge.io and click on Donate). 

Older applications like djview or mrViewer do not run into the issue as Gatekeeper knows they were created before macOS implemented these new rules.

**Comment by verstaerkermusic** [comment]
hi
thanks for looking into the issue. Currently I will deal with drag n drop and clicking away the error messages. 
If I have some money to spend I'll contact you
