### ISSUE TITLE
Upgrade to OpenEXR 3.2

### ISSUE THREAD

**Issue by 360highdynamicrangehdr** [ggarra13/mrv2#98]
Upgrade OpenEXR 3.1.7 to 3.2 [new](https://openexr.com/en/latest/news.html#august-30-2023-openexr-v3-2-0-released)

![Untitled 144](https://github.com/ggarra13/mrv2/assets/25839678/b867c5ae-4685-4f16-b289-5844f417d3b5)

Tested on Windows in MRV2 0.7.2

**Comment by ggarra13** [comment]
mrv2 v0.7.2 has not been released yet.  OpenEXR v3.2.0 has been released only three days ago and currently does not work cleanly on Linux.

**Comment by ggarra13** [comment]
Fixed for v0.7.7 and already in main.
